// Deals Hub Data - Student Discounts and Local Deals

export interface Deal {
  id: string;
  title: string;
  description: string;
  discount_percent: number | null;
  discount_text: string;
  category: 'streaming' | 'software' | 'food' | 'transport' | 'shopping' | 'services' | 'local' | 'entertainment';
  brand: string;
  link: string | null;
  university_id: string | null; // null = available everywhere
  country: 'US' | 'UK' | 'CA' | 'ALL'; // Which country this deal is available in
  expires_at: string | null;
  is_verified: boolean;
  submitted_by: string | null;
  upvotes: number;
  created_at: string;
}

export interface DealCategory {
  id: string;
  label: string;
  icon: string;
}

// Deal categories
export const DEAL_CATEGORIES: DealCategory[] = [
  { id: 'all', label: 'All Deals', icon: '🎁' },
  { id: 'streaming', label: 'Streaming', icon: '📺' },
  { id: 'software', label: 'Software', icon: '💻' },
  { id: 'food', label: 'Food', icon: '🍕' },
  { id: 'transport', label: 'Transport', icon: '🚗' },
  { id: 'shopping', label: 'Shopping', icon: '🛍️' },
  { id: 'services', label: 'Services', icon: '🔧' },
  { id: 'entertainment', label: 'Entertainment', icon: '🎬' },
  { id: 'local', label: 'Local', icon: '📍' },
];

// Storage key
const STORAGE_KEY_DEALS = 'noor_user_deals';
const STORAGE_KEY_UPVOTES = 'noor_deal_upvotes';

// ============================================================================
// US DEALS
// ============================================================================

const US_DEALS: Deal[] = [
  // Streaming
  {
    id: 'us-spotify',
    title: 'Spotify Premium Student',
    description: 'Get Spotify Premium, Hulu, and SHOWTIME for one low price.',
    discount_percent: 50,
    discount_text: '$5.99/month (normally $11.99)',
    category: 'streaming',
    brand: 'Spotify',
    link: 'https://www.spotify.com/us/student/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 342,
    created_at: '2025-09-01',
  },
  {
    id: 'us-apple-music',
    title: 'Apple Music Student',
    description: 'Stream over 100 million songs ad-free with Apple TV+ included.',
    discount_percent: 50,
    discount_text: '$5.99/month',
    category: 'streaming',
    brand: 'Apple',
    link: 'https://www.apple.com/apple-music/student/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 287,
    created_at: '2025-09-01',
  },
  {
    id: 'us-youtube',
    title: 'YouTube Premium Student',
    description: 'Ad-free videos, background play, and YouTube Music Premium.',
    discount_percent: 50,
    discount_text: '$7.99/month',
    category: 'streaming',
    brand: 'YouTube',
    link: 'https://www.youtube.com/premium/student',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },
  {
    id: 'us-hbo-max',
    title: 'Max (HBO) Student Discount',
    description: 'Stream HBO, Warner Bros movies, and exclusive originals.',
    discount_percent: 50,
    discount_text: '$7.99/month with ads',
    category: 'streaming',
    brand: 'Max',
    link: 'https://www.max.com/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 156,
    created_at: '2025-09-01',
  },
  {
    id: 'us-paramount',
    title: 'Paramount+ Student',
    description: 'Stream CBS, BET, Comedy Central, MTV, Nickelodeon content.',
    discount_percent: 25,
    discount_text: '$5.99/month',
    category: 'streaming',
    brand: 'Paramount+',
    link: 'https://www.paramountplus.com/student/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 89,
    created_at: '2025-09-01',
  },
  {
    id: 'us-peacock',
    title: 'Peacock Student Plan',
    description: 'NBC, Universal movies, Premier League, and WWE.',
    discount_percent: 50,
    discount_text: '$2.99/month',
    category: 'streaming',
    brand: 'Peacock',
    link: 'https://www.peacocktv.com/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 76,
    created_at: '2025-09-01',
  },

  // Software
  {
    id: 'us-github',
    title: 'GitHub Student Developer Pack',
    description: 'Free access to developer tools, cloud credits, and learning resources.',
    discount_percent: 100,
    discount_text: 'FREE (worth $200k+)',
    category: 'software',
    brand: 'GitHub',
    link: 'https://education.github.com/pack',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 456,
    created_at: '2025-09-01',
  },
  {
    id: 'us-adobe',
    title: 'Adobe Creative Cloud',
    description: 'All Adobe apps including Photoshop, Illustrator, Premiere Pro.',
    discount_percent: 60,
    discount_text: '$19.99/month',
    category: 'software',
    brand: 'Adobe',
    link: 'https://www.adobe.com/creativecloud/plans.html?plan=edu',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'us-microsoft',
    title: 'Microsoft 365 Education',
    description: 'Free Office 365 including Word, Excel, PowerPoint, Teams.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Microsoft',
    link: 'https://www.microsoft.com/en-us/education/products/office',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 398,
    created_at: '2025-09-01',
  },
  {
    id: 'us-notion',
    title: 'Notion Plus',
    description: 'Unlimited blocks and file uploads for students.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Notion',
    link: 'https://www.notion.so/students',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 312,
    created_at: '2025-09-01',
  },
  {
    id: 'us-figma',
    title: 'Figma Education',
    description: 'Free professional plan for students and educators.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Figma',
    link: 'https://www.figma.com/education/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 278,
    created_at: '2025-09-01',
  },
  {
    id: 'us-autodesk',
    title: 'Autodesk Free for Students',
    description: 'AutoCAD, Maya, 3ds Max, Fusion 360 free for students.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Autodesk',
    link: 'https://www.autodesk.com/education/free-software/featured',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 187,
    created_at: '2025-09-01',
  },
  {
    id: 'us-jetbrains',
    title: 'JetBrains Student Pack',
    description: 'Free access to all JetBrains IDEs (IntelliJ, PyCharm, etc.).',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'JetBrains',
    link: 'https://www.jetbrains.com/community/education/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 245,
    created_at: '2025-09-01',
  },

  // Shopping
  {
    id: 'us-amazon',
    title: 'Amazon Prime Student',
    description: '6-month free trial, then 50% off. Free shipping, Prime Video, more.',
    discount_percent: 50,
    discount_text: '$7.49/month after trial',
    category: 'shopping',
    brand: 'Amazon',
    link: 'https://www.amazon.com/amazonprime?planOptimizationId=WLPStudentMonthlyElig498',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 523,
    created_at: '2025-09-01',
  },
  {
    id: 'us-apple-store',
    title: 'Apple Education Pricing',
    description: 'Save on Mac, iPad, and accessories with education pricing.',
    discount_percent: null,
    discount_text: 'Up to $400 off',
    category: 'shopping',
    brand: 'Apple',
    link: 'https://www.apple.com/us-edu/store',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 412,
    created_at: '2025-09-01',
  },
  {
    id: 'us-samsung',
    title: 'Samsung Education Discount',
    description: 'Exclusive student discounts on phones, laptops, tablets.',
    discount_percent: 30,
    discount_text: 'Up to 30% off',
    category: 'shopping',
    brand: 'Samsung',
    link: 'https://www.samsung.com/us/shop/discount-program/education/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 189,
    created_at: '2025-09-01',
  },
  {
    id: 'us-target',
    title: 'Target Circle Student',
    description: 'Extra discounts and deals for verified students.',
    discount_percent: 20,
    discount_text: '20% off select items',
    category: 'shopping',
    brand: 'Target',
    link: 'https://www.target.com/circle/partners/student',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'us-bestbuy',
    title: 'Best Buy Student Deals',
    description: 'Exclusive student pricing on laptops, tablets, headphones.',
    discount_percent: null,
    discount_text: 'Exclusive pricing',
    category: 'shopping',
    brand: 'Best Buy',
    link: 'https://www.bestbuy.com/site/back-to-school/college-student-deals',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 167,
    created_at: '2025-09-01',
  },
  {
    id: 'us-nike',
    title: 'Nike Student Discount',
    description: '10% off everything with UNiDAYS verification.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'shopping',
    brand: 'Nike',
    link: 'https://www.nike.com/help/a/student-discount',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },
  {
    id: 'us-adidas',
    title: 'adidas Student Discount',
    description: '30% off with valid student email.',
    discount_percent: 30,
    discount_text: '30% off',
    category: 'shopping',
    brand: 'adidas',
    link: 'https://www.adidas.com/us/discount-programs',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 176,
    created_at: '2025-09-01',
  },

  // Food
  {
    id: 'us-chipotle',
    title: 'Chipotle Student ID Discount',
    description: 'Show student ID for BOGO or free drink with entree.',
    discount_percent: null,
    discount_text: 'BOGO or free drink',
    category: 'food',
    brand: 'Chipotle',
    link: 'https://www.chipotle.com',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 167,
    created_at: '2025-09-01',
  },
  {
    id: 'us-doordash',
    title: 'DoorDash DashPass Student',
    description: '$0 delivery fees and reduced service fees on eligible orders.',
    discount_percent: 50,
    discount_text: '$4.99/month',
    category: 'food',
    brand: 'DoorDash',
    link: 'https://www.doordash.com/dashpass/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'us-starbucks',
    title: 'Starbucks Rewards',
    description: 'Free birthday drink and stars on every purchase.',
    discount_percent: null,
    discount_text: 'Free birthday drink',
    category: 'food',
    brand: 'Starbucks',
    link: 'https://www.starbucks.com/rewards',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 189,
    created_at: '2025-09-01',
  },
  {
    id: 'us-grubhub',
    title: 'Grubhub+ Student',
    description: 'Free delivery on orders $12+ from participating restaurants.',
    discount_percent: 100,
    discount_text: 'FREE delivery',
    category: 'food',
    brand: 'Grubhub',
    link: 'https://www.grubhub.com/plus/student',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 156,
    created_at: '2025-09-01',
  },
  {
    id: 'us-ubereats',
    title: 'Uber Eats Student',
    description: '$0 delivery fee on orders over $15.',
    discount_percent: null,
    discount_text: 'Free delivery over $15',
    category: 'food',
    brand: 'Uber Eats',
    link: 'https://www.ubereats.com/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 145,
    created_at: '2025-09-01',
  },

  // Transport
  {
    id: 'us-amtrak',
    title: 'Amtrak Student Discount',
    description: '15% off most Amtrak fares with student advantage card.',
    discount_percent: 15,
    discount_text: '15% off fares',
    category: 'transport',
    brand: 'Amtrak',
    link: 'https://www.amtrak.com/student-discount',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 145,
    created_at: '2025-09-01',
  },
  {
    id: 'us-zipcar',
    title: 'Zipcar University',
    description: 'Discounted car sharing membership for students 18+.',
    discount_percent: null,
    discount_text: 'Reduced rates',
    category: 'transport',
    brand: 'Zipcar',
    link: 'https://www.zipcar.com/universities',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 98,
    created_at: '2025-09-01',
  },
  {
    id: 'us-lyft',
    title: 'Lyft Student Discount',
    description: 'Up to 15% off rides with student email verification.',
    discount_percent: 15,
    discount_text: 'Up to 15% off',
    category: 'transport',
    brand: 'Lyft',
    link: 'https://www.lyft.com/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 134,
    created_at: '2025-09-01',
  },

  // Services
  {
    id: 'us-nytimes',
    title: 'The New York Times Digital',
    description: 'Unlimited digital access at discounted student rate.',
    discount_percent: 75,
    discount_text: '$1/week',
    category: 'services',
    brand: 'NYTimes',
    link: 'https://www.nytimes.com/subscription/education',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 134,
    created_at: '2025-09-01',
  },
  {
    id: 'us-headspace',
    title: 'Headspace Student Plan',
    description: 'Meditation and mindfulness app at student pricing.',
    discount_percent: 85,
    discount_text: '$9.99/year',
    category: 'services',
    brand: 'Headspace',
    link: 'https://www.headspace.com/studentplan',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 178,
    created_at: '2025-09-01',
  },
  {
    id: 'us-calm',
    title: 'Calm Student Discount',
    description: 'Sleep and meditation app at reduced student rate.',
    discount_percent: 85,
    discount_text: '$8.99/year',
    category: 'services',
    brand: 'Calm',
    link: 'https://www.calm.com/student',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 145,
    created_at: '2025-09-01',
  },

  // Entertainment
  {
    id: 'us-amc',
    title: 'AMC Student Discount',
    description: 'Discounted movie tickets on Thursdays with student ID.',
    discount_percent: null,
    discount_text: 'Discount Thursdays',
    category: 'entertainment',
    brand: 'AMC Theatres',
    link: 'https://www.amctheatres.com/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 123,
    created_at: '2025-09-01',
  },
  {
    id: 'us-regal',
    title: 'Regal Student Discount',
    description: '10-25% off movie tickets with student ID.',
    discount_percent: 20,
    discount_text: '10-25% off',
    category: 'entertainment',
    brand: 'Regal Cinemas',
    link: 'https://www.regmovies.com/',
    university_id: null,
    country: 'US',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 98,
    created_at: '2025-09-01',
  },
];

// ============================================================================
// UK DEALS
// ============================================================================

const UK_DEALS: Deal[] = [
  // Student Discount Platforms
  {
    id: 'uk-unidays',
    title: 'UNiDAYS',
    description: 'Free student discount platform. Get verified for exclusive deals.',
    discount_percent: null,
    discount_text: 'Up to 50% off 800+ brands',
    category: 'shopping',
    brand: 'UNiDAYS',
    link: 'https://www.myunidays.com/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 567,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-studentbeans',
    title: 'Student Beans',
    description: 'Thousands of student discounts and freebies.',
    discount_percent: null,
    discount_text: 'Up to 60% off',
    category: 'shopping',
    brand: 'Student Beans',
    link: 'https://www.studentbeans.com/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 534,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-totum',
    title: 'TOTUM Card',
    description: 'Official NUS student discount card with 350+ discounts.',
    discount_percent: null,
    discount_text: '350+ discounts',
    category: 'shopping',
    brand: 'TOTUM',
    link: 'https://www.totum.com/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 456,
    created_at: '2025-09-01',
  },

  // Transport
  {
    id: 'uk-railcard',
    title: '16-25 Railcard',
    description: '1/3 off rail fares across Britain for 4 years.',
    discount_percent: 33,
    discount_text: '1/3 off all rail fares',
    category: 'transport',
    brand: 'National Rail',
    link: 'https://www.16-25railcard.co.uk/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 678,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-oyster',
    title: '18+ Student Oyster Photocard',
    description: '30% off adult-rate Travelcards and Bus & Tram Passes.',
    discount_percent: 30,
    discount_text: '30% off London transport',
    category: 'transport',
    brand: 'TfL',
    link: 'https://tfl.gov.uk/fares/free-and-discounted-travel/18-plus-student-oyster-photocard',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 445,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-nationalexpress',
    title: 'National Express Coach',
    description: 'Student discount on coach travel across the UK.',
    discount_percent: 30,
    discount_text: 'Up to 30% off',
    category: 'transport',
    brand: 'National Express',
    link: 'https://www.nationalexpress.com/en/offers/student-discount',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },

  // Streaming
  {
    id: 'uk-spotify',
    title: 'Spotify Premium Student UK',
    description: 'Spotify Premium with ad-free music streaming.',
    discount_percent: 50,
    discount_text: '£5.99/month',
    category: 'streaming',
    brand: 'Spotify',
    link: 'https://www.spotify.com/uk/student/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 389,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-apple-music',
    title: 'Apple Music Student UK',
    description: 'Apple Music with Apple TV+ included.',
    discount_percent: 50,
    discount_text: '£5.99/month',
    category: 'streaming',
    brand: 'Apple',
    link: 'https://www.apple.com/uk/shop/browse/campaigns/apple_music_student',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 312,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-youtube',
    title: 'YouTube Premium Student UK',
    description: 'Ad-free YouTube and YouTube Music.',
    discount_percent: 50,
    discount_text: '£6.99/month',
    category: 'streaming',
    brand: 'YouTube',
    link: 'https://www.youtube.com/premium/student',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-amazon-prime',
    title: 'Amazon Prime Student UK',
    description: '6-month free trial, then 50% off Prime membership.',
    discount_percent: 50,
    discount_text: '£4.49/month after trial',
    category: 'shopping',
    brand: 'Amazon',
    link: 'https://www.amazon.co.uk/joinstudent',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 456,
    created_at: '2025-09-01',
  },

  // Shopping
  {
    id: 'uk-asos',
    title: 'ASOS Student Discount',
    description: '10% off everything with student verification.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'shopping',
    brand: 'ASOS',
    link: 'https://www.asos.com/discover/students/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 378,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-apple',
    title: 'Apple Education UK',
    description: 'Save on Mac and iPad with education pricing.',
    discount_percent: null,
    discount_text: 'Up to £300 off',
    category: 'shopping',
    brand: 'Apple',
    link: 'https://www.apple.com/uk-edu/store',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 345,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-samsung',
    title: 'Samsung Education UK',
    description: 'Student discounts on phones, tablets, laptops.',
    discount_percent: 30,
    discount_text: 'Up to 30% off',
    category: 'shopping',
    brand: 'Samsung',
    link: 'https://www.samsung.com/uk/offer/students/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-topshop',
    title: 'Topshop/Topman Student',
    description: '10% student discount on fashion.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'shopping',
    brand: 'Topshop',
    link: 'https://www.asos.com/topshop/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 189,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-nike',
    title: 'Nike Student UK',
    description: '10% off full-price items with student verification.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'shopping',
    brand: 'Nike',
    link: 'https://www.nike.com/gb/help/a/student-discount-uk',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 256,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-adidas',
    title: 'adidas Student UK',
    description: '20% off with UNiDAYS verification.',
    discount_percent: 20,
    discount_text: '20% off',
    category: 'shopping',
    brand: 'adidas',
    link: 'https://www.adidas.co.uk/student-discount',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 223,
    created_at: '2025-09-01',
  },

  // Food
  {
    id: 'uk-deliveroo',
    title: 'Deliveroo Student',
    description: 'Free delivery on orders with Deliveroo Plus student.',
    discount_percent: null,
    discount_text: 'Free delivery',
    category: 'food',
    brand: 'Deliveroo',
    link: 'https://deliveroo.co.uk/plus',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 312,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-nandos',
    title: "Nando's Student Discount",
    description: '20% off your bill with valid student ID.',
    discount_percent: 20,
    discount_text: '20% off',
    category: 'food',
    brand: "Nando's",
    link: 'https://www.nandos.co.uk/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 456,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-mcdonalds',
    title: "McDonald's Student Deals",
    description: 'Free cheeseburger or McFlurry with meal via app.',
    discount_percent: null,
    discount_text: 'Free items',
    category: 'food',
    brand: "McDonald's",
    link: 'https://www.mcdonalds.com/gb/en-gb/offers.html',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 378,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-dominos',
    title: "Domino's Student Discount",
    description: '35% off when spending £30 or more.',
    discount_percent: 35,
    discount_text: '35% off',
    category: 'food',
    brand: "Domino's",
    link: 'https://www.dominos.co.uk/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 289,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-pizza-hut',
    title: 'Pizza Hut Student',
    description: '25% off via Student Beans.',
    discount_percent: 25,
    discount_text: '25% off',
    category: 'food',
    brand: 'Pizza Hut',
    link: 'https://www.pizzahut.co.uk/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },

  // Entertainment
  {
    id: 'uk-odeon',
    title: 'ODEON Student Discount',
    description: 'Up to 25% off cinema tickets.',
    discount_percent: 25,
    discount_text: 'Up to 25% off',
    category: 'entertainment',
    brand: 'ODEON',
    link: 'https://www.odeon.co.uk/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-cineworld',
    title: 'Cineworld Unlimited Student',
    description: 'Discounted unlimited cinema card for students.',
    discount_percent: null,
    discount_text: '£9.99/month',
    category: 'entertainment',
    brand: 'Cineworld',
    link: 'https://www.cineworld.co.uk/unlimited',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-vue',
    title: 'Vue Student Discount',
    description: '25% off standard tickets on Mondays.',
    discount_percent: 25,
    discount_text: '25% off on Mondays',
    category: 'entertainment',
    brand: 'Vue',
    link: 'https://www.myvue.com/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 167,
    created_at: '2025-09-01',
  },

  // Software
  {
    id: 'uk-github',
    title: 'GitHub Student Developer Pack',
    description: 'Free access to developer tools and cloud credits.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'GitHub',
    link: 'https://education.github.com/pack',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 389,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-adobe',
    title: 'Adobe Creative Cloud UK',
    description: 'All Adobe apps at student pricing.',
    discount_percent: 65,
    discount_text: '£16.24/month',
    category: 'software',
    brand: 'Adobe',
    link: 'https://www.adobe.com/uk/creativecloud/plans.html?plan=edu',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 267,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-microsoft',
    title: 'Microsoft 365 Education UK',
    description: 'Free Office 365 for students.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Microsoft',
    link: 'https://www.microsoft.com/en-gb/education/products/office',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 345,
    created_at: '2025-09-01',
  },

  // Services
  {
    id: 'uk-gymshark',
    title: 'Gymshark Student',
    description: '10% student discount on gymwear.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'shopping',
    brand: 'Gymshark',
    link: 'https://www.gymshark.com/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'uk-puregym',
    title: 'PureGym Student',
    description: 'Reduced membership rates for students.',
    discount_percent: null,
    discount_text: 'From £9.99/month',
    category: 'services',
    brand: 'PureGym',
    link: 'https://www.puregym.com/',
    university_id: null,
    country: 'UK',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 189,
    created_at: '2025-09-01',
  },
];

// ============================================================================
// CANADA DEALS
// ============================================================================

const CA_DEALS: Deal[] = [
  // Student Discount Card
  {
    id: 'ca-spc',
    title: 'SPC Card',
    description: 'Canada\'s #1 student discount card with 450+ partners.',
    discount_percent: null,
    discount_text: '10-30% off at 450+ stores',
    category: 'shopping',
    brand: 'SPC',
    link: 'https://www.spccard.ca/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 567,
    created_at: '2025-09-01',
  },

  // Streaming
  {
    id: 'ca-spotify',
    title: 'Spotify Premium Student Canada',
    description: 'Spotify Premium at student pricing.',
    discount_percent: 50,
    discount_text: '$5.99/month',
    category: 'streaming',
    brand: 'Spotify',
    link: 'https://www.spotify.com/ca/student/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 389,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-apple-music',
    title: 'Apple Music Student Canada',
    description: 'Apple Music with Apple TV+ included.',
    discount_percent: 50,
    discount_text: '$5.99/month',
    category: 'streaming',
    brand: 'Apple',
    link: 'https://www.apple.com/ca/shop/browse/campaigns/apple_music_student',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 312,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-youtube',
    title: 'YouTube Premium Student Canada',
    description: 'Ad-free YouTube and YouTube Music.',
    discount_percent: 50,
    discount_text: '$7.99/month',
    category: 'streaming',
    brand: 'YouTube',
    link: 'https://www.youtube.com/premium/student',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },

  // Shopping
  {
    id: 'ca-amazon',
    title: 'Amazon Prime Student Canada',
    description: '6-month free trial, then 50% off Prime.',
    discount_percent: 50,
    discount_text: '$4.99/month after trial',
    category: 'shopping',
    brand: 'Amazon',
    link: 'https://www.amazon.ca/joinstudent',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 478,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-apple',
    title: 'Apple Education Canada',
    description: 'Save on Mac and iPad with education pricing.',
    discount_percent: null,
    discount_text: 'Up to $400 off',
    category: 'shopping',
    brand: 'Apple',
    link: 'https://www.apple.com/ca-edu/store',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 345,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-samsung',
    title: 'Samsung Education Canada',
    description: 'Student discounts on Samsung products.',
    discount_percent: 30,
    discount_text: 'Up to 30% off',
    category: 'shopping',
    brand: 'Samsung',
    link: 'https://www.samsung.com/ca/offer/education/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-bestbuy',
    title: 'Best Buy Student Canada',
    description: 'Student deals on tech products.',
    discount_percent: null,
    discount_text: 'Exclusive pricing',
    category: 'shopping',
    brand: 'Best Buy',
    link: 'https://www.bestbuy.ca/en-ca/collection/student-savings',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 189,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-nike',
    title: 'Nike Student Canada',
    description: '10% off with UNiDAYS verification.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'shopping',
    brand: 'Nike',
    link: 'https://www.nike.com/ca/help/a/student-discount',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-adidas',
    title: 'adidas Student Canada',
    description: '30% off with student verification.',
    discount_percent: 30,
    discount_text: '30% off',
    category: 'shopping',
    brand: 'adidas',
    link: 'https://www.adidas.ca/en/discount-programs',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 176,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-aritzia',
    title: 'Aritzia Student Discount',
    description: '15% off with student ID.',
    discount_percent: 15,
    discount_text: '15% off',
    category: 'shopping',
    brand: 'Aritzia',
    link: 'https://www.aritzia.com/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 256,
    created_at: '2025-09-01',
  },

  // Food
  {
    id: 'ca-timhortons',
    title: 'Tim Hortons Rewards',
    description: 'Earn points on every purchase, free birthday reward.',
    discount_percent: null,
    discount_text: 'Free rewards',
    category: 'food',
    brand: 'Tim Hortons',
    link: 'https://www.timhortons.ca/rewards',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 345,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-doordash',
    title: 'DoorDash DashPass Student Canada',
    description: '$0 delivery fees on eligible orders.',
    discount_percent: 50,
    discount_text: '$4.99/month',
    category: 'food',
    brand: 'DoorDash',
    link: 'https://www.doordash.com/dashpass/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 267,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-ubereats',
    title: 'Uber Eats Canada',
    description: 'Student deals and free delivery promos.',
    discount_percent: null,
    discount_text: 'Various offers',
    category: 'food',
    brand: 'Uber Eats',
    link: 'https://www.ubereats.com/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-starbucks',
    title: 'Starbucks Rewards Canada',
    description: 'Free birthday drink and stars on purchases.',
    discount_percent: null,
    discount_text: 'Free birthday drink',
    category: 'food',
    brand: 'Starbucks',
    link: 'https://www.starbucks.ca/rewards',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-subway',
    title: 'Subway Student Deal',
    description: '15% off with SPC Card.',
    discount_percent: 15,
    discount_text: '15% off',
    category: 'food',
    brand: 'Subway',
    link: 'https://www.subway.com/en-CA',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 167,
    created_at: '2025-09-01',
  },

  // Entertainment
  {
    id: 'ca-cineplex',
    title: 'Cineplex Student Tuesday',
    description: 'Discounted movie tickets on Tuesdays.',
    discount_percent: null,
    discount_text: '$8.99 on Tuesdays',
    category: 'entertainment',
    brand: 'Cineplex',
    link: 'https://www.cineplex.com/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 289,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-landmark',
    title: 'Landmark Cinemas Student',
    description: 'Student pricing on movie tickets.',
    discount_percent: 20,
    discount_text: '~20% off',
    category: 'entertainment',
    brand: 'Landmark Cinemas',
    link: 'https://www.landmarkcinemas.com/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 145,
    created_at: '2025-09-01',
  },

  // Transport
  {
    id: 'ca-via-rail',
    title: 'VIA Rail Student',
    description: 'Youth fare for travelers 12-25.',
    discount_percent: null,
    discount_text: 'Reduced fares',
    category: 'transport',
    brand: 'VIA Rail',
    link: 'https://www.viarail.ca/en/fares-and-packages/youth',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-greyhound',
    title: 'Greyhound Student',
    description: '10% off bus fares across Canada.',
    discount_percent: 10,
    discount_text: '10% off',
    category: 'transport',
    brand: 'Greyhound',
    link: 'https://www.greyhound.ca/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 156,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-upass',
    title: 'U-Pass',
    description: 'Discounted transit pass through your university.',
    discount_percent: null,
    discount_text: 'Varies by city',
    category: 'transport',
    brand: 'Various Transit',
    link: null,
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 378,
    created_at: '2025-09-01',
  },

  // Software
  {
    id: 'ca-github',
    title: 'GitHub Student Developer Pack',
    description: 'Free access to developer tools and cloud credits.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'GitHub',
    link: 'https://education.github.com/pack',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 356,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-adobe',
    title: 'Adobe Creative Cloud Canada',
    description: 'All Adobe apps at student pricing.',
    discount_percent: 60,
    discount_text: '$25.99/month',
    category: 'software',
    brand: 'Adobe',
    link: 'https://www.adobe.com/ca/creativecloud/plans.html?plan=edu',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-microsoft',
    title: 'Microsoft 365 Education Canada',
    description: 'Free Office 365 for students.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Microsoft',
    link: 'https://www.microsoft.com/en-ca/education/products/office',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 312,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-notion',
    title: 'Notion Plus',
    description: 'Unlimited blocks for students.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Notion',
    link: 'https://www.notion.so/students',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 278,
    created_at: '2025-09-01',
  },

  // Services
  {
    id: 'ca-goodlife',
    title: 'GoodLife Fitness Student',
    description: 'Discounted gym membership for students.',
    discount_percent: null,
    discount_text: 'Reduced rates',
    category: 'services',
    brand: 'GoodLife Fitness',
    link: 'https://www.goodlifefitness.com/',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 198,
    created_at: '2025-09-01',
  },
  {
    id: 'ca-headspace',
    title: 'Headspace Student Canada',
    description: 'Meditation app at student pricing.',
    discount_percent: 85,
    discount_text: '$12.99/year',
    category: 'services',
    brand: 'Headspace',
    link: 'https://www.headspace.com/studentplan',
    university_id: null,
    country: 'CA',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 156,
    created_at: '2025-09-01',
  },
];

// ============================================================================
// GLOBAL DEALS (Available in all countries)
// ============================================================================

const GLOBAL_DEALS: Deal[] = [
  {
    id: 'global-canva',
    title: 'Canva Pro for Education',
    description: 'Free Canva Pro for students and teachers.',
    discount_percent: 100,
    discount_text: 'FREE',
    category: 'software',
    brand: 'Canva',
    link: 'https://www.canva.com/education/',
    university_id: null,
    country: 'ALL',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 445,
    created_at: '2025-09-01',
  },
  {
    id: 'global-grammarly',
    title: 'Grammarly Premium Student',
    description: 'Writing assistant with student discount.',
    discount_percent: 40,
    discount_text: '40% off',
    category: 'software',
    brand: 'Grammarly',
    link: 'https://www.grammarly.com/edu',
    university_id: null,
    country: 'ALL',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 334,
    created_at: '2025-09-01',
  },
  {
    id: 'global-skillshare',
    title: 'Skillshare Student',
    description: 'Online learning platform with student discount.',
    discount_percent: 50,
    discount_text: '50% off annual',
    category: 'services',
    brand: 'Skillshare',
    link: 'https://www.skillshare.com/',
    university_id: null,
    country: 'ALL',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 234,
    created_at: '2025-09-01',
  },
  {
    id: 'global-linkedin',
    title: 'LinkedIn Learning',
    description: 'Often free through university library.',
    discount_percent: 100,
    discount_text: 'FREE via university',
    category: 'services',
    brand: 'LinkedIn',
    link: 'https://www.linkedin.com/learning/',
    university_id: null,
    country: 'ALL',
    expires_at: null,
    is_verified: true,
    submitted_by: null,
    upvotes: 289,
    created_at: '2025-09-01',
  },
];

// Combine all deals
export const MOCK_DEALS: Deal[] = [
  ...US_DEALS,
  ...UK_DEALS,
  ...CA_DEALS,
  ...GLOBAL_DEALS,
];

// Get mock deals by country (server-side safe, no localStorage)
export function getMockDeals(country?: string): Deal[] {
  if (!country || country === 'ALL') {
    return [...MOCK_DEALS];
  }
  return MOCK_DEALS.filter(d => d.country === country || d.country === 'ALL');
}

// Get all deals with country filtering
export function getDeals(category?: string, university?: string, country?: string): Deal[] {
  let deals = [...MOCK_DEALS];

  // Add user-submitted deals
  if (typeof window !== 'undefined') {
    try {
      const stored = localStorage.getItem(STORAGE_KEY_DEALS);
      if (stored) {
        const userDeals: Deal[] = JSON.parse(stored);
        deals = [...userDeals, ...deals];
      }
    } catch {
      // Ignore
    }
  }

  // Filter by country
  if (country && country !== 'ALL') {
    deals = deals.filter(d => d.country === country || d.country === 'ALL');
  }

  // Filter by category
  if (category && category !== 'all') {
    deals = deals.filter(d => d.category === category);
  }

  // Filter by university (show global + local)
  if (university) {
    deals = deals.filter(d => d.university_id === null || d.university_id === university);
  }

  // Sort by upvotes
  return deals.sort((a, b) => b.upvotes - a.upvotes);
}

// Get deals count by country
export function getDealsCountByCountry(country: string): number {
  return MOCK_DEALS.filter(d => d.country === country || d.country === 'ALL').length;
}

// Submit a new deal
export function submitDeal(deal: Omit<Deal, 'id' | 'upvotes' | 'created_at' | 'is_verified'>): Deal {
  const newDeal: Deal = {
    ...deal,
    id: `deal_${Date.now()}`,
    upvotes: 1,
    created_at: new Date().toISOString().split('T')[0],
    is_verified: false,
  };

  if (typeof window !== 'undefined') {
    try {
      const stored = localStorage.getItem(STORAGE_KEY_DEALS);
      const userDeals: Deal[] = stored ? JSON.parse(stored) : [];
      userDeals.unshift(newDeal);
      localStorage.setItem(STORAGE_KEY_DEALS, JSON.stringify(userDeals));
    } catch {
      // Ignore
    }
  }

  return newDeal;
}

// Upvote a deal
export function upvoteDeal(dealId: string): void {
  if (typeof window === 'undefined') return;

  try {
    // Check if already upvoted
    const stored = localStorage.getItem(STORAGE_KEY_UPVOTES);
    const upvotes: string[] = stored ? JSON.parse(stored) : [];

    if (upvotes.includes(dealId)) {
      // Remove upvote
      const updated = upvotes.filter(id => id !== dealId);
      localStorage.setItem(STORAGE_KEY_UPVOTES, JSON.stringify(updated));
    } else {
      // Add upvote
      upvotes.push(dealId);
      localStorage.setItem(STORAGE_KEY_UPVOTES, JSON.stringify(upvotes));
    }
  } catch {
    // Ignore
  }
}

// Check if user upvoted a deal
export function hasUpvoted(dealId: string): boolean {
  if (typeof window === 'undefined') return false;

  try {
    const stored = localStorage.getItem(STORAGE_KEY_UPVOTES);
    const upvotes: string[] = stored ? JSON.parse(stored) : [];
    return upvotes.includes(dealId);
  } catch {
    return false;
  }
}

// Get upvoted deals
export function getUpvotedDeals(): string[] {
  if (typeof window === 'undefined') return [];

  try {
    const stored = localStorage.getItem(STORAGE_KEY_UPVOTES);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}
