// ============================================================================
// ADDITIONAL COMMUNITY COLLEGES
// More community colleges with high international student enrollment
// ============================================================================

import { University } from './types';

// ============================================================================
// MORE CALIFORNIA COMMUNITY COLLEGES
// ============================================================================
export const MORE_CALIFORNIA_CC: University[] = [
  {
    id: 'san-mateo-college',
    name: 'College of San Mateo',
    short_name: 'CSM',
    city: 'San Mateo',
    state: 'CA',
    country: 'US',
    zip_code: '94402',
    latitude: 37.5350,
    longitude: -122.3407,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 850,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.collegeofsanmateo.edu',
    aliases: ['Bulldogs'],
  },
  {
    id: 'skyline-college',
    name: 'Skyline College',
    short_name: 'Skyline',
    city: 'San Bruno',
    state: 'CA',
    country: 'US',
    zip_code: '94066',
    latitude: 37.6298,
    longitude: -122.4681,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9500,
    international_students: 700,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFCC00',
    website: 'https://www.skylinecollege.edu',
    aliases: ['Trojans'],
  },
  {
    id: 'canada-college',
    name: 'Cañada College',
    short_name: 'Cañada',
    city: 'Redwood City',
    state: 'CA',
    country: 'US',
    zip_code: '94061',
    latitude: 37.4338,
    longitude: -122.2475,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 6500,
    international_students: 450,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.canadacollege.edu',
    aliases: ['Colts'],
  },
  {
    id: 'ohlone-college',
    name: 'Ohlone College',
    short_name: 'Ohlone',
    city: 'Fremont',
    state: 'CA',
    country: 'US',
    zip_code: '94539',
    latitude: 37.5389,
    longitude: -121.9286,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 1100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.ohlone.edu',
    aliases: ['Renegades'],
  },
  {
    id: 'mission-college',
    name: 'Mission College',
    short_name: 'Mission',
    city: 'Santa Clara',
    state: 'CA',
    country: 'US',
    zip_code: '95054',
    latitude: 37.3929,
    longitude: -121.9799,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 900,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://missioncollege.edu',
    aliases: ['Saints'],
  },
  {
    id: 'west-valley-college',
    name: 'West Valley College',
    short_name: 'West Valley',
    city: 'Saratoga',
    state: 'CA',
    country: 'US',
    zip_code: '95070',
    latitude: 37.2639,
    longitude: -122.0108,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 750,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.westvalley.edu',
    aliases: ['Vikings'],
  },
  {
    id: 'evergreen-valley',
    name: 'Evergreen Valley College',
    short_name: 'Evergreen Valley',
    city: 'San Jose',
    state: 'CA',
    country: 'US',
    zip_code: '95135',
    latitude: 37.3154,
    longitude: -121.7847,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9500,
    international_students: 680,
    is_public: true,
    primary_color: '#006400',
    secondary_color: '#FFD700',
    website: 'https://www.evc.edu',
    aliases: ['Hawks'],
  },
  {
    id: 'san-jose-city',
    name: 'San Jose City College',
    short_name: 'SJCC',
    city: 'San Jose',
    state: 'CA',
    country: 'US',
    zip_code: '95128',
    latitude: 37.3050,
    longitude: -121.9367,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 620,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#C8102E',
    website: 'https://www.sjcc.edu',
    aliases: ['Jaguars'],
  },
  {
    id: 'chabot-college',
    name: 'Chabot College',
    short_name: 'Chabot',
    city: 'Hayward',
    state: 'CA',
    country: 'US',
    zip_code: '94545',
    latitude: 37.6336,
    longitude: -122.0925,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 550,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.chabotcollege.edu',
    aliases: ['Gladiators'],
  },
  {
    id: 'las-positas',
    name: 'Las Positas College',
    short_name: 'Las Positas',
    city: 'Livermore',
    state: 'CA',
    country: 'US',
    zip_code: '94551',
    latitude: 37.6993,
    longitude: -121.8140,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 8500,
    international_students: 420,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.laspositascollege.edu',
    aliases: ['Hawks'],
  },
  {
    id: 'laney-college',
    name: 'Laney College',
    short_name: 'Laney',
    city: 'Oakland',
    state: 'CA',
    country: 'US',
    zip_code: '94607',
    latitude: 37.7958,
    longitude: -122.2636,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 1200,
    is_public: true,
    primary_color: '#006400',
    secondary_color: '#FFD700',
    website: 'https://www.laney.edu',
    aliases: ['Eagles'],
  },
  {
    id: 'merritt-college',
    name: 'Merritt College',
    short_name: 'Merritt',
    city: 'Oakland',
    state: 'CA',
    country: 'US',
    zip_code: '94619',
    latitude: 37.7892,
    longitude: -122.1792,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 5000,
    international_students: 280,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.merritt.edu',
    aliases: ['Thunderbirds'],
  },
  {
    id: 'college-of-alameda',
    name: 'College of Alameda',
    short_name: 'COA',
    city: 'Alameda',
    state: 'CA',
    country: 'US',
    zip_code: '94501',
    latitude: 37.7708,
    longitude: -122.2658,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 6000,
    international_students: 350,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.alameda.edu',
    aliases: ['Cougars'],
  },
  {
    id: 'berkeley-city-college',
    name: 'Berkeley City College',
    short_name: 'BCC',
    city: 'Berkeley',
    state: 'CA',
    country: 'US',
    zip_code: '94704',
    latitude: 37.8694,
    longitude: -122.2672,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 7500,
    international_students: 480,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.berkeleycitycollege.edu',
    aliases: [],
  },
  {
    id: 'contra-costa-college',
    name: 'Contra Costa College',
    short_name: 'CCC',
    city: 'San Pablo',
    state: 'CA',
    country: 'US',
    zip_code: '94806',
    latitude: 37.9672,
    longitude: -122.3483,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 8000,
    international_students: 380,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.contracosta.edu',
    aliases: ['Comets'],
  },
  {
    id: 'los-medanos',
    name: 'Los Medanos College',
    short_name: 'LMC',
    city: 'Pittsburg',
    state: 'CA',
    country: 'US',
    zip_code: '94565',
    latitude: 37.9897,
    longitude: -121.8703,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 8500,
    international_students: 290,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.losmedanos.edu',
    aliases: ['Mustangs'],
  },
  {
    id: 'solano-cc',
    name: 'Solano Community College',
    short_name: 'Solano',
    city: 'Fairfield',
    state: 'CA',
    country: 'US',
    zip_code: '94534',
    latitude: 38.2272,
    longitude: -122.0381,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 10500,
    international_students: 420,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.solano.edu',
    aliases: ['Falcons'],
  },
  {
    id: 'napa-valley-college',
    name: 'Napa Valley College',
    short_name: 'NVC',
    city: 'Napa',
    state: 'CA',
    country: 'US',
    zip_code: '94558',
    latitude: 38.2969,
    longitude: -122.3008,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 7000,
    international_students: 350,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#8B0000',
    website: 'https://www.napavalley.edu',
    aliases: ['Storm'],
  },
  {
    id: 'santa-rosa-jc',
    name: 'Santa Rosa Junior College',
    short_name: 'SRJC',
    city: 'Santa Rosa',
    state: 'CA',
    country: 'US',
    zip_code: '95401',
    latitude: 38.4400,
    longitude: -122.7142,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 1100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.santarosa.edu',
    aliases: ['Bear Cubs'],
  },
  {
    id: 'american-river-college',
    name: 'American River College',
    short_name: 'ARC',
    city: 'Sacramento',
    state: 'CA',
    country: 'US',
    zip_code: '95841',
    latitude: 38.6508,
    longitude: -121.3500,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 850,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.arc.losrios.edu',
    aliases: ['Beavers'],
  },
  {
    id: 'sierra-college',
    name: 'Sierra College',
    short_name: 'Sierra',
    city: 'Rocklin',
    state: 'CA',
    country: 'US',
    zip_code: '95677',
    latitude: 38.8031,
    longitude: -121.2444,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 420,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.sierracollege.edu',
    aliases: ['Wolverines'],
  },
  {
    id: 'modesto-jc',
    name: 'Modesto Junior College',
    short_name: 'MJC',
    city: 'Modesto',
    state: 'CA',
    country: 'US',
    zip_code: '95350',
    latitude: 37.6419,
    longitude: -120.9861,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 380,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.mjc.edu',
    aliases: ['Pirates'],
  },
  {
    id: 'fresno-city-college',
    name: 'Fresno City College',
    short_name: 'FCC',
    city: 'Fresno',
    state: 'CA',
    country: 'US',
    zip_code: '93741',
    latitude: 36.7583,
    longitude: -119.7889,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 520,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.fresnocitycollege.edu',
    aliases: ['Rams'],
  },
  {
    id: 'bakersfield-college',
    name: 'Bakersfield College',
    short_name: 'BC',
    city: 'Bakersfield',
    state: 'CA',
    country: 'US',
    zip_code: '93305',
    latitude: 35.3847,
    longitude: -119.0061,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 340,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.bakersfieldcollege.edu',
    aliases: ['Renegades'],
  },
  {
    id: 'college-of-the-canyons',
    name: 'College of the Canyons',
    short_name: 'COC',
    city: 'Santa Clarita',
    state: 'CA',
    country: 'US',
    zip_code: '91355',
    latitude: 34.4050,
    longitude: -118.5553,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 650,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.canyons.edu',
    aliases: ['Cougars'],
  },
  {
    id: 'chaffey-college',
    name: 'Chaffey College',
    short_name: 'Chaffey',
    city: 'Rancho Cucamonga',
    state: 'CA',
    country: 'US',
    zip_code: '91737',
    latitude: 34.0956,
    longitude: -117.5789,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 720,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.chaffey.edu',
    aliases: ['Panthers'],
  },
  {
    id: 'rio-hondo',
    name: 'Rio Hondo College',
    short_name: 'Rio Hondo',
    city: 'Whittier',
    state: 'CA',
    country: 'US',
    zip_code: '90601',
    latitude: 33.9889,
    longitude: -118.0317,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18500,
    international_students: 480,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.riohondo.edu',
    aliases: ['Roadrunners'],
  },
  {
    id: 'cerritos-college',
    name: 'Cerritos College',
    short_name: 'Cerritos',
    city: 'Norwalk',
    state: 'CA',
    country: 'US',
    zip_code: '90650',
    latitude: 33.9022,
    longitude: -118.0872,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 580,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.cerritos.edu',
    aliases: ['Falcons'],
  },
  {
    id: 'compton-college',
    name: 'Compton College',
    short_name: 'Compton',
    city: 'Compton',
    state: 'CA',
    country: 'US',
    zip_code: '90221',
    latitude: 33.8817,
    longitude: -118.2117,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 7000,
    international_students: 180,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.compton.edu',
    aliases: ['Tartars'],
  },
  {
    id: 'palomar-college',
    name: 'Palomar College',
    short_name: 'Palomar',
    city: 'San Marcos',
    state: 'CA',
    country: 'US',
    zip_code: '92069',
    latitude: 33.1036,
    longitude: -117.1533,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 23000,
    international_students: 520,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.palomar.edu',
    aliases: ['Comets'],
  },
  {
    id: 'miracosta-college',
    name: 'MiraCosta College',
    short_name: 'MiraCosta',
    city: 'Oceanside',
    state: 'CA',
    country: 'US',
    zip_code: '92056',
    latitude: 33.1944,
    longitude: -117.3192,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 420,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006400',
    website: 'https://www.miracosta.edu',
    aliases: ['Spartans'],
  },
  {
    id: 'southwestern-college',
    name: 'Southwestern College',
    short_name: 'Southwestern',
    city: 'Chula Vista',
    state: 'CA',
    country: 'US',
    zip_code: '91910',
    latitude: 32.6489,
    longitude: -117.0136,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 380,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.swccd.edu',
    aliases: ['Jaguars'],
  },
];

// ============================================================================
// MORE COMMUNITY COLLEGES (OTHER STATES)
// ============================================================================
export const MORE_OTHER_CC: University[] = [
  // NEW JERSEY
  {
    id: 'bergen-cc',
    name: 'Bergen Community College',
    short_name: 'Bergen',
    city: 'Paramus',
    state: 'NJ',
    country: 'US',
    zip_code: '07652',
    latitude: 40.9548,
    longitude: -74.0703,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 1100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.bergen.edu',
    aliases: ['Bulldogs'],
  },
  {
    id: 'county-college-morris',
    name: 'County College of Morris',
    short_name: 'CCM',
    city: 'Randolph',
    state: 'NJ',
    country: 'US',
    zip_code: '07869',
    latitude: 40.8650,
    longitude: -74.5725,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 7500,
    international_students: 450,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.ccm.edu',
    aliases: ['Titans'],
  },
  {
    id: 'middlesex-college-nj',
    name: 'Middlesex College',
    short_name: 'Middlesex',
    city: 'Edison',
    state: 'NJ',
    country: 'US',
    zip_code: '08818',
    latitude: 40.5197,
    longitude: -74.3625,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 780,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#C8102E',
    website: 'https://www.middlesexcc.edu',
    aliases: ['Blue Colts'],
  },
  {
    id: 'essex-cc',
    name: 'Essex County College',
    short_name: 'Essex',
    city: 'Newark',
    state: 'NJ',
    country: 'US',
    zip_code: '07102',
    latitude: 40.7426,
    longitude: -74.1839,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 620,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.essex.edu',
    aliases: ['Wolverines'],
  },
  // MARYLAND
  {
    id: 'montgomery-college',
    name: 'Montgomery College',
    short_name: 'MC',
    city: 'Rockville',
    state: 'MD',
    country: 'US',
    zip_code: '20850',
    latitude: 39.0850,
    longitude: -77.1528,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 2200,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.montgomerycollege.edu',
    aliases: ['Raptors'],
  },
  {
    id: 'prince-georges-cc',
    name: "Prince George's Community College",
    short_name: 'PGCC',
    city: 'Largo',
    state: 'MD',
    country: 'US',
    zip_code: '20774',
    latitude: 38.8833,
    longitude: -76.8656,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 12500,
    international_students: 950,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.pgcc.edu',
    aliases: ['Owls'],
  },
  {
    id: 'anne-arundel-cc',
    name: 'Anne Arundel Community College',
    short_name: 'AACC',
    city: 'Arnold',
    state: 'MD',
    country: 'US',
    zip_code: '21012',
    latitude: 39.0308,
    longitude: -76.5072,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 650,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.aacc.edu',
    aliases: ['Riverhawks'],
  },
  // PENNSYLVANIA
  {
    id: 'ccp',
    name: 'Community College of Philadelphia',
    short_name: 'CCP',
    city: 'Philadelphia',
    state: 'PA',
    country: 'US',
    zip_code: '19130',
    latitude: 39.9656,
    longitude: -75.1681,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 1200,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.ccp.edu',
    aliases: ['Colonials'],
  },
  {
    id: 'ccac',
    name: 'Community College of Allegheny County',
    short_name: 'CCAC',
    city: 'Pittsburgh',
    state: 'PA',
    country: 'US',
    zip_code: '15233',
    latitude: 40.4589,
    longitude: -79.9814,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 850,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.ccac.edu',
    aliases: ['Panthers'],
  },
  // OHIO
  {
    id: 'cuyahoga-cc',
    name: 'Cuyahoga Community College',
    short_name: 'Tri-C',
    city: 'Cleveland',
    state: 'OH',
    country: 'US',
    zip_code: '44115',
    latitude: 41.4993,
    longitude: -81.6944,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 1100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.tri-c.edu',
    aliases: ['Triceratops'],
  },
  {
    id: 'columbus-state-cc',
    name: 'Columbus State Community College',
    short_name: 'Columbus State',
    city: 'Columbus',
    state: 'OH',
    country: 'US',
    zip_code: '43215',
    latitude: 39.9606,
    longitude: -82.9994,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 920,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#C8102E',
    website: 'https://www.cscc.edu',
    aliases: ['Cougars'],
  },
  {
    id: 'sinclair-cc',
    name: 'Sinclair Community College',
    short_name: 'Sinclair',
    city: 'Dayton',
    state: 'OH',
    country: 'US',
    zip_code: '45402',
    latitude: 39.7589,
    longitude: -84.1939,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 580,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#C8102E',
    website: 'https://www.sinclair.edu',
    aliases: ['Tartan Pride'],
  },
  // MICHIGAN
  {
    id: 'oakland-cc',
    name: 'Oakland Community College',
    short_name: 'OCC',
    city: 'Bloomfield Hills',
    state: 'MI',
    country: 'US',
    zip_code: '48304',
    latitude: 42.5775,
    longitude: -83.2333,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 750,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.oaklandcc.edu',
    aliases: ['Raiders'],
  },
  {
    id: 'henry-ford-college',
    name: 'Henry Ford College',
    short_name: 'HFC',
    city: 'Dearborn',
    state: 'MI',
    country: 'US',
    zip_code: '48128',
    latitude: 42.3186,
    longitude: -83.2431,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 850,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.hfcc.edu',
    aliases: ['Hawks'],
  },
  {
    id: 'macomb-cc',
    name: 'Macomb Community College',
    short_name: 'Macomb',
    city: 'Warren',
    state: 'MI',
    country: 'US',
    zip_code: '48088',
    latitude: 42.5089,
    longitude: -82.9381,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 680,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.macomb.edu',
    aliases: ['Monarchs'],
  },
  {
    id: 'washtenaw-cc',
    name: 'Washtenaw Community College',
    short_name: 'WCC',
    city: 'Ann Arbor',
    state: 'MI',
    country: 'US',
    zip_code: '48105',
    latitude: 42.2706,
    longitude: -83.7119,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 520,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006400',
    website: 'https://www.wccnet.edu',
    aliases: [],
  },
  // GEORGIA
  {
    id: 'georgia-perimeter',
    name: 'Georgia State University Perimeter College',
    short_name: 'Perimeter',
    city: 'Decatur',
    state: 'GA',
    country: 'US',
    zip_code: '30034',
    latitude: 33.7572,
    longitude: -84.2231,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 1100,
    is_public: true,
    primary_color: '#0039A6',
    secondary_color: '#CC0000',
    website: 'https://perimeter.gsu.edu',
    aliases: ['Jaguars'],
  },
  {
    id: 'atlanta-tech',
    name: 'Atlanta Technical College',
    short_name: 'Atlanta Tech',
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    zip_code: '30310',
    latitude: 33.7394,
    longitude: -84.4233,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 4500,
    international_students: 280,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.atlantatech.edu',
    aliases: [],
  },
  // OREGON
  {
    id: 'portland-cc',
    name: 'Portland Community College',
    short_name: 'PCC',
    city: 'Portland',
    state: 'OR',
    country: 'US',
    zip_code: '97219',
    latitude: 45.4367,
    longitude: -122.7058,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 28000,
    international_students: 1600,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.pcc.edu',
    aliases: ['Panthers'],
  },
  {
    id: 'lane-cc',
    name: 'Lane Community College',
    short_name: 'LCC',
    city: 'Eugene',
    state: 'OR',
    country: 'US',
    zip_code: '97405',
    latitude: 43.9856,
    longitude: -123.0506,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 650,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006400',
    website: 'https://www.lanecc.edu',
    aliases: ['Titans'],
  },
  // MINNESOTA
  {
    id: 'hennepin-tech',
    name: 'Hennepin Technical College',
    short_name: 'Hennepin Tech',
    city: 'Brooklyn Park',
    state: 'MN',
    country: 'US',
    zip_code: '55445',
    latitude: 45.1119,
    longitude: -93.3450,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 7500,
    international_students: 420,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.hennepintech.edu',
    aliases: [],
  },
  {
    id: 'minneapolis-cc',
    name: 'Minneapolis Community and Technical College',
    short_name: 'MCTC',
    city: 'Minneapolis',
    state: 'MN',
    country: 'US',
    zip_code: '55403',
    latitude: 44.9687,
    longitude: -93.2756,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9500,
    international_students: 650,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.minneapolis.edu',
    aliases: [],
  },
  // CONNECTICUT
  {
    id: 'housatonic-cc',
    name: 'Housatonic Community College',
    short_name: 'Housatonic',
    city: 'Bridgeport',
    state: 'CT',
    country: 'US',
    zip_code: '06604',
    latitude: 41.1797,
    longitude: -73.1894,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 5500,
    international_students: 380,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.housatonic.edu',
    aliases: ['Hawks'],
  },
  {
    id: 'norwalk-cc',
    name: 'Norwalk Community College',
    short_name: 'NCC',
    city: 'Norwalk',
    state: 'CT',
    country: 'US',
    zip_code: '06854',
    latitude: 41.1025,
    longitude: -73.4203,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 6000,
    international_students: 450,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006400',
    website: 'https://www.norwalk.edu',
    aliases: ['Panthers'],
  },
  // COLORADO
  {
    id: 'front-range-cc',
    name: 'Front Range Community College',
    short_name: 'FRCC',
    city: 'Westminster',
    state: 'CO',
    country: 'US',
    zip_code: '80031',
    latitude: 39.8778,
    longitude: -105.0225,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 580,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.frontrange.edu',
    aliases: [],
  },
  {
    id: 'ccd',
    name: 'Community College of Denver',
    short_name: 'CCD',
    city: 'Denver',
    state: 'CO',
    country: 'US',
    zip_code: '80204',
    latitude: 39.7450,
    longitude: -105.0056,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 520,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.ccd.edu',
    aliases: [],
  },
  // NEVADA
  {
    id: 'csn',
    name: 'College of Southern Nevada',
    short_name: 'CSN',
    city: 'Las Vegas',
    state: 'NV',
    country: 'US',
    zip_code: '89146',
    latitude: 36.1636,
    longitude: -115.2161,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 1800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.csn.edu',
    aliases: ['Coyotes'],
  },
  {
    id: 'tmcc',
    name: 'Truckee Meadows Community College',
    short_name: 'TMCC',
    city: 'Reno',
    state: 'NV',
    country: 'US',
    zip_code: '89512',
    latitude: 39.5533,
    longitude: -119.8150,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 580,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.tmcc.edu',
    aliases: ['Lizards'],
  },
  // HAWAII
  {
    id: 'kcc-hawaii',
    name: "Kapi'olani Community College",
    short_name: 'KCC',
    city: 'Honolulu',
    state: 'HI',
    country: 'US',
    zip_code: '96816',
    latitude: 21.2711,
    longitude: -157.8017,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 7500,
    international_students: 950,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006400',
    website: 'https://www.kapiolani.hawaii.edu',
    aliases: [],
  },
];

// ============================================================================
// COMBINE ALL ADDITIONAL COMMUNITY COLLEGES
// ============================================================================
export const ALL_ADDITIONAL_CC: University[] = [
  ...MORE_CALIFORNIA_CC,
  ...MORE_OTHER_CC,
];

export default ALL_ADDITIONAL_CC;
