// ============================================================================
// ADDITIONAL STATE UNIVERSITY SYSTEMS
// Florida, Georgia, North Carolina, Virginia, Massachusetts, and more
// ============================================================================

import { University } from './types';

// ============================================================================
// FLORIDA STATE UNIVERSITY SYSTEM (12 universities)
// ============================================================================

export const FLORIDA_SUS: University[] = [
  {
    id: 'uf',
    name: 'University of Florida',
    short_name: 'UF',
    system_name: 'State University System of Florida',
    city: 'Gainesville',
    state: 'FL',
    zip_code: '32611',
    latitude: 29.6436,
    longitude: -82.3549,
    type: 'university',
    campus_type: 'main',
    enrollment: 56567,
    international_students: 6200,
    is_public: true,
    primary_color: '#0021A5',
    secondary_color: '#FA4616',
    website: 'https://www.ufl.edu',
    aliases: ['Gators', 'Florida']
  },
  {
    id: 'fsu',
    name: 'Florida State University',
    short_name: 'FSU',
    system_name: 'State University System of Florida',
    city: 'Tallahassee',
    state: 'FL',
    zip_code: '32306',
    latitude: 30.4419,
    longitude: -84.2985,
    type: 'university',
    campus_type: 'main',
    enrollment: 44161,
    international_students: 2800,
    is_public: true,
    primary_color: '#782F40',
    secondary_color: '#CEB888',
    website: 'https://www.fsu.edu',
    aliases: ['Seminoles', 'Florida State']
  },
  {
    id: 'usf',
    name: 'University of South Florida',
    short_name: 'USF',
    system_name: 'State University System of Florida',
    city: 'Tampa',
    state: 'FL',
    zip_code: '33620',
    latitude: 28.0587,
    longitude: -82.4139,
    type: 'university',
    campus_type: 'main',
    enrollment: 50577,
    international_students: 4200,
    is_public: true,
    primary_color: '#006747',
    secondary_color: '#CFC493',
    website: 'https://www.usf.edu',
    aliases: ['Bulls', 'South Florida']
  },
  {
    id: 'ucf',
    name: 'University of Central Florida',
    short_name: 'UCF',
    system_name: 'State University System of Florida',
    city: 'Orlando',
    state: 'FL',
    zip_code: '32816',
    latitude: 28.6024,
    longitude: -81.2001,
    type: 'university',
    campus_type: 'main',
    enrollment: 71948,
    international_students: 4500,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#BA9B37',
    website: 'https://www.ucf.edu',
    aliases: ['Knights', 'Central Florida']
  },
  {
    id: 'fiu',
    name: 'Florida International University',
    short_name: 'FIU',
    system_name: 'State University System of Florida',
    city: 'Miami',
    state: 'FL',
    zip_code: '33199',
    latitude: 25.7559,
    longitude: -80.3746,
    type: 'university',
    campus_type: 'main',
    enrollment: 58787,
    international_students: 5100,
    is_public: true,
    primary_color: '#081E3F',
    secondary_color: '#B6862C',
    website: 'https://www.fiu.edu',
    aliases: ['Panthers', 'Florida International']
  },
  {
    id: 'fau',
    name: 'Florida Atlantic University',
    short_name: 'FAU',
    system_name: 'State University System of Florida',
    city: 'Boca Raton',
    state: 'FL',
    zip_code: '33431',
    latitude: 26.3729,
    longitude: -80.1017,
    type: 'university',
    campus_type: 'main',
    enrollment: 30808,
    international_students: 1800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.fau.edu',
    aliases: ['Owls', 'Florida Atlantic']
  },
  {
    id: 'uf-jacksonville',
    name: 'University of North Florida',
    short_name: 'UNF',
    system_name: 'State University System of Florida',
    city: 'Jacksonville',
    state: 'FL',
    zip_code: '32224',
    latitude: 30.2693,
    longitude: -81.5090,
    type: 'university',
    campus_type: 'main',
    enrollment: 17003,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#A8A8A8',
    website: 'https://www.unf.edu',
    aliases: ['Ospreys', 'North Florida']
  },
  {
    id: 'fgcu',
    name: 'Florida Gulf Coast University',
    short_name: 'FGCU',
    system_name: 'State University System of Florida',
    city: 'Fort Myers',
    state: 'FL',
    zip_code: '33965',
    latitude: 26.4651,
    longitude: -81.7701,
    type: 'university',
    campus_type: 'main',
    enrollment: 15105,
    is_public: true,
    primary_color: '#002D62',
    secondary_color: '#007749',
    website: 'https://www.fgcu.edu',
    aliases: ['Eagles', 'Gulf Coast']
  },
  {
    id: 'uwf',
    name: 'University of West Florida',
    short_name: 'UWF',
    system_name: 'State University System of Florida',
    city: 'Pensacola',
    state: 'FL',
    zip_code: '32514',
    latitude: 30.5483,
    longitude: -87.2179,
    type: 'university',
    campus_type: 'main',
    enrollment: 12692,
    is_public: true,
    primary_color: '#003893',
    secondary_color: '#00A651',
    website: 'https://www.uwf.edu',
    aliases: ['Argonauts', 'West Florida']
  },
  {
    id: 'famu',
    name: 'Florida A&M University',
    short_name: 'FAMU',
    system_name: 'State University System of Florida',
    city: 'Tallahassee',
    state: 'FL',
    zip_code: '32307',
    latitude: 30.4255,
    longitude: -84.2840,
    type: 'university',
    campus_type: 'main',
    enrollment: 9614,
    is_public: true,
    primary_color: '#FF6600',
    secondary_color: '#006633',
    website: 'https://www.famu.edu',
    aliases: ['Rattlers', 'Florida A&M']
  },
  {
    id: 'fpu',
    name: 'Florida Polytechnic University',
    short_name: 'Florida Poly',
    system_name: 'State University System of Florida',
    city: 'Lakeland',
    state: 'FL',
    zip_code: '33805',
    latitude: 28.1495,
    longitude: -81.8512,
    type: 'university',
    campus_type: 'main',
    enrollment: 1503,
    is_public: true,
    primary_color: '#660099',
    secondary_color: '#A8A8A8',
    website: 'https://floridapoly.edu',
    aliases: ['Phoenix', 'Florida Polytechnic']
  },
  {
    id: 'ncf',
    name: 'New College of Florida',
    short_name: 'New College',
    system_name: 'State University System of Florida',
    city: 'Sarasota',
    state: 'FL',
    zip_code: '34243',
    latitude: 27.3839,
    longitude: -82.5530,
    type: 'university',
    campus_type: 'main',
    enrollment: 706,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.ncf.edu'
  }
];

// ============================================================================
// UNIVERSITY SYSTEM OF GEORGIA (26 institutions - major ones)
// ============================================================================

export const GEORGIA_USG: University[] = [
  {
    id: 'uga',
    name: 'University of Georgia',
    short_name: 'UGA',
    system_name: 'University System of Georgia',
    city: 'Athens',
    state: 'GA',
    zip_code: '30602',
    latitude: 33.9480,
    longitude: -83.3773,
    type: 'university',
    campus_type: 'main',
    enrollment: 40118,
    international_students: 2400,
    is_public: true,
    primary_color: '#BA0C2F',
    secondary_color: '#000000',
    website: 'https://www.uga.edu',
    aliases: ['Georgia', 'Bulldogs']
  },
  {
    id: 'gatech',
    name: 'Georgia Institute of Technology',
    short_name: 'Georgia Tech',
    system_name: 'University System of Georgia',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30332',
    latitude: 33.7756,
    longitude: -84.3963,
    type: 'university',
    campus_type: 'main',
    enrollment: 44000,
    international_students: 9800,
    is_public: true,
    primary_color: '#B3A369',
    secondary_color: '#003057',
    website: 'https://www.gatech.edu',
    aliases: ['GT', 'Yellow Jackets', 'Tech']
  },
  {
    id: 'gsu',
    name: 'Georgia State University',
    short_name: 'Georgia State',
    system_name: 'University System of Georgia',
    city: 'Atlanta',
    state: 'GA',
    zip_code: '30303',
    latitude: 33.7529,
    longitude: -84.3853,
    type: 'university',
    campus_type: 'main',
    enrollment: 54000,
    international_students: 3200,
    is_public: true,
    primary_color: '#0039A6',
    secondary_color: '#CC0000',
    website: 'https://www.gsu.edu',
    aliases: ['GSU', 'Panthers']
  },
  {
    id: 'kennesaw',
    name: 'Kennesaw State University',
    short_name: 'Kennesaw State',
    system_name: 'University System of Georgia',
    city: 'Kennesaw',
    state: 'GA',
    zip_code: '30144',
    latitude: 34.0379,
    longitude: -84.5809,
    type: 'university',
    campus_type: 'main',
    enrollment: 43000,
    international_students: 2100,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFB81C',
    website: 'https://www.kennesaw.edu',
    aliases: ['KSU', 'Owls']
  },
  {
    id: 'georgia-southern',
    name: 'Georgia Southern University',
    short_name: 'Georgia Southern',
    system_name: 'University System of Georgia',
    city: 'Statesboro',
    state: 'GA',
    zip_code: '30458',
    latitude: 32.4233,
    longitude: -81.7852,
    type: 'university',
    campus_type: 'main',
    enrollment: 26000,
    is_public: true,
    primary_color: '#041E42',
    secondary_color: '#FFFFFF',
    website: 'https://www.georgiasouthern.edu',
    aliases: ['Eagles']
  },
  {
    id: 'valdosta-state',
    name: 'Valdosta State University',
    short_name: 'Valdosta State',
    system_name: 'University System of Georgia',
    city: 'Valdosta',
    state: 'GA',
    zip_code: '31698',
    latitude: 30.8466,
    longitude: -83.2537,
    type: 'university',
    campus_type: 'main',
    enrollment: 11000,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#000000',
    website: 'https://www.valdosta.edu',
    aliases: ['VSU', 'Blazers']
  },
  {
    id: 'augusta',
    name: 'Augusta University',
    short_name: 'Augusta',
    system_name: 'University System of Georgia',
    city: 'Augusta',
    state: 'GA',
    zip_code: '30912',
    latitude: 33.4732,
    longitude: -82.0225,
    type: 'university',
    campus_type: 'main',
    enrollment: 9700,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFFFFF',
    website: 'https://www.augusta.edu',
    aliases: ['AU', 'Jaguars']
  },
  {
    id: 'uwg',
    name: 'University of West Georgia',
    short_name: 'West Georgia',
    system_name: 'University System of Georgia',
    city: 'Carrollton',
    state: 'GA',
    zip_code: '30118',
    latitude: 33.5851,
    longitude: -85.0663,
    type: 'university',
    campus_type: 'main',
    enrollment: 13000,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#003087',
    website: 'https://www.westga.edu',
    aliases: ['UWG', 'Wolves']
  }
];

// ============================================================================
// UNIVERSITY OF NORTH CAROLINA SYSTEM (17 institutions)
// ============================================================================

export const UNC_SYSTEM: University[] = [
  {
    id: 'unc-chapel-hill',
    name: 'University of North Carolina at Chapel Hill',
    short_name: 'UNC Chapel Hill',
    system_name: 'University of North Carolina',
    city: 'Chapel Hill',
    state: 'NC',
    zip_code: '27599',
    latitude: 35.9049,
    longitude: -79.0469,
    type: 'university',
    campus_type: 'main',
    enrollment: 31641,
    international_students: 2800,
    is_public: true,
    primary_color: '#7BAFD4',
    secondary_color: '#13294B',
    website: 'https://www.unc.edu',
    aliases: ['UNC', 'Carolina', 'Tar Heels']
  },
  {
    id: 'nc-state',
    name: 'North Carolina State University',
    short_name: 'NC State',
    system_name: 'University of North Carolina',
    city: 'Raleigh',
    state: 'NC',
    zip_code: '27695',
    latitude: 35.7847,
    longitude: -78.6821,
    type: 'university',
    campus_type: 'main',
    enrollment: 36304,
    international_students: 3600,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.ncsu.edu',
    aliases: ['NCSU', 'Wolfpack', 'State']
  },
  {
    id: 'unc-charlotte',
    name: 'University of North Carolina at Charlotte',
    short_name: 'UNC Charlotte',
    system_name: 'University of North Carolina',
    city: 'Charlotte',
    state: 'NC',
    zip_code: '28223',
    latitude: 35.3074,
    longitude: -80.7339,
    type: 'university',
    campus_type: 'main',
    enrollment: 30146,
    international_students: 1400,
    is_public: true,
    primary_color: '#005035',
    secondary_color: '#A49665',
    website: 'https://www.charlotte.edu',
    aliases: ['UNCC', '49ers']
  },
  {
    id: 'unc-greensboro',
    name: 'University of North Carolina at Greensboro',
    short_name: 'UNCG',
    system_name: 'University of North Carolina',
    city: 'Greensboro',
    state: 'NC',
    zip_code: '27412',
    latitude: 36.0688,
    longitude: -79.8102,
    type: 'university',
    campus_type: 'main',
    enrollment: 19647,
    is_public: true,
    primary_color: '#0F2044',
    secondary_color: '#FFD200',
    website: 'https://www.uncg.edu',
    aliases: ['Spartans']
  },
  {
    id: 'east-carolina',
    name: 'East Carolina University',
    short_name: 'ECU',
    system_name: 'University of North Carolina',
    city: 'Greenville',
    state: 'NC',
    zip_code: '27858',
    latitude: 35.6066,
    longitude: -77.3658,
    type: 'university',
    campus_type: 'main',
    enrollment: 28798,
    is_public: true,
    primary_color: '#592A8A',
    secondary_color: '#FFC425',
    website: 'https://www.ecu.edu',
    aliases: ['East Carolina', 'Pirates']
  },
  {
    id: 'unc-wilmington',
    name: 'University of North Carolina Wilmington',
    short_name: 'UNCW',
    system_name: 'University of North Carolina',
    city: 'Wilmington',
    state: 'NC',
    zip_code: '28403',
    latitude: 34.2271,
    longitude: -77.8725,
    type: 'university',
    campus_type: 'main',
    enrollment: 17915,
    is_public: true,
    primary_color: '#006666',
    secondary_color: '#FFD200',
    website: 'https://www.uncw.edu',
    aliases: ['Seahawks']
  },
  {
    id: 'appalachian-state',
    name: 'Appalachian State University',
    short_name: 'App State',
    system_name: 'University of North Carolina',
    city: 'Boone',
    state: 'NC',
    zip_code: '28608',
    latitude: 36.2138,
    longitude: -81.6758,
    type: 'university',
    campus_type: 'main',
    enrollment: 20641,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFCC00',
    website: 'https://www.appstate.edu',
    aliases: ['Appalachian', 'Mountaineers']
  },
  {
    id: 'unc-asheville',
    name: 'University of North Carolina at Asheville',
    short_name: 'UNC Asheville',
    system_name: 'University of North Carolina',
    city: 'Asheville',
    state: 'NC',
    zip_code: '28804',
    latitude: 35.6159,
    longitude: -82.5688,
    type: 'university',
    campus_type: 'main',
    enrollment: 3200,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.unca.edu',
    aliases: ['UNCA', 'Bulldogs']
  },
  {
    id: 'nc-at',
    name: 'North Carolina A&T State University',
    short_name: 'NC A&T',
    system_name: 'University of North Carolina',
    city: 'Greensboro',
    state: 'NC',
    zip_code: '27411',
    latitude: 36.0761,
    longitude: -79.7731,
    type: 'university',
    campus_type: 'main',
    enrollment: 13323,
    is_public: true,
    primary_color: '#004684',
    secondary_color: '#FFB81C',
    website: 'https://www.ncat.edu',
    aliases: ['Aggies']
  },
  {
    id: 'nc-central',
    name: 'North Carolina Central University',
    short_name: 'NCCU',
    system_name: 'University of North Carolina',
    city: 'Durham',
    state: 'NC',
    zip_code: '27707',
    latitude: 35.9744,
    longitude: -78.8984,
    type: 'university',
    campus_type: 'main',
    enrollment: 8000,
    is_public: true,
    primary_color: '#862633',
    secondary_color: '#8F8E8C',
    website: 'https://www.nccu.edu',
    aliases: ['Eagles']
  },
  {
    id: 'western-carolina',
    name: 'Western Carolina University',
    short_name: 'Western Carolina',
    system_name: 'University of North Carolina',
    city: 'Cullowhee',
    state: 'NC',
    zip_code: '28723',
    latitude: 35.3093,
    longitude: -83.1879,
    type: 'university',
    campus_type: 'main',
    enrollment: 12000,
    is_public: true,
    primary_color: '#592A8A',
    secondary_color: '#FFC425',
    website: 'https://www.wcu.edu',
    aliases: ['WCU', 'Catamounts']
  },
  {
    id: 'winston-salem-state',
    name: 'Winston-Salem State University',
    short_name: 'WSSU',
    system_name: 'University of North Carolina',
    city: 'Winston-Salem',
    state: 'NC',
    zip_code: '27110',
    latitude: 36.0989,
    longitude: -80.2181,
    type: 'university',
    campus_type: 'main',
    enrollment: 5000,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.wssu.edu',
    aliases: ['Rams']
  },
  {
    id: 'fayetteville-state',
    name: 'Fayetteville State University',
    short_name: 'Fayetteville State',
    system_name: 'University of North Carolina',
    city: 'Fayetteville',
    state: 'NC',
    zip_code: '28301',
    latitude: 35.0657,
    longitude: -78.9068,
    type: 'university',
    campus_type: 'main',
    enrollment: 6500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.uncfsu.edu',
    aliases: ['FSU', 'Broncos']
  },
  {
    id: 'unc-pembroke',
    name: 'University of North Carolina at Pembroke',
    short_name: 'UNC Pembroke',
    system_name: 'University of North Carolina',
    city: 'Pembroke',
    state: 'NC',
    zip_code: '28372',
    latitude: 34.6816,
    longitude: -79.1870,
    type: 'university',
    campus_type: 'main',
    enrollment: 8200,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFD700',
    website: 'https://www.uncp.edu',
    aliases: ['UNCP', 'Braves']
  },
  {
    id: 'elizabeth-city-state',
    name: 'Elizabeth City State University',
    short_name: 'ECSU',
    system_name: 'University of North Carolina',
    city: 'Elizabeth City',
    state: 'NC',
    zip_code: '27909',
    latitude: 36.3026,
    longitude: -76.2297,
    type: 'university',
    campus_type: 'main',
    enrollment: 1600,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.ecsu.edu',
    aliases: ['Vikings']
  },
  {
    id: 'unc-school-arts',
    name: 'University of North Carolina School of the Arts',
    short_name: 'UNCSA',
    system_name: 'University of North Carolina',
    city: 'Winston-Salem',
    state: 'NC',
    zip_code: '27127',
    latitude: 36.0867,
    longitude: -80.2846,
    type: 'university',
    campus_type: 'main',
    enrollment: 1200,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFD700',
    website: 'https://www.uncsa.edu',
    aliases: ['School of the Arts']
  }
];

// ============================================================================
// VIRGINIA PUBLIC UNIVERSITIES
// ============================================================================

export const VIRGINIA_UNIVERSITIES: University[] = [
  {
    id: 'uva',
    name: 'University of Virginia',
    short_name: 'UVA',
    city: 'Charlottesville',
    state: 'VA',
    zip_code: '22904',
    latitude: 38.0336,
    longitude: -78.5080,
    type: 'university',
    campus_type: 'main',
    enrollment: 25018,
    international_students: 2800,
    is_public: true,
    primary_color: '#232D4B',
    secondary_color: '#F84C1E',
    website: 'https://www.virginia.edu',
    aliases: ['Virginia', 'Cavaliers', 'Wahoos']
  },
  {
    id: 'virginia-tech',
    name: 'Virginia Polytechnic Institute and State University',
    short_name: 'Virginia Tech',
    city: 'Blacksburg',
    state: 'VA',
    zip_code: '24061',
    latitude: 37.2296,
    longitude: -80.4139,
    type: 'university',
    campus_type: 'main',
    enrollment: 36383,
    international_students: 4200,
    is_public: true,
    primary_color: '#630031',
    secondary_color: '#CF4420',
    website: 'https://www.vt.edu',
    aliases: ['VT', 'Hokies']
  },
  {
    id: 'vcu',
    name: 'Virginia Commonwealth University',
    short_name: 'VCU',
    city: 'Richmond',
    state: 'VA',
    zip_code: '23284',
    latitude: 37.5488,
    longitude: -77.4530,
    type: 'university',
    campus_type: 'main',
    enrollment: 28772,
    international_students: 2100,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFB300',
    website: 'https://www.vcu.edu',
    aliases: ['Rams']
  },
  {
    id: 'gmu',
    name: 'George Mason University',
    short_name: 'Mason',
    city: 'Fairfax',
    state: 'VA',
    zip_code: '22030',
    latitude: 38.8316,
    longitude: -77.3089,
    type: 'university',
    campus_type: 'main',
    enrollment: 37677,
    international_students: 5200,
    is_public: true,
    primary_color: '#006633',
    secondary_color: '#FFCC33',
    website: 'https://www.gmu.edu',
    aliases: ['GMU', 'George Mason', 'Patriots']
  },
  {
    id: 'jmu',
    name: 'James Madison University',
    short_name: 'JMU',
    city: 'Harrisonburg',
    state: 'VA',
    zip_code: '22807',
    latitude: 38.4393,
    longitude: -78.8691,
    type: 'university',
    campus_type: 'main',
    enrollment: 22157,
    is_public: true,
    primary_color: '#450084',
    secondary_color: '#CBB677',
    website: 'https://www.jmu.edu',
    aliases: ['James Madison', 'Dukes']
  },
  {
    id: 'odu',
    name: 'Old Dominion University',
    short_name: 'ODU',
    city: 'Norfolk',
    state: 'VA',
    zip_code: '23529',
    latitude: 36.8862,
    longitude: -76.3064,
    type: 'university',
    campus_type: 'main',
    enrollment: 24176,
    international_students: 1600,
    is_public: true,
    primary_color: '#003057',
    secondary_color: '#7C878E',
    website: 'https://www.odu.edu',
    aliases: ['Old Dominion', 'Monarchs']
  },
  {
    id: 'wm',
    name: 'William & Mary',
    short_name: 'W&M',
    city: 'Williamsburg',
    state: 'VA',
    zip_code: '23187',
    latitude: 37.2707,
    longitude: -76.7075,
    type: 'university',
    campus_type: 'main',
    enrollment: 9519,
    international_students: 800,
    is_public: true,
    primary_color: '#115740',
    secondary_color: '#B9975B',
    website: 'https://www.wm.edu',
    aliases: ['William and Mary', 'Tribe']
  },
  {
    id: 'vsu',
    name: 'Virginia State University',
    short_name: 'VSU',
    city: 'Petersburg',
    state: 'VA',
    zip_code: '23806',
    latitude: 37.2428,
    longitude: -77.4134,
    type: 'university',
    campus_type: 'main',
    enrollment: 4200,
    is_public: true,
    primary_color: '#FF6600',
    secondary_color: '#003366',
    website: 'https://www.vsu.edu',
    aliases: ['Virginia State', 'Trojans']
  },
  {
    id: 'radford',
    name: 'Radford University',
    short_name: 'Radford',
    city: 'Radford',
    state: 'VA',
    zip_code: '24142',
    latitude: 37.1343,
    longitude: -80.5542,
    type: 'university',
    campus_type: 'main',
    enrollment: 7800,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#003366',
    website: 'https://www.radford.edu',
    aliases: ['Highlanders']
  },
  {
    id: 'longwood',
    name: 'Longwood University',
    short_name: 'Longwood',
    city: 'Farmville',
    state: 'VA',
    zip_code: '23909',
    latitude: 37.2984,
    longitude: -78.3953,
    type: 'university',
    campus_type: 'main',
    enrollment: 5100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.longwood.edu',
    aliases: ['Lancers']
  }
];

// ============================================================================
// MASSACHUSETTS PUBLIC UNIVERSITIES
// ============================================================================

export const MASSACHUSETTS_UNIVERSITIES: University[] = [
  {
    id: 'umass-amherst',
    name: 'University of Massachusetts Amherst',
    short_name: 'UMass Amherst',
    system_name: 'University of Massachusetts',
    city: 'Amherst',
    state: 'MA',
    zip_code: '01003',
    latitude: 42.3912,
    longitude: -72.5267,
    type: 'university',
    campus_type: 'main',
    enrollment: 32000,
    international_students: 4200,
    is_public: true,
    primary_color: '#881C1C',
    secondary_color: '#000000',
    website: 'https://www.umass.edu',
    aliases: ['UMass', 'Minutemen', 'Amherst']
  },
  {
    id: 'umass-boston',
    name: 'University of Massachusetts Boston',
    short_name: 'UMass Boston',
    system_name: 'University of Massachusetts',
    city: 'Boston',
    state: 'MA',
    zip_code: '02125',
    latitude: 42.3145,
    longitude: -71.0371,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 1800,
    is_public: true,
    primary_color: '#005A8C',
    secondary_color: '#FFD200',
    website: 'https://www.umb.edu',
    aliases: ['UMB', 'Beacons']
  },
  {
    id: 'umass-lowell',
    name: 'University of Massachusetts Lowell',
    short_name: 'UMass Lowell',
    system_name: 'University of Massachusetts',
    city: 'Lowell',
    state: 'MA',
    zip_code: '01854',
    latitude: 42.6539,
    longitude: -71.3284,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 1600,
    is_public: true,
    primary_color: '#0067B1',
    secondary_color: '#CC0000',
    website: 'https://www.uml.edu',
    aliases: ['UML', 'River Hawks']
  },
  {
    id: 'umass-dartmouth',
    name: 'University of Massachusetts Dartmouth',
    short_name: 'UMass Dartmouth',
    system_name: 'University of Massachusetts',
    city: 'Dartmouth',
    state: 'MA',
    zip_code: '02747',
    latitude: 41.6289,
    longitude: -70.9976,
    type: 'university',
    campus_type: 'main',
    enrollment: 8000,
    is_public: true,
    primary_color: '#00529B',
    secondary_color: '#FFD200',
    website: 'https://www.umassd.edu',
    aliases: ['UMD', 'Corsairs']
  },
  {
    id: 'umass-chan',
    name: 'UMass Chan Medical School',
    short_name: 'UMass Chan',
    system_name: 'University of Massachusetts',
    city: 'Worcester',
    state: 'MA',
    zip_code: '01655',
    latitude: 42.2779,
    longitude: -71.7618,
    type: 'university',
    campus_type: 'main',
    enrollment: 1300,
    is_public: true,
    primary_color: '#881C1C',
    secondary_color: '#000000',
    website: 'https://www.umassmed.edu',
    aliases: ['UMass Medical']
  }
];

// ============================================================================
// ARIZONA UNIVERSITIES
// ============================================================================

export const ARIZONA_UNIVERSITIES: University[] = [
  {
    id: 'asu',
    name: 'Arizona State University',
    short_name: 'ASU',
    city: 'Tempe',
    state: 'AZ',
    zip_code: '85287',
    latitude: 33.4242,
    longitude: -111.9281,
    type: 'university',
    campus_type: 'main',
    enrollment: 74795,
    international_students: 12500,
    is_public: true,
    primary_color: '#8C1D40',
    secondary_color: '#FFC627',
    website: 'https://www.asu.edu',
    aliases: ['Arizona State', 'Sun Devils']
  },
  {
    id: 'asu-west',
    name: 'Arizona State University - West Campus',
    short_name: 'ASU West',
    system_name: 'Arizona State University',
    city: 'Glendale',
    state: 'AZ',
    zip_code: '85306',
    latitude: 33.6085,
    longitude: -112.1596,
    type: 'university',
    campus_type: 'branch',
    enrollment: 4500,
    is_public: true,
    primary_color: '#8C1D40',
    secondary_color: '#FFC627',
    website: 'https://campus.asu.edu/west'
  },
  {
    id: 'asu-polytechnic',
    name: 'Arizona State University - Polytechnic Campus',
    short_name: 'ASU Poly',
    system_name: 'Arizona State University',
    city: 'Mesa',
    state: 'AZ',
    zip_code: '85212',
    latitude: 33.3060,
    longitude: -111.6797,
    type: 'university',
    campus_type: 'branch',
    enrollment: 5500,
    is_public: true,
    primary_color: '#8C1D40',
    secondary_color: '#FFC627',
    website: 'https://campus.asu.edu/polytechnic'
  },
  {
    id: 'asu-downtown',
    name: 'Arizona State University - Downtown Phoenix Campus',
    short_name: 'ASU Downtown',
    system_name: 'Arizona State University',
    city: 'Phoenix',
    state: 'AZ',
    zip_code: '85004',
    latitude: 33.4516,
    longitude: -112.0673,
    type: 'university',
    campus_type: 'branch',
    enrollment: 12000,
    is_public: true,
    primary_color: '#8C1D40',
    secondary_color: '#FFC627',
    website: 'https://campus.asu.edu/downtown-phoenix'
  },
  {
    id: 'uarizona',
    name: 'University of Arizona',
    short_name: 'Arizona',
    city: 'Tucson',
    state: 'AZ',
    zip_code: '85721',
    latitude: 32.2319,
    longitude: -110.9501,
    type: 'university',
    campus_type: 'main',
    enrollment: 49403,
    international_students: 4800,
    is_public: true,
    primary_color: '#CC0033',
    secondary_color: '#003366',
    website: 'https://www.arizona.edu',
    aliases: ['U of A', 'UA', 'Wildcats']
  },
  {
    id: 'nau',
    name: 'Northern Arizona University',
    short_name: 'NAU',
    city: 'Flagstaff',
    state: 'AZ',
    zip_code: '86011',
    latitude: 35.1886,
    longitude: -111.6534,
    type: 'university',
    campus_type: 'main',
    enrollment: 28000,
    international_students: 1200,
    is_public: true,
    primary_color: '#003466',
    secondary_color: '#FFC627',
    website: 'https://www.nau.edu',
    aliases: ['Northern Arizona', 'Lumberjacks']
  }
];

// ============================================================================
// COLORADO UNIVERSITIES
// ============================================================================

export const COLORADO_UNIVERSITIES: University[] = [
  {
    id: 'cu-boulder',
    name: 'University of Colorado Boulder',
    short_name: 'CU Boulder',
    system_name: 'University of Colorado',
    city: 'Boulder',
    state: 'CO',
    zip_code: '80309',
    latitude: 40.0076,
    longitude: -105.2659,
    type: 'university',
    campus_type: 'main',
    enrollment: 36312,
    international_students: 3200,
    is_public: true,
    primary_color: '#CFB87C',
    secondary_color: '#000000',
    website: 'https://www.colorado.edu',
    aliases: ['Colorado', 'Buffaloes', 'CU']
  },
  {
    id: 'cu-denver',
    name: 'University of Colorado Denver',
    short_name: 'CU Denver',
    system_name: 'University of Colorado',
    city: 'Denver',
    state: 'CO',
    zip_code: '80204',
    latitude: 39.7457,
    longitude: -105.0073,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 1800,
    is_public: true,
    primary_color: '#CFB87C',
    secondary_color: '#000000',
    website: 'https://www.ucdenver.edu',
    aliases: ['UC Denver', 'Lynx']
  },
  {
    id: 'cu-anschutz',
    name: 'University of Colorado Anschutz Medical Campus',
    short_name: 'CU Anschutz',
    system_name: 'University of Colorado',
    city: 'Aurora',
    state: 'CO',
    zip_code: '80045',
    latitude: 39.7462,
    longitude: -104.8385,
    type: 'university',
    campus_type: 'main',
    enrollment: 4500,
    is_public: true,
    primary_color: '#CFB87C',
    secondary_color: '#000000',
    website: 'https://www.cuanschutz.edu'
  },
  {
    id: 'uccs',
    name: 'University of Colorado Colorado Springs',
    short_name: 'UCCS',
    system_name: 'University of Colorado',
    city: 'Colorado Springs',
    state: 'CO',
    zip_code: '80918',
    latitude: 38.8942,
    longitude: -104.7988,
    type: 'university',
    campus_type: 'main',
    enrollment: 12000,
    is_public: true,
    primary_color: '#CFB87C',
    secondary_color: '#000000',
    website: 'https://www.uccs.edu',
    aliases: ['Mountain Lions']
  },
  {
    id: 'csu',
    name: 'Colorado State University',
    short_name: 'Colorado State',
    city: 'Fort Collins',
    state: 'CO',
    zip_code: '80523',
    latitude: 40.5734,
    longitude: -105.0865,
    type: 'university',
    campus_type: 'main',
    enrollment: 33877,
    international_students: 1800,
    is_public: true,
    primary_color: '#1E4D2B',
    secondary_color: '#C8C372',
    website: 'https://www.colostate.edu',
    aliases: ['CSU', 'Rams']
  },
  {
    id: 'colorado-mines',
    name: 'Colorado School of Mines',
    short_name: 'Mines',
    city: 'Golden',
    state: 'CO',
    zip_code: '80401',
    latitude: 39.7514,
    longitude: -105.2222,
    type: 'university',
    campus_type: 'main',
    enrollment: 6800,
    international_students: 1100,
    is_public: true,
    primary_color: '#21314D',
    secondary_color: '#8B8D8F',
    website: 'https://www.mines.edu',
    aliases: ['CSM', 'Orediggers']
  },
  {
    id: 'unc-colorado',
    name: 'University of Northern Colorado',
    short_name: 'UNC',
    city: 'Greeley',
    state: 'CO',
    zip_code: '80639',
    latitude: 40.4063,
    longitude: -104.6992,
    type: 'university',
    campus_type: 'main',
    enrollment: 9600,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.unco.edu',
    aliases: ['Northern Colorado', 'Bears']
  }
];

// ============================================================================
// WASHINGTON STATE UNIVERSITIES (Additional)
// ============================================================================

export const WASHINGTON_ADDITIONAL: University[] = [
  {
    id: 'wwu',
    name: 'Western Washington University',
    short_name: 'WWU',
    city: 'Bellingham',
    state: 'WA',
    zip_code: '98225',
    latitude: 48.7336,
    longitude: -122.4865,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    is_public: true,
    primary_color: '#003F87',
    secondary_color: '#FFFFFF',
    website: 'https://www.wwu.edu',
    aliases: ['Western', 'Vikings']
  },
  {
    id: 'cwu',
    name: 'Central Washington University',
    short_name: 'CWU',
    city: 'Ellensburg',
    state: 'WA',
    zip_code: '98926',
    latitude: 46.9965,
    longitude: -120.5433,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    is_public: true,
    primary_color: '#A60F2D',
    secondary_color: '#000000',
    website: 'https://www.cwu.edu',
    aliases: ['Central', 'Wildcats']
  },
  {
    id: 'ewu',
    name: 'Eastern Washington University',
    short_name: 'EWU',
    city: 'Cheney',
    state: 'WA',
    zip_code: '99004',
    latitude: 47.4915,
    longitude: -117.5763,
    type: 'university',
    campus_type: 'main',
    enrollment: 11000,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#000000',
    website: 'https://www.ewu.edu',
    aliases: ['Eastern', 'Eagles']
  }
];

// ============================================================================
// COMBINE ALL ADDITIONAL STATE UNIVERSITIES
// ============================================================================

export const ALL_ADDITIONAL_STATE_UNIVERSITIES: University[] = [
  ...FLORIDA_SUS,
  ...GEORGIA_USG,
  ...UNC_SYSTEM,
  ...VIRGINIA_UNIVERSITIES,
  ...MASSACHUSETTS_UNIVERSITIES,
  ...ARIZONA_UNIVERSITIES,
  ...COLORADO_UNIVERSITIES,
  ...WASHINGTON_ADDITIONAL
];
