// ============================================================================
// CANADA UNIVERSITIES & COLLEGES - COMPREHENSIVE LIST
// ============================================================================

import { University } from './types';

// Major Canadian Universities (U15 Group and others)
export const CANADIAN_UNIVERSITIES: University[] = [
  // U15 Research Universities
  {
    id: 'uoft-stgeorge',
    name: 'University of Toronto - St. George',
    short_name: 'U of T',
    system_name: 'University of Toronto',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M5S 1A1',
    latitude: 43.6629,
    longitude: -79.3957,
    type: 'university',
    campus_type: 'main',
    enrollment: 73000,
    international_students: 25550,
    international_percentage: 35,
    is_public: true,
    primary_color: '#002A5C',
    secondary_color: '#FFE498',
    website: 'https://www.utoronto.ca',
    aliases: ['U of T', 'Toronto', 'UofT'],
  },
  {
    id: 'uoft-scarborough',
    name: 'University of Toronto Scarborough',
    short_name: 'UTSC',
    system_name: 'University of Toronto',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M1C 1A4',
    latitude: 43.7845,
    longitude: -79.1864,
    type: 'university',
    campus_type: 'branch',
    enrollment: 15000,
    international_students: 5250,
    international_percentage: 35,
    is_public: true,
    primary_color: '#002A5C',
    secondary_color: '#FFE498',
    website: 'https://www.utsc.utoronto.ca',
    aliases: ['UTSC', 'U of T Scarborough'],
  },
  {
    id: 'uoft-mississauga',
    name: 'University of Toronto Mississauga',
    short_name: 'UTM',
    system_name: 'University of Toronto',
    city: 'Mississauga',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L5L 1C6',
    latitude: 43.5489,
    longitude: -79.6626,
    type: 'university',
    campus_type: 'branch',
    enrollment: 15000,
    international_students: 5250,
    international_percentage: 35,
    is_public: true,
    primary_color: '#002A5C',
    secondary_color: '#FFE498',
    website: 'https://www.utm.utoronto.ca',
    aliases: ['UTM', 'U of T Mississauga'],
  },
  {
    id: 'mcgill',
    name: 'McGill University',
    short_name: 'McGill',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H3A 0G4',
    latitude: 45.5048,
    longitude: -73.5772,
    type: 'university',
    campus_type: 'main',
    enrollment: 40000,
    international_students: 12000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#ED1B2F',
    secondary_color: '#FFFFFF',
    website: 'https://www.mcgill.ca',
    aliases: ['McGill University'],
  },
  {
    id: 'ubc-vancouver',
    name: 'University of British Columbia - Vancouver',
    short_name: 'UBC',
    system_name: 'University of British Columbia',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V6T 1Z4',
    latitude: 49.2606,
    longitude: -123.2460,
    type: 'university',
    campus_type: 'main',
    enrollment: 55000,
    international_students: 17600,
    international_percentage: 32,
    is_public: true,
    primary_color: '#002145',
    secondary_color: '#97D4E9',
    website: 'https://www.ubc.ca',
    aliases: ['UBC', 'UBC Vancouver'],
  },
  {
    id: 'ubc-okanagan',
    name: 'University of British Columbia - Okanagan',
    short_name: 'UBCO',
    system_name: 'University of British Columbia',
    city: 'Kelowna',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V1V 1V7',
    latitude: 49.9399,
    longitude: -119.3970,
    type: 'university',
    campus_type: 'branch',
    enrollment: 11000,
    international_students: 2750,
    international_percentage: 25,
    is_public: true,
    primary_color: '#002145',
    secondary_color: '#97D4E9',
    website: 'https://ok.ubc.ca',
    aliases: ['UBCO', 'UBC Okanagan'],
  },
  {
    id: 'waterloo',
    name: 'University of Waterloo',
    short_name: 'Waterloo',
    city: 'Waterloo',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N2L 3G1',
    latitude: 43.4723,
    longitude: -80.5449,
    type: 'university',
    campus_type: 'main',
    enrollment: 42000,
    international_students: 13020,
    international_percentage: 31,
    is_public: true,
    primary_color: '#FFD54F',
    secondary_color: '#000000',
    website: 'https://uwaterloo.ca',
    aliases: ['UWaterloo', 'UW', 'Waterloo'],
  },
  {
    id: 'mcmaster',
    name: 'McMaster University',
    short_name: 'McMaster',
    city: 'Hamilton',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L8S 4L8',
    latitude: 43.2609,
    longitude: -79.9192,
    type: 'university',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 6600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#7A003C',
    secondary_color: '#FDBF57',
    website: 'https://www.mcmaster.ca',
    aliases: ['Mac', 'McMaster'],
  },
  {
    id: 'ualberta',
    name: 'University of Alberta',
    short_name: 'UAlberta',
    city: 'Edmonton',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T6G 2R3',
    latitude: 53.5232,
    longitude: -113.5263,
    type: 'university',
    campus_type: 'main',
    enrollment: 40000,
    international_students: 8000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#007C41',
    secondary_color: '#FFDB05',
    website: 'https://www.ualberta.ca',
    aliases: ['U of A', 'UAlberta'],
  },
  {
    id: 'umontreal',
    name: 'Université de Montréal',
    short_name: 'UdeM',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H3T 1J4',
    latitude: 45.5017,
    longitude: -73.6157,
    type: 'university',
    campus_type: 'main',
    enrollment: 45000,
    international_students: 9000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#0072BC',
    secondary_color: '#FFFFFF',
    website: 'https://www.umontreal.ca',
    aliases: ['UdeM', 'University of Montreal'],
  },
  {
    id: 'uottawa',
    name: 'University of Ottawa',
    short_name: 'uOttawa',
    city: 'Ottawa',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K1N 6N5',
    latitude: 45.4231,
    longitude: -75.6831,
    type: 'university',
    campus_type: 'main',
    enrollment: 42000,
    international_students: 8400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#8F001A',
    secondary_color: '#2D2D2D',
    website: 'https://www.uottawa.ca',
    aliases: ['uOttawa', 'Ottawa U'],
  },
  {
    id: 'western',
    name: 'Western University',
    short_name: 'Western',
    city: 'London',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N6A 3K7',
    latitude: 43.0096,
    longitude: -81.2737,
    type: 'university',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 6600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#4F2683',
    secondary_color: '#807F83',
    website: 'https://www.uwo.ca',
    aliases: ['Western', 'UWO'],
  },
  {
    id: 'queens',
    name: "Queen's University",
    short_name: "Queen's",
    city: 'Kingston',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K7L 3N6',
    latitude: 44.2253,
    longitude: -76.4951,
    type: 'university',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 3900,
    international_percentage: 15,
    is_public: true,
    primary_color: '#002452',
    secondary_color: '#FABD0F',
    website: 'https://www.queensu.ca',
    aliases: ["Queen's University"],
  },
  {
    id: 'ucalgary',
    name: 'University of Calgary',
    short_name: 'UCalgary',
    city: 'Calgary',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T2N 1N4',
    latitude: 51.0778,
    longitude: -114.1300,
    type: 'university',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 6600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#CF0722',
    secondary_color: '#FFD300',
    website: 'https://www.ucalgary.ca',
    aliases: ['U of C', 'UCalgary'],
  },
  {
    id: 'sfu',
    name: 'Simon Fraser University',
    short_name: 'SFU',
    city: 'Burnaby',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V5A 1S6',
    latitude: 49.2781,
    longitude: -122.9199,
    type: 'university',
    campus_type: 'main',
    enrollment: 35000,
    international_students: 8750,
    international_percentage: 25,
    is_public: true,
    primary_color: '#CC0633',
    secondary_color: '#54585A',
    website: 'https://www.sfu.ca',
    aliases: ['SFU', 'Simon Fraser'],
  },
  {
    id: 'york',
    name: 'York University',
    short_name: 'York',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M3J 1P3',
    latitude: 43.7735,
    longitude: -79.5019,
    type: 'university',
    campus_type: 'main',
    enrollment: 55000,
    international_students: 11000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#E31837',
    secondary_color: '#FFFFFF',
    website: 'https://www.yorku.ca',
    aliases: ['York U', 'YorkU'],
  },
  {
    id: 'dalhousie',
    name: 'Dalhousie University',
    short_name: 'Dal',
    city: 'Halifax',
    state: 'Nova Scotia',
    country: 'CA',
    zip_code: 'B3H 4R2',
    latitude: 44.6366,
    longitude: -63.5917,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 4000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#FFD400',
    secondary_color: '#000000',
    website: 'https://www.dal.ca',
    aliases: ['Dal', 'Dalhousie'],
  },
  {
    id: 'uvic',
    name: 'University of Victoria',
    short_name: 'UVic',
    city: 'Victoria',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V8W 2Y2',
    latitude: 48.4634,
    longitude: -123.3117,
    type: 'university',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 4400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#002754',
    secondary_color: '#C63527',
    website: 'https://www.uvic.ca',
    aliases: ['UVic', 'Victoria'],
  },
  {
    id: 'umanitoba',
    name: 'University of Manitoba',
    short_name: 'UManitoba',
    city: 'Winnipeg',
    state: 'Manitoba',
    country: 'CA',
    zip_code: 'R3T 2N2',
    latitude: 49.8075,
    longitude: -97.1365,
    type: 'university',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 6000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#7C1631',
    secondary_color: '#CDA53C',
    website: 'https://umanitoba.ca',
    aliases: ['U of M', 'UManitoba'],
  },
  {
    id: 'tmu',
    name: 'Toronto Metropolitan University',
    short_name: 'TMU',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M5B 2K3',
    latitude: 43.6577,
    longitude: -79.3788,
    type: 'university',
    campus_type: 'main',
    enrollment: 46000,
    international_students: 9200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#004C9B',
    secondary_color: '#FFD700',
    website: 'https://www.torontomu.ca',
    aliases: ['TMU', 'Ryerson', 'Toronto Met'],
  },
  {
    id: 'carleton',
    name: 'Carleton University',
    short_name: 'Carleton',
    city: 'Ottawa',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K1S 5B6',
    latitude: 45.3876,
    longitude: -75.6960,
    type: 'university',
    campus_type: 'main',
    enrollment: 31000,
    international_students: 6200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#000000',
    website: 'https://carleton.ca',
    aliases: ['Carleton'],
  },
  {
    id: 'concordia',
    name: 'Concordia University',
    short_name: 'Concordia',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H3G 1M8',
    latitude: 45.4973,
    longitude: -73.5789,
    type: 'university',
    campus_type: 'main',
    enrollment: 51000,
    international_students: 10200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#8F2749',
    secondary_color: '#002145',
    website: 'https://www.concordia.ca',
    aliases: ['Concordia'],
  },
  {
    id: 'guelph',
    name: 'University of Guelph',
    short_name: 'Guelph',
    city: 'Guelph',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N1G 2W1',
    latitude: 43.5327,
    longitude: -80.2262,
    type: 'university',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 4500,
    international_percentage: 15,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#FFD700',
    website: 'https://www.uoguelph.ca',
    aliases: ['U of G', 'Guelph'],
  },
  {
    id: 'usask',
    name: 'University of Saskatchewan',
    short_name: 'USask',
    city: 'Saskatoon',
    state: 'Saskatchewan',
    country: 'CA',
    zip_code: 'S7N 5A2',
    latitude: 52.1332,
    longitude: -106.6316,
    type: 'university',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 5200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFCD00',
    website: 'https://www.usask.ca',
    aliases: ['U of S', 'USask'],
  },
  {
    id: 'laval',
    name: 'Université Laval',
    short_name: 'Laval',
    city: 'Quebec City',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'G1V 0A6',
    latitude: 46.7800,
    longitude: -71.2761,
    type: 'university',
    campus_type: 'main',
    enrollment: 45000,
    international_students: 6750,
    international_percentage: 15,
    is_public: true,
    primary_color: '#FFCD00',
    secondary_color: '#C20430',
    website: 'https://www.ulaval.ca',
    aliases: ['Laval'],
  },
  {
    id: 'sherbrooke',
    name: 'Université de Sherbrooke',
    short_name: 'UdeS',
    city: 'Sherbrooke',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'J1K 2R1',
    latitude: 45.3787,
    longitude: -71.9287,
    type: 'university',
    campus_type: 'main',
    enrollment: 31000,
    international_students: 4650,
    international_percentage: 15,
    is_public: true,
    primary_color: '#007849',
    secondary_color: '#FFD700',
    website: 'https://www.usherbrooke.ca',
    aliases: ['UdeS', 'Sherbrooke'],
  },
  {
    id: 'unb',
    name: 'University of New Brunswick',
    short_name: 'UNB',
    city: 'Fredericton',
    state: 'New Brunswick',
    country: 'CA',
    zip_code: 'E3B 5A3',
    latitude: 45.9500,
    longitude: -66.6400,
    type: 'university',
    campus_type: 'main',
    enrollment: 10500,
    international_students: 2100,
    international_percentage: 20,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#000000',
    website: 'https://www.unb.ca',
    aliases: ['UNB'],
  },
  {
    id: 'windsor',
    name: 'University of Windsor',
    short_name: 'Windsor',
    city: 'Windsor',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N9B 3P4',
    latitude: 42.3058,
    longitude: -83.0639,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 4800,
    international_percentage: 30,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#FFD700',
    website: 'https://www.uwindsor.ca',
    aliases: ['U of Windsor', 'Windsor'],
  },
  {
    id: 'memorial',
    name: 'Memorial University of Newfoundland',
    short_name: 'Memorial',
    city: "St. John's",
    state: 'Newfoundland and Labrador',
    country: 'CA',
    zip_code: 'A1C 5S7',
    latitude: 47.5731,
    longitude: -52.7327,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 2850,
    international_percentage: 15,
    is_public: true,
    primary_color: '#7A003C',
    secondary_color: '#007749',
    website: 'https://www.mun.ca',
    aliases: ['MUN', 'Memorial'],
  },
  {
    id: 'brock',
    name: 'Brock University',
    short_name: 'Brock',
    city: 'St. Catharines',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L2S 3A1',
    latitude: 43.1174,
    longitude: -79.2471,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 3800,
    international_percentage: 20,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#000000',
    website: 'https://brocku.ca',
    aliases: ['Brock'],
  },
  {
    id: 'regina',
    name: 'University of Regina',
    short_name: 'URegina',
    city: 'Regina',
    state: 'Saskatchewan',
    country: 'CA',
    zip_code: 'S4S 0A2',
    latitude: 50.4189,
    longitude: -104.5859,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 3200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://www.uregina.ca',
    aliases: ['U of R', 'URegina'],
  },
  {
    id: 'laurier',
    name: 'Wilfrid Laurier University',
    short_name: 'Laurier',
    city: 'Waterloo',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N2L 3C5',
    latitude: 43.4738,
    longitude: -80.5275,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 2850,
    international_percentage: 15,
    is_public: true,
    primary_color: '#4F2683',
    secondary_color: '#FFD700',
    website: 'https://www.wlu.ca',
    aliases: ['WLU', 'Laurier'],
  },
  {
    id: 'trent',
    name: 'Trent University',
    short_name: 'Trent',
    city: 'Peterborough',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K9L 0G2',
    latitude: 44.3564,
    longitude: -78.2889,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 1500,
    international_percentage: 15,
    is_public: true,
    primary_color: '#006400',
    secondary_color: '#FFD700',
    website: 'https://www.trentu.ca',
    aliases: ['Trent'],
  },
  {
    id: 'lakehead',
    name: 'Lakehead University',
    short_name: 'Lakehead',
    city: 'Thunder Bay',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'P7B 5E1',
    latitude: 48.4215,
    longitude: -89.2615,
    type: 'university',
    campus_type: 'main',
    enrollment: 8500,
    international_students: 1700,
    international_percentage: 20,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#FFD700',
    website: 'https://www.lakeheadu.ca',
    aliases: ['Lakehead'],
  },
  {
    id: 'nipissing',
    name: 'Nipissing University',
    short_name: 'Nipissing',
    city: 'North Bay',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'P1B 8L7',
    latitude: 46.3192,
    longitude: -79.4628,
    type: 'university',
    campus_type: 'main',
    enrollment: 5000,
    international_students: 500,
    international_percentage: 10,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#C20430',
    website: 'https://www.nipissingu.ca',
    aliases: ['Nipissing'],
  },
  {
    id: 'uoit',
    name: 'Ontario Tech University',
    short_name: 'Ontario Tech',
    city: 'Oshawa',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L1G 0C5',
    latitude: 43.9452,
    longitude: -78.8951,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 2000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://ontariotechu.ca',
    aliases: ['UOIT', 'Ontario Tech'],
  },
  {
    id: 'laurentian',
    name: 'Laurentian University',
    short_name: 'Laurentian',
    city: 'Sudbury',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'P3E 2C6',
    latitude: 46.4675,
    longitude: -80.9720,
    type: 'university',
    campus_type: 'main',
    enrollment: 6000,
    international_students: 900,
    international_percentage: 15,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#FFD700',
    website: 'https://laurentian.ca',
    aliases: ['Laurentian'],
  },
  {
    id: 'uqam',
    name: 'Université du Québec à Montréal',
    short_name: 'UQAM',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H2X 3R9',
    latitude: 45.5088,
    longitude: -73.5687,
    type: 'university',
    campus_type: 'main',
    enrollment: 40000,
    international_students: 6000,
    international_percentage: 15,
    is_public: true,
    primary_color: '#008B8B',
    secondary_color: '#000000',
    website: 'https://uqam.ca',
    aliases: ['UQAM'],
  },
  {
    id: 'uqac',
    name: 'Université du Québec à Chicoutimi',
    short_name: 'UQAC',
    city: 'Chicoutimi',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'G7H 2B1',
    latitude: 48.4194,
    longitude: -71.0531,
    type: 'university',
    campus_type: 'main',
    enrollment: 6000,
    international_students: 900,
    international_percentage: 15,
    is_public: true,
    primary_color: '#008B8B',
    secondary_color: '#FFD700',
    website: 'https://www.uqac.ca',
    aliases: ['UQAC'],
  },
  {
    id: 'acadia',
    name: 'Acadia University',
    short_name: 'Acadia',
    city: 'Wolfville',
    state: 'Nova Scotia',
    country: 'CA',
    zip_code: 'B4P 2R6',
    latitude: 45.0883,
    longitude: -64.3641,
    type: 'university',
    campus_type: 'main',
    enrollment: 4000,
    international_students: 600,
    international_percentage: 15,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#002147',
    website: 'https://www2.acadiau.ca',
    aliases: ['Acadia'],
  },
  {
    id: 'stfx',
    name: "St. Francis Xavier University",
    short_name: 'StFX',
    city: 'Antigonish',
    state: 'Nova Scotia',
    country: 'CA',
    zip_code: 'B2G 2W5',
    latitude: 45.6218,
    longitude: -61.9985,
    type: 'university',
    campus_type: 'main',
    enrollment: 4500,
    international_students: 450,
    international_percentage: 10,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#FFFFFF',
    website: 'https://www.stfx.ca',
    aliases: ['StFX', 'St FX'],
  },
  {
    id: 'mta',
    name: 'Mount Allison University',
    short_name: 'Mt. A',
    city: 'Sackville',
    state: 'New Brunswick',
    country: 'CA',
    zip_code: 'E4L 1E4',
    latitude: 45.8986,
    longitude: -64.3703,
    type: 'university',
    campus_type: 'main',
    enrollment: 2300,
    international_students: 460,
    international_percentage: 20,
    is_public: true,
    primary_color: '#7A003C',
    secondary_color: '#FFD700',
    website: 'https://www.mta.ca',
    aliases: ['Mount A', 'Mt. Allison'],
  },
  {
    id: 'upei',
    name: 'University of Prince Edward Island',
    short_name: 'UPEI',
    city: 'Charlottetown',
    state: 'Prince Edward Island',
    country: 'CA',
    zip_code: 'C1A 4P3',
    latitude: 46.2592,
    longitude: -63.1350,
    type: 'university',
    campus_type: 'main',
    enrollment: 5000,
    international_students: 1000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#A50034',
    website: 'https://www.upei.ca',
    aliases: ['UPEI'],
  },
  {
    id: 'uleth',
    name: 'University of Lethbridge',
    short_name: 'ULeth',
    city: 'Lethbridge',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T1K 3M4',
    latitude: 49.6818,
    longitude: -112.8687,
    type: 'university',
    campus_type: 'main',
    enrollment: 8700,
    international_students: 1305,
    international_percentage: 15,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#A50034',
    website: 'https://www.uleth.ca',
    aliases: ['U of L', 'ULeth'],
  },
  {
    id: 'kwantlen',
    name: 'Kwantlen Polytechnic University',
    short_name: 'KPU',
    city: 'Surrey',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V3W 2M8',
    latitude: 49.1319,
    longitude: -122.8711,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 6000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://www.kpu.ca',
    aliases: ['KPU', 'Kwantlen'],
  },
  {
    id: 'royalroads',
    name: 'Royal Roads University',
    short_name: 'Royal Roads',
    city: 'Victoria',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V9B 5Y2',
    latitude: 48.4345,
    longitude: -123.4729,
    type: 'university',
    campus_type: 'main',
    enrollment: 5000,
    international_students: 1500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#FFD700',
    website: 'https://www.royalroads.ca',
    aliases: ['RRU', 'Royal Roads'],
  },
  {
    id: 'mru',
    name: 'Mount Royal University',
    short_name: 'MRU',
    city: 'Calgary',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T3E 6K6',
    latitude: 51.0109,
    longitude: -114.1298,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 2250,
    international_percentage: 15,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.mtroyal.ca',
    aliases: ['MRU', 'Mount Royal'],
  },
  {
    id: 'macewan',
    name: 'MacEwan University',
    short_name: 'MacEwan',
    city: 'Edmonton',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T5J 4S2',
    latitude: 53.5472,
    longitude: -113.5055,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 2850,
    international_percentage: 15,
    is_public: true,
    primary_color: '#FFD700',
    secondary_color: '#002147',
    website: 'https://www.macewan.ca',
    aliases: ['MacEwan'],
  },
  {
    id: 'tru',
    name: 'Thompson Rivers University',
    short_name: 'TRU',
    city: 'Kamloops',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V2C 0C8',
    latitude: 50.6702,
    longitude: -120.3633,
    type: 'university',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 4200,
    international_percentage: 30,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#006341',
    website: 'https://www.tru.ca',
    aliases: ['TRU'],
  },
  {
    id: 'unbc',
    name: 'University of Northern British Columbia',
    short_name: 'UNBC',
    city: 'Prince George',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V2N 4Z9',
    latitude: 53.8937,
    longitude: -122.8118,
    type: 'university',
    campus_type: 'main',
    enrollment: 4000,
    international_students: 600,
    international_percentage: 15,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#006341',
    website: 'https://www.unbc.ca',
    aliases: ['UNBC'],
  },
  {
    id: 'ufv',
    name: 'University of the Fraser Valley',
    short_name: 'UFV',
    city: 'Abbotsford',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V2S 7M8',
    latitude: 49.0304,
    longitude: -122.2846,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 4500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://www.ufv.ca',
    aliases: ['UFV'],
  },
  {
    id: 'capilano',
    name: 'Capilano University',
    short_name: 'CapU',
    city: 'North Vancouver',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V7J 3H5',
    latitude: 49.3481,
    longitude: -123.0775,
    type: 'university',
    campus_type: 'main',
    enrollment: 8000,
    international_students: 2400,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.capilanou.ca',
    aliases: ['CapU', 'Capilano'],
  },
  {
    id: 'ecuad',
    name: 'Emily Carr University of Art + Design',
    short_name: 'Emily Carr',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V6H 3R9',
    latitude: 49.2629,
    longitude: -123.1364,
    type: 'university',
    campus_type: 'main',
    enrollment: 2000,
    international_students: 600,
    international_percentage: 30,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFFFFF',
    website: 'https://www.ecuad.ca',
    aliases: ['Emily Carr', 'ECUAD'],
  },
  {
    id: 'ocad',
    name: 'OCAD University',
    short_name: 'OCAD U',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M5T 1W1',
    latitude: 43.6516,
    longitude: -79.3920,
    type: 'university',
    campus_type: 'main',
    enrollment: 5000,
    international_students: 1000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#E40046',
    website: 'https://www.ocadu.ca',
    aliases: ['OCAD', 'OCAD U'],
  },
  {
    id: 'nscad',
    name: 'NSCAD University',
    short_name: 'NSCAD',
    city: 'Halifax',
    state: 'Nova Scotia',
    country: 'CA',
    zip_code: 'B3J 3J6',
    latitude: 44.6476,
    longitude: -63.5728,
    type: 'university',
    campus_type: 'main',
    enrollment: 1000,
    international_students: 200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#E40046',
    website: 'https://nscad.ca',
    aliases: ['NSCAD'],
  },
];

// Canadian Colleges
export const CANADIAN_COLLEGES: University[] = [
  {
    id: 'seneca',
    name: 'Seneca College',
    short_name: 'Seneca',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M2J 2X5',
    latitude: 43.7958,
    longitude: -79.3486,
    type: 'college',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 12000,
    international_percentage: 40,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#000000',
    website: 'https://www.senecacollege.ca',
    aliases: ['Seneca College'],
  },
  {
    id: 'humber',
    name: 'Humber College',
    short_name: 'Humber',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M9W 5L7',
    latitude: 43.7284,
    longitude: -79.6073,
    type: 'college',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 13200,
    international_percentage: 40,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://humber.ca',
    aliases: ['Humber College'],
  },
  {
    id: 'george-brown',
    name: 'George Brown College',
    short_name: 'George Brown',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M5A 1H3',
    latitude: 43.6512,
    longitude: -79.3705,
    type: 'college',
    campus_type: 'main',
    enrollment: 32000,
    international_students: 12800,
    international_percentage: 40,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://www.georgebrown.ca',
    aliases: ['GBC', 'George Brown'],
  },
  {
    id: 'sheridan',
    name: 'Sheridan College',
    short_name: 'Sheridan',
    city: 'Oakville',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L6H 2L1',
    latitude: 43.4686,
    longitude: -79.7000,
    type: 'college',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 10000,
    international_percentage: 40,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.sheridancollege.ca',
    aliases: ['Sheridan College'],
  },
  {
    id: 'centennial',
    name: 'Centennial College',
    short_name: 'Centennial',
    city: 'Toronto',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'M1K 5E9',
    latitude: 43.7856,
    longitude: -79.2294,
    type: 'college',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 10400,
    international_percentage: 40,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#000000',
    website: 'https://www.centennialcollege.ca',
    aliases: ['Centennial College'],
  },
  {
    id: 'bcit',
    name: 'British Columbia Institute of Technology',
    short_name: 'BCIT',
    city: 'Burnaby',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V5G 3H2',
    latitude: 49.2500,
    longitude: -123.0000,
    type: 'college',
    campus_type: 'main',
    enrollment: 48000,
    international_students: 9600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.bcit.ca',
    aliases: ['BCIT'],
  },
  {
    id: 'langara',
    name: 'Langara College',
    short_name: 'Langara',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V5Y 2Z6',
    latitude: 49.2246,
    longitude: -123.1086,
    type: 'college',
    campus_type: 'main',
    enrollment: 21000,
    international_students: 8400,
    international_percentage: 40,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#E40046',
    website: 'https://langara.ca',
    aliases: ['Langara College'],
  },
  {
    id: 'douglas',
    name: 'Douglas College',
    short_name: 'Douglas',
    city: 'New Westminster',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V3L 5B2',
    latitude: 49.2043,
    longitude: -122.9108,
    type: 'college',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 10000,
    international_percentage: 40,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#FFD700',
    website: 'https://www.douglascollege.ca',
    aliases: ['Douglas College'],
  },
  {
    id: 'conestoga',
    name: 'Conestoga College',
    short_name: 'Conestoga',
    city: 'Kitchener',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N2G 4M4',
    latitude: 43.3895,
    longitude: -80.4043,
    type: 'college',
    campus_type: 'main',
    enrollment: 23000,
    international_students: 9200,
    international_percentage: 40,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://www.conestogac.on.ca',
    aliases: ['Conestoga College'],
  },
  {
    id: 'fanshawe',
    name: 'Fanshawe College',
    short_name: 'Fanshawe',
    city: 'London',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'N5Y 5R6',
    latitude: 42.9883,
    longitude: -81.2464,
    type: 'college',
    campus_type: 'main',
    enrollment: 21000,
    international_students: 8400,
    international_percentage: 40,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#FFD700',
    website: 'https://www.fanshawec.ca',
    aliases: ['Fanshawe College'],
  },
  {
    id: 'mohawk',
    name: 'Mohawk College',
    short_name: 'Mohawk',
    city: 'Hamilton',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L9C 1Y6',
    latitude: 43.2380,
    longitude: -79.8876,
    type: 'college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 4500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#7A003C',
    secondary_color: '#FFD700',
    website: 'https://www.mohawkcollege.ca',
    aliases: ['Mohawk College'],
  },
  {
    id: 'niagara',
    name: 'Niagara College',
    short_name: 'Niagara',
    city: 'Welland',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L3C 7L3',
    latitude: 42.9849,
    longitude: -79.2486,
    type: 'college',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 4800,
    international_percentage: 40,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://www.niagaracollege.ca',
    aliases: ['Niagara College'],
  },
  {
    id: 'algonquin',
    name: 'Algonquin College',
    short_name: 'Algonquin',
    city: 'Ottawa',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K2G 1V8',
    latitude: 45.3503,
    longitude: -75.7557,
    type: 'college',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 6000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#000000',
    website: 'https://www.algonquincollege.com',
    aliases: ['Algonquin College'],
  },
  {
    id: 'durham',
    name: 'Durham College',
    short_name: 'Durham',
    city: 'Oshawa',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L1H 7K4',
    latitude: 43.9452,
    longitude: -78.8951,
    type: 'college',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 4200,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://durhamcollege.ca',
    aliases: ['Durham College'],
  },
  {
    id: 'fleming',
    name: 'Fleming College',
    short_name: 'Fleming',
    city: 'Peterborough',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K9J 7B1',
    latitude: 44.3550,
    longitude: -78.3000,
    type: 'college',
    campus_type: 'main',
    enrollment: 6500,
    international_students: 1300,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://flemingcollege.ca',
    aliases: ['Fleming College'],
  },
  {
    id: 'georgian',
    name: 'Georgian College',
    short_name: 'Georgian',
    city: 'Barrie',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'L4M 3X9',
    latitude: 44.4103,
    longitude: -79.6832,
    type: 'college',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 3900,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.georgiancollege.ca',
    aliases: ['Georgian College'],
  },
  {
    id: 'loyalist',
    name: 'Loyalist College',
    short_name: 'Loyalist',
    city: 'Belleville',
    state: 'Ontario',
    country: 'CA',
    zip_code: 'K8N 5B9',
    latitude: 44.1628,
    longitude: -77.3832,
    type: 'college',
    campus_type: 'main',
    enrollment: 3000,
    international_students: 600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#C20430',
    website: 'https://www.loyalistcollege.com',
    aliases: ['Loyalist College'],
  },
  {
    id: 'nait',
    name: 'Northern Alberta Institute of Technology',
    short_name: 'NAIT',
    city: 'Edmonton',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T5G 2R1',
    latitude: 53.5695,
    longitude: -113.5054,
    type: 'college',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 2400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.nait.ca',
    aliases: ['NAIT'],
  },
  {
    id: 'sait',
    name: 'Southern Alberta Institute of Technology',
    short_name: 'SAIT',
    city: 'Calgary',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T2M 0L4',
    latitude: 51.0648,
    longitude: -114.0883,
    type: 'college',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 2200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#C20430',
    website: 'https://www.sait.ca',
    aliases: ['SAIT'],
  },
  {
    id: 'bow-valley',
    name: 'Bow Valley College',
    short_name: 'Bow Valley',
    city: 'Calgary',
    state: 'Alberta',
    country: 'CA',
    zip_code: 'T2G 4T8',
    latitude: 51.0447,
    longitude: -114.0719,
    type: 'college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 3000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFD700',
    website: 'https://bowvalleycollege.ca',
    aliases: ['Bow Valley College'],
  },
  {
    id: 'nscc',
    name: 'Nova Scotia Community College',
    short_name: 'NSCC',
    city: 'Halifax',
    state: 'Nova Scotia',
    country: 'CA',
    zip_code: 'B3J 2T5',
    latitude: 44.6488,
    longitude: -63.5752,
    type: 'college',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 2000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.nscc.ca',
    aliases: ['NSCC'],
  },
  {
    id: 'nbcc',
    name: 'New Brunswick Community College',
    short_name: 'NBCC',
    city: 'Fredericton',
    state: 'New Brunswick',
    country: 'CA',
    zip_code: 'E3C 2G2',
    latitude: 45.9500,
    longitude: -66.6333,
    type: 'college',
    campus_type: 'main',
    enrollment: 7000,
    international_students: 1400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#C20430',
    website: 'https://nbcc.ca',
    aliases: ['NBCC'],
  },
  {
    id: 'red-river',
    name: 'Red River College Polytechnic',
    short_name: 'RRC',
    city: 'Winnipeg',
    state: 'Manitoba',
    country: 'CA',
    zip_code: 'R3H 0J9',
    latitude: 49.8838,
    longitude: -97.1478,
    type: 'college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 3000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#C20430',
    secondary_color: '#000000',
    website: 'https://www.rrc.ca',
    aliases: ['RRC', 'Red River College'],
  },
  {
    id: 'sask-polytech',
    name: 'Saskatchewan Polytechnic',
    short_name: 'Sask Polytech',
    city: 'Saskatoon',
    state: 'Saskatchewan',
    country: 'CA',
    zip_code: 'S7K 3R5',
    latitude: 52.1358,
    longitude: -106.6403,
    type: 'college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 3000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#006341',
    website: 'https://saskpolytech.ca',
    aliases: ['Sask Polytech', 'SIAST'],
  },
  {
    id: 'vcc',
    name: 'Vancouver Community College',
    short_name: 'VCC',
    city: 'Vancouver',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V5T 4V5',
    latitude: 49.2620,
    longitude: -123.0917,
    type: 'college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 4500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.vcc.ca',
    aliases: ['VCC'],
  },
  {
    id: 'camosun',
    name: 'Camosun College',
    short_name: 'Camosun',
    city: 'Victoria',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V8P 5J2',
    latitude: 48.4562,
    longitude: -123.3447,
    type: 'college',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 2200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#006341',
    website: 'https://camosun.ca',
    aliases: ['Camosun College'],
  },
  {
    id: 'okanagan',
    name: 'Okanagan College',
    short_name: 'OC',
    city: 'Kelowna',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V1Y 4X8',
    latitude: 49.8868,
    longitude: -119.4967,
    type: 'college',
    campus_type: 'main',
    enrollment: 8000,
    international_students: 2400,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.okanagan.bc.ca',
    aliases: ['Okanagan College', 'OC'],
  },
  {
    id: 'selkirk',
    name: 'Selkirk College',
    short_name: 'Selkirk',
    city: 'Castlegar',
    state: 'British Columbia',
    country: 'CA',
    zip_code: 'V1N 4L3',
    latitude: 49.3256,
    longitude: -117.6593,
    type: 'college',
    campus_type: 'main',
    enrollment: 2500,
    international_students: 500,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#006341',
    website: 'https://selkirk.ca',
    aliases: ['Selkirk College'],
  },
  {
    id: 'cna',
    name: 'College of the North Atlantic',
    short_name: 'CNA',
    city: "St. John's",
    state: 'Newfoundland and Labrador',
    country: 'CA',
    zip_code: 'A1C 5P7',
    latitude: 47.5615,
    longitude: -52.7126,
    type: 'college',
    campus_type: 'main',
    enrollment: 8000,
    international_students: 1600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.cna.nl.ca',
    aliases: ['CNA'],
  },
  {
    id: 'dawson',
    name: 'Dawson College',
    short_name: 'Dawson',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H3Z 1A4',
    latitude: 45.4828,
    longitude: -73.5870,
    type: 'cegep',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 1650,
    international_percentage: 15,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.dawsoncollege.qc.ca',
    aliases: ['Dawson College'],
  },
  {
    id: 'vanier',
    name: 'Vanier College',
    short_name: 'Vanier',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H4L 3X9',
    latitude: 45.5336,
    longitude: -73.6727,
    type: 'cegep',
    campus_type: 'main',
    enrollment: 7000,
    international_students: 1050,
    international_percentage: 15,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#C20430',
    website: 'https://www.vaniercollege.qc.ca',
    aliases: ['Vanier College'],
  },
  {
    id: 'john-abbott',
    name: 'John Abbott College',
    short_name: 'JAC',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H9X 3L9',
    latitude: 45.4100,
    longitude: -73.9400,
    type: 'cegep',
    campus_type: 'main',
    enrollment: 7000,
    international_students: 700,
    international_percentage: 10,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#006341',
    website: 'https://www.johnabbott.qc.ca',
    aliases: ['JAC', 'John Abbott'],
  },
  {
    id: 'marianopolis',
    name: 'Marianopolis College',
    short_name: 'Marianopolis',
    city: 'Montreal',
    state: 'Quebec',
    country: 'CA',
    zip_code: 'H3Y 2T1',
    latitude: 45.4833,
    longitude: -73.5900,
    type: 'cegep',
    campus_type: 'main',
    enrollment: 2000,
    international_students: 400,
    international_percentage: 20,
    is_public: false,
    primary_color: '#003C71',
    secondary_color: '#FFD700',
    website: 'https://www.marianopolis.edu',
    aliases: ['Marianopolis College'],
  },
];

// Combine all Canadian institutions
export const ALL_CANADIAN_INSTITUTIONS: University[] = [
  ...CANADIAN_UNIVERSITIES,
  ...CANADIAN_COLLEGES,
];

export default ALL_CANADIAN_INSTITUTIONS;
