// ============================================================================
// MAJOR COMMUNITY COLLEGES
// Top community colleges with high international student enrollment
// ============================================================================

import { University } from './types';

// ============================================================================
// CALIFORNIA COMMUNITY COLLEGES (Top with International Students)
// ============================================================================
export const CALIFORNIA_CC: University[] = [
  {
    id: 'de-anza',
    name: 'De Anza College',
    short_name: 'De Anza',
    city: 'Cupertino',
    state: 'CA',
    zip_code: '95014',
    latitude: 37.3189,
    longitude: -122.0449,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 2500,
    is_public: true,
    primary_color: '#006747',
    secondary_color: '#FFB81C',
    website: 'https://www.deanza.edu',
    aliases: ['DAC'],
  },
  {
    id: 'foothill-college',
    name: 'Foothill College',
    short_name: 'Foothill',
    city: 'Los Altos Hills',
    state: 'CA',
    zip_code: '94022',
    latitude: 37.3614,
    longitude: -122.1278,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 1800,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#C8102E',
    website: 'https://www.foothill.edu',
    aliases: ['Owls'],
  },
  {
    id: 'santa-monica-college',
    name: 'Santa Monica College',
    short_name: 'SMC',
    city: 'Santa Monica',
    state: 'CA',
    zip_code: '90405',
    latitude: 34.0152,
    longitude: -118.4696,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 3000,
    is_public: true,
    primary_color: '#003B5C',
    secondary_color: '#FFFFFF',
    website: 'https://www.smc.edu',
    aliases: ['Corsairs'],
  },
  {
    id: 'pasadena-city-college',
    name: 'Pasadena City College',
    short_name: 'PCC',
    city: 'Pasadena',
    state: 'CA',
    zip_code: '91106',
    latitude: 34.1408,
    longitude: -118.1216,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 27000,
    international_students: 2200,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#000000',
    website: 'https://www.pasadena.edu',
    aliases: ['Lancers'],
  },
  {
    id: 'diablo-valley-college',
    name: 'Diablo Valley College',
    short_name: 'DVC',
    city: 'Pleasant Hill',
    state: 'CA',
    zip_code: '94523',
    latitude: 37.9535,
    longitude: -122.0565,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 1500,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#C8102E',
    website: 'https://www.dvc.edu',
    aliases: ['Vikings'],
  },
  {
    id: 'orange-coast-college',
    name: 'Orange Coast College',
    short_name: 'OCC',
    city: 'Costa Mesa',
    state: 'CA',
    zip_code: '92626',
    latitude: 33.6698,
    longitude: -117.9125,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 1200,
    is_public: true,
    primary_color: '#F47920',
    secondary_color: '#000000',
    website: 'https://www.orangecoastcollege.edu',
    aliases: ['Pirates'],
  },
  {
    id: 'irvine-valley-college',
    name: 'Irvine Valley College',
    short_name: 'IVC',
    city: 'Irvine',
    state: 'CA',
    zip_code: '92618',
    latitude: 33.6869,
    longitude: -117.8328,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 1000,
    is_public: true,
    primary_color: '#006B54',
    secondary_color: '#FFB81C',
    website: 'https://www.ivc.edu',
    aliases: ['Lasers'],
  },
  {
    id: 'city-college-sf',
    name: 'City College of San Francisco',
    short_name: 'CCSF',
    city: 'San Francisco',
    state: 'CA',
    zip_code: '94112',
    latitude: 37.7258,
    longitude: -122.4517,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 60000,
    international_students: 3500,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.ccsf.edu',
    aliases: ['Rams'],
  },
  {
    id: 'mt-sac',
    name: 'Mt. San Antonio College',
    short_name: 'Mt. SAC',
    city: 'Walnut',
    state: 'CA',
    zip_code: '91789',
    latitude: 34.0475,
    longitude: -117.8447,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 1800,
    is_public: true,
    primary_color: '#003B5C',
    secondary_color: '#C8102E',
    website: 'https://www.mtsac.edu',
    aliases: ['Mounties'],
  },
  {
    id: 'el-camino-college',
    name: 'El Camino College',
    short_name: 'El Camino',
    city: 'Torrance',
    state: 'CA',
    zip_code: '90506',
    latitude: 33.8673,
    longitude: -118.3523,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 1400,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#C8102E',
    website: 'https://www.elcamino.edu',
    aliases: ['Warriors'],
  },
  {
    id: 'santa-barbara-cc',
    name: 'Santa Barbara City College',
    short_name: 'SBCC',
    city: 'Santa Barbara',
    state: 'CA',
    zip_code: '93109',
    latitude: 34.4063,
    longitude: -119.6961,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 1200,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#C8102E',
    website: 'https://www.sbcc.edu',
    aliases: ['Vaqueros'],
  },
  {
    id: 'glendale-cc',
    name: 'Glendale Community College',
    short_name: 'GCC',
    city: 'Glendale',
    state: 'CA',
    zip_code: '91208',
    latitude: 34.1507,
    longitude: -118.2595,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 1800,
    is_public: true,
    primary_color: '#00205B',
    secondary_color: '#C8102E',
    website: 'https://www.glendale.edu',
    aliases: ['Vaqueros'],
  },
  {
    id: 'long-beach-cc',
    name: 'Long Beach City College',
    short_name: 'LBCC',
    city: 'Long Beach',
    state: 'CA',
    zip_code: '90808',
    latitude: 33.8028,
    longitude: -118.1603,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 1200,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#006B54',
    website: 'https://www.lbcc.edu',
    aliases: ['Vikings'],
  },
  {
    id: 'san-diego-mesa',
    name: 'San Diego Mesa College',
    short_name: 'Mesa College',
    city: 'San Diego',
    state: 'CA',
    zip_code: '92111',
    latitude: 32.8019,
    longitude: -117.1508,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 1100,
    is_public: true,
    primary_color: '#003B5C',
    secondary_color: '#C8102E',
    website: 'https://www.sdmesa.edu',
    aliases: ['Olympians'],
  },
  {
    id: 'san-diego-city-college',
    name: 'San Diego City College',
    short_name: 'City College SD',
    city: 'San Diego',
    state: 'CA',
    zip_code: '92101',
    latitude: 32.7208,
    longitude: -117.1603,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 900,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#808080',
    website: 'https://www.sdcity.edu',
    aliases: ['Knights'],
  },
  {
    id: 'san-diego-miramar',
    name: 'San Diego Miramar College',
    short_name: 'Miramar',
    city: 'San Diego',
    state: 'CA',
    zip_code: '92126',
    latitude: 32.9131,
    longitude: -117.1486,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 700,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.sdmiramar.edu',
    aliases: ['Jets'],
  },
  {
    id: 'los-angeles-cc',
    name: 'Los Angeles City College',
    short_name: 'LACC',
    city: 'Los Angeles',
    state: 'CA',
    zip_code: '90029',
    latitude: 34.0853,
    longitude: -118.2903,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 1400,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFB81C',
    website: 'https://www.lacitycollege.edu',
    aliases: ['Cubs'],
  },
  {
    id: 'pierce-college',
    name: 'Los Angeles Pierce College',
    short_name: 'Pierce',
    city: 'Woodland Hills',
    state: 'CA',
    zip_code: '91371',
    latitude: 34.1797,
    longitude: -118.5828,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 1100,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#FFFFFF',
    website: 'https://www.piercecollege.edu',
    aliases: ['Brahmas'],
  },
  {
    id: 'golden-west',
    name: 'Golden West College',
    short_name: 'Golden West',
    city: 'Huntington Beach',
    state: 'CA',
    zip_code: '92647',
    latitude: 33.7033,
    longitude: -117.9822,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.goldenwestcollege.edu',
    aliases: ['Rustlers'],
  },
  {
    id: 'cypress-college',
    name: 'Cypress College',
    short_name: 'Cypress',
    city: 'Cypress',
    state: 'CA',
    zip_code: '90630',
    latitude: 33.8194,
    longitude: -118.0392,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 750,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#808080',
    website: 'https://www.cypresscollege.edu',
    aliases: ['Chargers'],
  },
  {
    id: 'fullerton-college',
    name: 'Fullerton College',
    short_name: 'Fullerton CC',
    city: 'Fullerton',
    state: 'CA',
    zip_code: '92832',
    latitude: 33.8700,
    longitude: -117.9231,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 1100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#808080',
    website: 'https://www.fullcoll.edu',
    aliases: ['Hornets'],
  },
  {
    id: 'saddleback-college',
    name: 'Saddleback College',
    short_name: 'Saddleback',
    city: 'Mission Viejo',
    state: 'CA',
    zip_code: '92692',
    latitude: 33.5672,
    longitude: -117.6706,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 28000,
    international_students: 850,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#C8102E',
    website: 'https://www.saddleback.edu',
    aliases: ['Gauchos'],
  },
];

// ============================================================================
// OTHER STATE COMMUNITY COLLEGES
// ============================================================================
export const OTHER_CC: University[] = [
  // Texas
  {
    id: 'austin-cc',
    name: 'Austin Community College',
    short_name: 'ACC',
    city: 'Austin',
    state: 'TX',
    zip_code: '78752',
    latitude: 30.3322,
    longitude: -97.7031,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 41000,
    international_students: 2000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006B54',
    website: 'https://www.austincc.edu',
    aliases: ['Riverbats'],
  },
  {
    id: 'houston-cc',
    name: 'Houston Community College',
    short_name: 'HCC',
    city: 'Houston',
    state: 'TX',
    zip_code: '77002',
    latitude: 29.7604,
    longitude: -95.3698,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 55000,
    international_students: 3000,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#C8102E',
    website: 'https://www.hccs.edu',
    aliases: [],
  },
  {
    id: 'dallas-college',
    name: 'Dallas College',
    short_name: 'Dallas CC',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75243',
    latitude: 32.9000,
    longitude: -96.7500,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 70000,
    international_students: 3500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.dcccd.edu',
    aliases: ['DCCCD'],
  },
  {
    id: 'tarrant-county-college',
    name: 'Tarrant County College',
    short_name: 'TCC',
    city: 'Fort Worth',
    state: 'TX',
    zip_code: '76102',
    latitude: 32.7508,
    longitude: -97.3406,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 50000,
    international_students: 1800,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#006B54',
    website: 'https://www.tccd.edu',
    aliases: [],
  },
  // Florida
  {
    id: 'miami-dade',
    name: 'Miami Dade College',
    short_name: 'MDC',
    city: 'Miami',
    state: 'FL',
    zip_code: '33132',
    latitude: 25.7790,
    longitude: -80.1889,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 120000,
    international_students: 6000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.mdc.edu',
    aliases: ['Sharks'],
  },
  {
    id: 'broward-college',
    name: 'Broward College',
    short_name: 'Broward',
    city: 'Fort Lauderdale',
    state: 'FL',
    zip_code: '33301',
    latitude: 26.1197,
    longitude: -80.1400,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 63000,
    international_students: 2800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.broward.edu',
    aliases: ['Seahawks'],
  },
  {
    id: 'valencia-college',
    name: 'Valencia College',
    short_name: 'Valencia',
    city: 'Orlando',
    state: 'FL',
    zip_code: '32802',
    latitude: 28.5392,
    longitude: -81.3806,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 76000,
    international_students: 2400,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.valenciacollege.edu',
    aliases: [],
  },
  {
    id: 'palm-beach-state',
    name: 'Palm Beach State College',
    short_name: 'PBSC',
    city: 'Lake Worth',
    state: 'FL',
    zip_code: '33461',
    latitude: 26.6192,
    longitude: -80.0672,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 48000,
    international_students: 1800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006B54',
    website: 'https://www.palmbeachstate.edu',
    aliases: ['Panthers'],
  },
  // Virginia
  {
    id: 'nova-cc',
    name: 'Northern Virginia Community College',
    short_name: 'NOVA',
    city: 'Annandale',
    state: 'VA',
    zip_code: '22003',
    latitude: 38.8300,
    longitude: -77.1961,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 75000,
    international_students: 4500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.nvcc.edu',
    aliases: ['Nighthawks'],
  },
  // Washington
  {
    id: 'seattle-central',
    name: 'Seattle Central College',
    short_name: 'Seattle Central',
    city: 'Seattle',
    state: 'WA',
    zip_code: '98122',
    latitude: 47.6165,
    longitude: -122.3212,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 1500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#C8102E',
    website: 'https://seattlecentral.edu',
    aliases: [],
  },
  {
    id: 'bellevue-college',
    name: 'Bellevue College',
    short_name: 'BC',
    city: 'Bellevue',
    state: 'WA',
    zip_code: '98007',
    latitude: 47.5851,
    longitude: -122.1487,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 1200,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.bellevuecollege.edu',
    aliases: ['Bulldogs'],
  },
  {
    id: 'green-river-college',
    name: 'Green River College',
    short_name: 'Green River',
    city: 'Auburn',
    state: 'WA',
    zip_code: '98092',
    latitude: 47.3222,
    longitude: -122.2619,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 1100,
    is_public: true,
    primary_color: '#006B54',
    secondary_color: '#FFFFFF',
    website: 'https://www.greenriver.edu',
    aliases: ['Gators'],
  },
  // Illinois
  {
    id: 'harper-college',
    name: 'Harper College',
    short_name: 'Harper',
    city: 'Palatine',
    state: 'IL',
    zip_code: '60067',
    latitude: 42.0939,
    longitude: -88.0406,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.harpercollege.edu',
    aliases: ['Hawks'],
  },
  {
    id: 'college-of-dupage',
    name: 'College of DuPage',
    short_name: 'COD',
    city: 'Glen Ellyn',
    state: 'IL',
    zip_code: '60137',
    latitude: 41.8500,
    longitude: -88.0683,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 900,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.cod.edu',
    aliases: ['Chaparrals'],
  },
  // Arizona
  {
    id: 'mesa-cc',
    name: 'Mesa Community College',
    short_name: 'MCC',
    city: 'Mesa',
    state: 'AZ',
    zip_code: '85202',
    latitude: 33.4152,
    longitude: -111.8315,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 1000,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#000000',
    website: 'https://www.mesacc.edu',
    aliases: ['Thunderbirds'],
  },
  {
    id: 'scottsdale-cc',
    name: 'Scottsdale Community College',
    short_name: 'SCC',
    city: 'Scottsdale',
    state: 'AZ',
    zip_code: '85256',
    latitude: 33.4739,
    longitude: -111.9228,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 600,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#C8102E',
    website: 'https://www.scottsdalecc.edu',
    aliases: ['Artichokes'],
  },
  // New York (CUNY/SUNY CCs already in separate file)
  {
    id: 'suffolk-cc',
    name: 'Suffolk County Community College',
    short_name: 'Suffolk CC',
    city: 'Selden',
    state: 'NY',
    zip_code: '11784',
    latitude: 40.8600,
    longitude: -73.0350,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 920,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.sunysuffolk.edu',
    aliases: ['Sharks'],
  },
  {
    id: 'nassau-cc',
    name: 'Nassau Community College',
    short_name: 'Nassau CC',
    city: 'Garden City',
    state: 'NY',
    zip_code: '11530',
    latitude: 40.7423,
    longitude: -73.5893,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 850,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFC72C',
    website: 'https://www.ncc.edu',
    aliases: ['Lions'],
  },
  // Massachusetts
  {
    id: 'bunker-hill-cc',
    name: 'Bunker Hill Community College',
    short_name: 'BHCC',
    city: 'Boston',
    state: 'MA',
    zip_code: '02129',
    latitude: 42.3739,
    longitude: -71.0631,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 1200,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.bhcc.edu',
    aliases: ['Bulldogs'],
  },
  {
    id: 'middlesex-cc-ma',
    name: 'Middlesex Community College',
    short_name: 'MCC',
    city: 'Lowell',
    state: 'MA',
    zip_code: '01852',
    latitude: 42.6342,
    longitude: -71.3231,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 600,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFB81C',
    website: 'https://www.middlesex.mass.edu',
    aliases: [],
  },
];

export const ALL_COMMUNITY_COLLEGES = [...CALIFORNIA_CC, ...OTHER_CC];

export default ALL_COMMUNITY_COLLEGES;
