// ============================================================================
// NEW YORK UNIVERSITY SYSTEMS - SUNY (64) + CUNY (25)
// ============================================================================

import { University } from './types';

// ============================================================================
// SUNY SYSTEM - State University of New York (64 campuses)
// ============================================================================

export const SUNY_UNIVERSITIES: University[] = [
  // === SUNY University Centers (4) ===
  {
    id: 'suny-albany',
    name: 'University at Albany, SUNY',
    short_name: 'UAlbany',
    system_name: 'SUNY',
    city: 'Albany',
    state: 'NY',
    zip_code: '12222',
    latitude: 42.6859,
    longitude: -73.8241,
    type: 'university',
    campus_type: 'main',
    enrollment: 17292,
    international_students: 1800,
    is_public: true,
    primary_color: '#461660',
    secondary_color: '#FFB81C',
    website: 'https://www.albany.edu',
    aliases: ['SUNY Albany', 'Albany']
  },
  {
    id: 'suny-binghamton',
    name: 'Binghamton University, SUNY',
    short_name: 'Binghamton',
    system_name: 'SUNY',
    city: 'Binghamton',
    state: 'NY',
    zip_code: '13902',
    latitude: 42.0877,
    longitude: -75.9692,
    type: 'university',
    campus_type: 'main',
    enrollment: 18128,
    international_students: 3200,
    is_public: true,
    primary_color: '#005A43',
    secondary_color: '#FFFFFF',
    website: 'https://www.binghamton.edu',
    aliases: ['SUNY Binghamton', 'Bing']
  },
  {
    id: 'suny-buffalo',
    name: 'University at Buffalo, SUNY',
    short_name: 'UB',
    system_name: 'SUNY',
    city: 'Buffalo',
    state: 'NY',
    zip_code: '14260',
    latitude: 43.0008,
    longitude: -78.7875,
    type: 'university',
    campus_type: 'main',
    enrollment: 32347,
    international_students: 6500,
    is_public: true,
    primary_color: '#005BBB',
    secondary_color: '#FFFFFF',
    website: 'https://www.buffalo.edu',
    aliases: ['SUNY Buffalo', 'Buffalo']
  },
  {
    id: 'suny-stony-brook',
    name: 'Stony Brook University, SUNY',
    short_name: 'Stony Brook',
    system_name: 'SUNY',
    city: 'Stony Brook',
    state: 'NY',
    zip_code: '11794',
    latitude: 40.9126,
    longitude: -73.1234,
    type: 'university',
    campus_type: 'main',
    enrollment: 26782,
    international_students: 5400,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#6E6E6E',
    website: 'https://www.stonybrook.edu',
    aliases: ['SUNY Stony Brook', 'SBU']
  },

  // === SUNY University Colleges (13) ===
  {
    id: 'suny-brockport',
    name: 'SUNY Brockport',
    short_name: 'Brockport',
    system_name: 'SUNY',
    city: 'Brockport',
    state: 'NY',
    zip_code: '14420',
    latitude: 43.2127,
    longitude: -77.9375,
    type: 'university',
    campus_type: 'main',
    enrollment: 7200,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFB81C',
    website: 'https://www.brockport.edu'
  },
  {
    id: 'suny-buffalo-state',
    name: 'Buffalo State University',
    short_name: 'Buffalo State',
    system_name: 'SUNY',
    city: 'Buffalo',
    state: 'NY',
    zip_code: '14222',
    latitude: 42.9314,
    longitude: -78.8817,
    type: 'university',
    campus_type: 'main',
    enrollment: 7400,
    is_public: true,
    primary_color: '#FF6600',
    secondary_color: '#000000',
    website: 'https://www.buffalostate.edu'
  },
  {
    id: 'suny-cortland',
    name: 'SUNY Cortland',
    short_name: 'Cortland',
    system_name: 'SUNY',
    city: 'Cortland',
    state: 'NY',
    zip_code: '13045',
    latitude: 42.5918,
    longitude: -76.1813,
    type: 'university',
    campus_type: 'main',
    enrollment: 6500,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.cortland.edu'
  },
  {
    id: 'suny-fredonia',
    name: 'SUNY Fredonia',
    short_name: 'Fredonia',
    system_name: 'SUNY',
    city: 'Fredonia',
    state: 'NY',
    zip_code: '14063',
    latitude: 42.4400,
    longitude: -79.3317,
    type: 'university',
    campus_type: 'main',
    enrollment: 4000,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFFFFF',
    website: 'https://www.fredonia.edu'
  },
  {
    id: 'suny-geneseo',
    name: 'SUNY Geneseo',
    short_name: 'Geneseo',
    system_name: 'SUNY',
    city: 'Geneseo',
    state: 'NY',
    zip_code: '14454',
    latitude: 42.7959,
    longitude: -77.8197,
    type: 'university',
    campus_type: 'main',
    enrollment: 4800,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFD700',
    website: 'https://www.geneseo.edu'
  },
  {
    id: 'suny-new-paltz',
    name: 'SUNY New Paltz',
    short_name: 'New Paltz',
    system_name: 'SUNY',
    city: 'New Paltz',
    state: 'NY',
    zip_code: '12561',
    latitude: 41.7470,
    longitude: -74.0835,
    type: 'university',
    campus_type: 'main',
    enrollment: 7100,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FF9900',
    website: 'https://www.newpaltz.edu'
  },
  {
    id: 'suny-old-westbury',
    name: 'SUNY Old Westbury',
    short_name: 'Old Westbury',
    system_name: 'SUNY',
    city: 'Old Westbury',
    state: 'NY',
    zip_code: '11568',
    latitude: 40.7887,
    longitude: -73.5540,
    type: 'university',
    campus_type: 'main',
    enrollment: 4500,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFD700',
    website: 'https://www.oldwestbury.edu'
  },
  {
    id: 'suny-oneonta',
    name: 'SUNY Oneonta',
    short_name: 'Oneonta',
    system_name: 'SUNY',
    city: 'Oneonta',
    state: 'NY',
    zip_code: '13820',
    latitude: 42.4667,
    longitude: -75.0647,
    type: 'university',
    campus_type: 'main',
    enrollment: 6000,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.oneonta.edu'
  },
  {
    id: 'suny-oswego',
    name: 'SUNY Oswego',
    short_name: 'Oswego',
    system_name: 'SUNY',
    city: 'Oswego',
    state: 'NY',
    zip_code: '13126',
    latitude: 43.4514,
    longitude: -76.5454,
    type: 'university',
    campus_type: 'main',
    enrollment: 7400,
    is_public: true,
    primary_color: '#006747',
    secondary_color: '#FFD100',
    website: 'https://www.oswego.edu'
  },
  {
    id: 'suny-plattsburgh',
    name: 'SUNY Plattsburgh',
    short_name: 'Plattsburgh',
    system_name: 'SUNY',
    city: 'Plattsburgh',
    state: 'NY',
    zip_code: '12901',
    latitude: 44.6948,
    longitude: -73.4740,
    type: 'university',
    campus_type: 'main',
    enrollment: 5200,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.plattsburgh.edu'
  },
  {
    id: 'suny-potsdam',
    name: 'SUNY Potsdam',
    short_name: 'Potsdam',
    system_name: 'SUNY',
    city: 'Potsdam',
    state: 'NY',
    zip_code: '13676',
    latitude: 44.6695,
    longitude: -75.0025,
    type: 'university',
    campus_type: 'main',
    enrollment: 3000,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#808080',
    website: 'https://www.potsdam.edu'
  },
  {
    id: 'suny-purchase',
    name: 'Purchase College, SUNY',
    short_name: 'Purchase',
    system_name: 'SUNY',
    city: 'Purchase',
    state: 'NY',
    zip_code: '10577',
    latitude: 41.0465,
    longitude: -73.7068,
    type: 'university',
    campus_type: 'main',
    enrollment: 3200,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.purchase.edu'
  },
  {
    id: 'suny-empire-state',
    name: 'SUNY Empire State University',
    short_name: 'Empire State',
    system_name: 'SUNY',
    city: 'Saratoga Springs',
    state: 'NY',
    zip_code: '12866',
    latitude: 43.0831,
    longitude: -73.7846,
    type: 'university',
    campus_type: 'online',
    enrollment: 10000,
    is_public: true,
    primary_color: '#002D72',
    secondary_color: '#F7941D',
    website: 'https://www.sunyempire.edu'
  },

  // === SUNY Technology Colleges (7) ===
  {
    id: 'suny-alfred-state',
    name: 'Alfred State College',
    short_name: 'Alfred State',
    system_name: 'SUNY',
    city: 'Alfred',
    state: 'NY',
    zip_code: '14802',
    latitude: 42.2543,
    longitude: -77.7910,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 3700,
    is_public: true,
    primary_color: '#003594',
    secondary_color: '#FFB81C',
    website: 'https://www.alfredstate.edu'
  },
  {
    id: 'suny-canton',
    name: 'SUNY Canton',
    short_name: 'Canton',
    system_name: 'SUNY',
    city: 'Canton',
    state: 'NY',
    zip_code: '13617',
    latitude: 44.5959,
    longitude: -75.1691,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 3200,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFD700',
    website: 'https://www.canton.edu'
  },
  {
    id: 'suny-cobleskill',
    name: 'SUNY Cobleskill',
    short_name: 'Cobleskill',
    system_name: 'SUNY',
    city: 'Cobleskill',
    state: 'NY',
    zip_code: '12043',
    latitude: 42.6772,
    longitude: -74.4857,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 2300,
    is_public: true,
    primary_color: '#FF6600',
    secondary_color: '#000000',
    website: 'https://www.cobleskill.edu'
  },
  {
    id: 'suny-delhi',
    name: 'SUNY Delhi',
    short_name: 'Delhi',
    system_name: 'SUNY',
    city: 'Delhi',
    state: 'NY',
    zip_code: '13753',
    latitude: 42.2779,
    longitude: -74.9158,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 3200,
    is_public: true,
    primary_color: '#006633',
    secondary_color: '#FFD700',
    website: 'https://www.delhi.edu'
  },
  {
    id: 'suny-farmingdale',
    name: 'Farmingdale State College',
    short_name: 'Farmingdale',
    system_name: 'SUNY',
    city: 'Farmingdale',
    state: 'NY',
    zip_code: '11735',
    latitude: 40.7526,
    longitude: -73.4304,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 10000,
    is_public: true,
    primary_color: '#006400',
    secondary_color: '#FFD700',
    website: 'https://www.farmingdale.edu'
  },
  {
    id: 'suny-morrisville',
    name: 'SUNY Morrisville',
    short_name: 'Morrisville',
    system_name: 'SUNY',
    city: 'Morrisville',
    state: 'NY',
    zip_code: '13408',
    latitude: 42.8987,
    longitude: -75.6408,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 2800,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFB81C',
    website: 'https://www.morrisville.edu'
  },
  {
    id: 'suny-maritime',
    name: 'SUNY Maritime College',
    short_name: 'Maritime',
    system_name: 'SUNY',
    city: 'Throggs Neck',
    state: 'NY',
    zip_code: '10465',
    latitude: 40.8076,
    longitude: -73.7996,
    type: 'technical_college',
    campus_type: 'main',
    enrollment: 1800,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.sunymaritime.edu'
  },

  // === SUNY Community Colleges (30) ===
  {
    id: 'suny-adirondack',
    name: 'SUNY Adirondack',
    short_name: 'Adirondack CC',
    system_name: 'SUNY',
    city: 'Queensbury',
    state: 'NY',
    zip_code: '12804',
    latitude: 43.3548,
    longitude: -73.6793,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 3500,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFB81C',
    website: 'https://www.sunyacc.edu'
  },
  {
    id: 'suny-broome',
    name: 'SUNY Broome Community College',
    short_name: 'Broome CC',
    system_name: 'SUNY',
    city: 'Binghamton',
    state: 'NY',
    zip_code: '13902',
    latitude: 42.1276,
    longitude: -75.9701,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 6000,
    is_public: true,
    primary_color: '#006747',
    secondary_color: '#FFD100',
    website: 'https://www.sunybroome.edu'
  },
  {
    id: 'suny-cayuga',
    name: 'Cayuga Community College',
    short_name: 'Cayuga CC',
    system_name: 'SUNY',
    city: 'Auburn',
    state: 'NY',
    zip_code: '13021',
    latitude: 42.9317,
    longitude: -76.5661,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 3000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.cayuga-cc.edu'
  },
  {
    id: 'suny-clinton',
    name: 'Clinton Community College',
    short_name: 'Clinton CC',
    system_name: 'SUNY',
    city: 'Plattsburgh',
    state: 'NY',
    zip_code: '12901',
    latitude: 44.6748,
    longitude: -73.4540,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 1800,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.clinton.edu'
  },
  {
    id: 'suny-columbia-greene',
    name: 'Columbia-Greene Community College',
    short_name: 'Columbia-Greene CC',
    system_name: 'SUNY',
    city: 'Hudson',
    state: 'NY',
    zip_code: '12534',
    latitude: 42.2326,
    longitude: -73.7540,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 1500,
    is_public: true,
    primary_color: '#006341',
    secondary_color: '#FFFFFF',
    website: 'https://www.sunycgcc.edu'
  },
  {
    id: 'suny-corning',
    name: 'Corning Community College',
    short_name: 'Corning CC',
    system_name: 'SUNY',
    city: 'Corning',
    state: 'NY',
    zip_code: '14830',
    latitude: 42.1443,
    longitude: -77.0547,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 4500,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#000000',
    website: 'https://www.corning-cc.edu'
  },
  {
    id: 'suny-dutchess',
    name: 'Dutchess Community College',
    short_name: 'DCC',
    system_name: 'SUNY',
    city: 'Poughkeepsie',
    state: 'NY',
    zip_code: '12601',
    latitude: 41.6865,
    longitude: -73.8968,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 8500,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFD700',
    website: 'https://www.sunydutchess.edu'
  },
  {
    id: 'suny-erie',
    name: 'Erie Community College',
    short_name: 'ECC',
    system_name: 'SUNY',
    city: 'Buffalo',
    state: 'NY',
    zip_code: '14221',
    latitude: 42.9761,
    longitude: -78.8014,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 11000,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFD700',
    website: 'https://www.ecc.edu'
  },
  {
    id: 'suny-fashion-institute',
    name: 'Fashion Institute of Technology',
    short_name: 'FIT',
    system_name: 'SUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10001',
    latitude: 40.7465,
    longitude: -73.9943,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 8500,
    international_students: 1200,
    is_public: true,
    primary_color: '#CC0066',
    secondary_color: '#000000',
    website: 'https://www.fitnyc.edu',
    aliases: ['FIT NYC']
  },
  {
    id: 'suny-finger-lakes',
    name: 'Finger Lakes Community College',
    short_name: 'FLCC',
    system_name: 'SUNY',
    city: 'Canandaigua',
    state: 'NY',
    zip_code: '14424',
    latitude: 42.8676,
    longitude: -77.2836,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 5500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006633',
    website: 'https://www.flcc.edu'
  },
  {
    id: 'suny-fulton-montgomery',
    name: 'Fulton-Montgomery Community College',
    short_name: 'FMCC',
    system_name: 'SUNY',
    city: 'Johnstown',
    state: 'NY',
    zip_code: '12095',
    latitude: 43.0062,
    longitude: -74.3632,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 2500,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.fmcc.suny.edu'
  },
  {
    id: 'suny-genesee',
    name: 'Genesee Community College',
    short_name: 'GCC',
    system_name: 'SUNY',
    city: 'Batavia',
    state: 'NY',
    zip_code: '14020',
    latitude: 42.9995,
    longitude: -78.1686,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 5500,
    is_public: true,
    primary_color: '#006633',
    secondary_color: '#FFD700',
    website: 'https://www.genesee.edu'
  },
  {
    id: 'suny-herkimer',
    name: 'Herkimer College',
    short_name: 'Herkimer',
    system_name: 'SUNY',
    city: 'Herkimer',
    state: 'NY',
    zip_code: '13350',
    latitude: 43.0184,
    longitude: -74.9758,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 2800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.herkimer.edu'
  },
  {
    id: 'suny-hudson-valley',
    name: 'Hudson Valley Community College',
    short_name: 'HVCC',
    system_name: 'SUNY',
    city: 'Troy',
    state: 'NY',
    zip_code: '12180',
    latitude: 42.6978,
    longitude: -73.6587,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 10000,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#CC0000',
    website: 'https://www.hvcc.edu'
  },
  {
    id: 'suny-jamestown',
    name: 'Jamestown Community College',
    short_name: 'JCC',
    system_name: 'SUNY',
    city: 'Jamestown',
    state: 'NY',
    zip_code: '14701',
    latitude: 42.0773,
    longitude: -79.2353,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 3200,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.sunyjcc.edu'
  },
  {
    id: 'suny-jefferson',
    name: 'Jefferson Community College',
    short_name: 'Jefferson CC',
    system_name: 'SUNY',
    city: 'Watertown',
    state: 'NY',
    zip_code: '13601',
    latitude: 43.9784,
    longitude: -75.9132,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 3000,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.sunyjefferson.edu'
  },
  {
    id: 'suny-mohawk-valley',
    name: 'Mohawk Valley Community College',
    short_name: 'MVCC',
    system_name: 'SUNY',
    city: 'Utica',
    state: 'NY',
    zip_code: '13501',
    latitude: 43.1009,
    longitude: -75.2327,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 5500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.mvcc.edu'
  },
  {
    id: 'suny-monroe',
    name: 'Monroe Community College',
    short_name: 'MCC',
    system_name: 'SUNY',
    city: 'Rochester',
    state: 'NY',
    zip_code: '14623',
    latitude: 43.0848,
    longitude: -77.6412,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 12000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.monroecc.edu'
  },
  {
    id: 'suny-nassau',
    name: 'Nassau Community College',
    short_name: 'Nassau CC',
    system_name: 'SUNY',
    city: 'Garden City',
    state: 'NY',
    zip_code: '11530',
    latitude: 40.7279,
    longitude: -73.5990,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 18000,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFD700',
    website: 'https://www.ncc.edu'
  },
  {
    id: 'suny-niagara',
    name: 'Niagara County Community College',
    short_name: 'NCCC',
    system_name: 'SUNY',
    city: 'Sanborn',
    state: 'NY',
    zip_code: '14132',
    latitude: 43.1412,
    longitude: -78.8706,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 5500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.niagaracc.suny.edu'
  },
  {
    id: 'suny-north-country',
    name: 'North Country Community College',
    short_name: 'NCCC',
    system_name: 'SUNY',
    city: 'Saranac Lake',
    state: 'NY',
    zip_code: '12983',
    latitude: 44.3276,
    longitude: -74.1307,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 1500,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.nccc.edu'
  },
  {
    id: 'suny-onondaga',
    name: 'Onondaga Community College',
    short_name: 'OCC',
    system_name: 'SUNY',
    city: 'Syracuse',
    state: 'NY',
    zip_code: '13215',
    latitude: 43.0081,
    longitude: -76.1474,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 9000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.sunyocc.edu'
  },
  {
    id: 'suny-orange',
    name: 'SUNY Orange',
    short_name: 'Orange CC',
    system_name: 'SUNY',
    city: 'Middletown',
    state: 'NY',
    zip_code: '10940',
    latitude: 41.4459,
    longitude: -74.4229,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 6000,
    is_public: true,
    primary_color: '#FF6600',
    secondary_color: '#000000',
    website: 'https://www.sunyorange.edu'
  },
  {
    id: 'suny-rockland',
    name: 'Rockland Community College',
    short_name: 'RCC',
    system_name: 'SUNY',
    city: 'Suffern',
    state: 'NY',
    zip_code: '10901',
    latitude: 41.1162,
    longitude: -74.1235,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 6500,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.sunyrockland.edu'
  },
  {
    id: 'suny-schenectady',
    name: 'Schenectady County Community College',
    short_name: 'SCCC',
    system_name: 'SUNY',
    city: 'Schenectady',
    state: 'NY',
    zip_code: '12305',
    latitude: 42.8142,
    longitude: -73.9396,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 4500,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.sunysccc.edu'
  },
  {
    id: 'suny-suffolk',
    name: 'Suffolk County Community College',
    short_name: 'Suffolk CC',
    system_name: 'SUNY',
    city: 'Selden',
    state: 'NY',
    zip_code: '11784',
    latitude: 40.8648,
    longitude: -73.0462,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 26000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.sunysuffolk.edu'
  },
  {
    id: 'suny-sullivan',
    name: 'Sullivan County Community College',
    short_name: 'Sullivan CC',
    system_name: 'SUNY',
    city: 'Loch Sheldrake',
    state: 'NY',
    zip_code: '12759',
    latitude: 41.7729,
    longitude: -74.6482,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 1500,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.sunysullivan.edu'
  },
  {
    id: 'suny-tompkins-cortland',
    name: 'Tompkins Cortland Community College',
    short_name: 'TC3',
    system_name: 'SUNY',
    city: 'Dryden',
    state: 'NY',
    zip_code: '13053',
    latitude: 42.4651,
    longitude: -76.2949,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 4000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.tompkinscortland.edu'
  },
  {
    id: 'suny-ulster',
    name: 'SUNY Ulster',
    short_name: 'Ulster CC',
    system_name: 'SUNY',
    city: 'Stone Ridge',
    state: 'NY',
    zip_code: '12484',
    latitude: 41.8640,
    longitude: -74.1265,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 3000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#006633',
    website: 'https://www.sunyulster.edu'
  },
  {
    id: 'suny-westchester',
    name: 'Westchester Community College',
    short_name: 'WCC',
    system_name: 'SUNY',
    city: 'Valhalla',
    state: 'NY',
    zip_code: '10595',
    latitude: 41.0837,
    longitude: -73.7712,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 12000,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#006633',
    website: 'https://www.sunywcc.edu'
  },

  // === SUNY Specialized Institutions ===
  {
    id: 'suny-downstate',
    name: 'SUNY Downstate Health Sciences University',
    short_name: 'Downstate',
    system_name: 'SUNY',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11203',
    latitude: 40.6553,
    longitude: -73.9450,
    type: 'university',
    campus_type: 'main',
    enrollment: 1900,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.downstate.edu'
  },
  {
    id: 'suny-upstate',
    name: 'SUNY Upstate Medical University',
    short_name: 'Upstate',
    system_name: 'SUNY',
    city: 'Syracuse',
    state: 'NY',
    zip_code: '13210',
    latitude: 43.0422,
    longitude: -76.1387,
    type: 'university',
    campus_type: 'main',
    enrollment: 1700,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FF9900',
    website: 'https://www.upstate.edu'
  },
  {
    id: 'suny-optometry',
    name: 'SUNY College of Optometry',
    short_name: 'SUNY Optometry',
    system_name: 'SUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10036',
    latitude: 40.7549,
    longitude: -73.9840,
    type: 'university',
    campus_type: 'main',
    enrollment: 400,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.sunyopt.edu'
  },
  {
    id: 'suny-esf',
    name: 'SUNY College of Environmental Science and Forestry',
    short_name: 'SUNY ESF',
    system_name: 'SUNY',
    city: 'Syracuse',
    state: 'NY',
    zip_code: '13210',
    latitude: 43.0361,
    longitude: -76.1329,
    type: 'university',
    campus_type: 'main',
    enrollment: 2200,
    is_public: true,
    primary_color: '#00563F',
    secondary_color: '#FFD700',
    website: 'https://www.esf.edu',
    aliases: ['ESF', 'Environmental Science Forestry']
  },
  {
    id: 'suny-poly',
    name: 'SUNY Polytechnic Institute',
    short_name: 'SUNY Poly',
    system_name: 'SUNY',
    city: 'Utica',
    state: 'NY',
    zip_code: '13502',
    latitude: 43.0962,
    longitude: -75.2330,
    type: 'university',
    campus_type: 'main',
    enrollment: 2800,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFD700',
    website: 'https://www.sunypoly.edu'
  },
  {
    id: 'suny-korea',
    name: 'SUNY Korea',
    short_name: 'SUNY Korea',
    system_name: 'SUNY',
    city: 'Incheon',
    state: 'International',
    zip_code: '21985',
    latitude: 37.3850,
    longitude: 126.6564,
    type: 'university',
    campus_type: 'branch',
    enrollment: 800,
    international_students: 800,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#6E6E6E',
    website: 'https://www.sunykorea.ac.kr'
  }
];

// ============================================================================
// CUNY SYSTEM - City University of New York (25 institutions)
// ============================================================================

export const CUNY_UNIVERSITIES: University[] = [
  // === CUNY Senior Colleges (11) ===
  {
    id: 'cuny-baruch',
    name: 'Baruch College, CUNY',
    short_name: 'Baruch',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10010',
    latitude: 40.7404,
    longitude: -73.9836,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 2500,
    is_public: true,
    primary_color: '#003DA5',
    secondary_color: '#F0AB00',
    website: 'https://www.baruch.cuny.edu',
    aliases: ['Baruch College']
  },
  {
    id: 'cuny-brooklyn',
    name: 'Brooklyn College, CUNY',
    short_name: 'Brooklyn College',
    system_name: 'CUNY',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11210',
    latitude: 40.6310,
    longitude: -73.9524,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 1800,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#FFD700',
    website: 'https://www.brooklyn.cuny.edu'
  },
  {
    id: 'cuny-city-college',
    name: 'The City College of New York',
    short_name: 'City College',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10031',
    latitude: 40.8200,
    longitude: -73.9493,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 1600,
    is_public: true,
    primary_color: '#660099',
    secondary_color: '#FFD700',
    website: 'https://www.ccny.cuny.edu',
    aliases: ['CCNY']
  },
  {
    id: 'cuny-hunter',
    name: 'Hunter College, CUNY',
    short_name: 'Hunter',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10065',
    latitude: 40.7686,
    longitude: -73.9647,
    type: 'university',
    campus_type: 'main',
    enrollment: 23000,
    international_students: 2100,
    is_public: true,
    primary_color: '#660099',
    secondary_color: '#FFD700',
    website: 'https://www.hunter.cuny.edu',
    aliases: ['Hunter College']
  },
  {
    id: 'cuny-john-jay',
    name: 'John Jay College of Criminal Justice',
    short_name: 'John Jay',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10019',
    latitude: 40.7704,
    longitude: -73.9881,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 1200,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#000000',
    website: 'https://www.jjay.cuny.edu'
  },
  {
    id: 'cuny-lehman',
    name: 'Lehman College, CUNY',
    short_name: 'Lehman',
    system_name: 'CUNY',
    city: 'Bronx',
    state: 'NY',
    zip_code: '10468',
    latitude: 40.8731,
    longitude: -73.8941,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 900,
    is_public: true,
    primary_color: '#FFD700',
    secondary_color: '#000000',
    website: 'https://www.lehman.cuny.edu'
  },
  {
    id: 'cuny-medgar-evers',
    name: 'Medgar Evers College, CUNY',
    short_name: 'Medgar Evers',
    system_name: 'CUNY',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11225',
    latitude: 40.6669,
    longitude: -73.9573,
    type: 'university',
    campus_type: 'main',
    enrollment: 7000,
    is_public: true,
    primary_color: '#006400',
    secondary_color: '#FFD700',
    website: 'https://www.mec.cuny.edu'
  },
  {
    id: 'cuny-queens',
    name: 'Queens College, CUNY',
    short_name: 'Queens College',
    system_name: 'CUNY',
    city: 'Queens',
    state: 'NY',
    zip_code: '11367',
    latitude: 40.7362,
    longitude: -73.8203,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 1900,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#003366',
    website: 'https://www.qc.cuny.edu'
  },
  {
    id: 'cuny-college-si',
    name: 'College of Staten Island, CUNY',
    short_name: 'CSI',
    system_name: 'CUNY',
    city: 'Staten Island',
    state: 'NY',
    zip_code: '10314',
    latitude: 40.6019,
    longitude: -74.1502,
    type: 'university',
    campus_type: 'main',
    enrollment: 13000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.csi.cuny.edu'
  },
  {
    id: 'cuny-york',
    name: 'York College, CUNY',
    short_name: 'York',
    system_name: 'CUNY',
    city: 'Jamaica',
    state: 'NY',
    zip_code: '11451',
    latitude: 40.7014,
    longitude: -73.7967,
    type: 'university',
    campus_type: 'main',
    enrollment: 8000,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#000000',
    website: 'https://www.york.cuny.edu'
  },
  {
    id: 'cuny-nycct',
    name: 'New York City College of Technology',
    short_name: 'City Tech',
    system_name: 'CUNY',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11201',
    latitude: 40.6955,
    longitude: -73.9876,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 1500,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#FFD700',
    website: 'https://www.citytech.cuny.edu',
    aliases: ['City Tech', 'NYCCT']
  },

  // === CUNY Community Colleges (7) ===
  {
    id: 'cuny-bmcc',
    name: 'Borough of Manhattan Community College',
    short_name: 'BMCC',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10007',
    latitude: 40.7183,
    longitude: -74.0118,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 2800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.bmcc.cuny.edu'
  },
  {
    id: 'cuny-bronx-cc',
    name: 'Bronx Community College',
    short_name: 'BCC',
    system_name: 'CUNY',
    city: 'Bronx',
    state: 'NY',
    zip_code: '10453',
    latitude: 40.8576,
    longitude: -73.9116,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 11000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.bcc.cuny.edu'
  },
  {
    id: 'cuny-hostos',
    name: 'Hostos Community College',
    short_name: 'Hostos',
    system_name: 'CUNY',
    city: 'Bronx',
    state: 'NY',
    zip_code: '10451',
    latitude: 40.8170,
    longitude: -73.9267,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 7000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.hostos.cuny.edu'
  },
  {
    id: 'cuny-kingsborough',
    name: 'Kingsborough Community College',
    short_name: 'KCC',
    system_name: 'CUNY',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11235',
    latitude: 40.5780,
    longitude: -73.9346,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.kbcc.cuny.edu'
  },
  {
    id: 'cuny-laguardia',
    name: 'LaGuardia Community College',
    short_name: 'LaGuardia',
    system_name: 'CUNY',
    city: 'Long Island City',
    state: 'NY',
    zip_code: '11101',
    latitude: 40.7439,
    longitude: -73.9357,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 2000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.laguardia.cuny.edu'
  },
  {
    id: 'cuny-queensborough',
    name: 'Queensborough Community College',
    short_name: 'QCC',
    system_name: 'CUNY',
    city: 'Bayside',
    state: 'NY',
    zip_code: '11364',
    latitude: 40.7558,
    longitude: -73.7564,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 15000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.qcc.cuny.edu'
  },
  {
    id: 'cuny-guttman',
    name: 'Guttman Community College',
    short_name: 'Guttman',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10019',
    latitude: 40.7614,
    longitude: -73.9876,
    type: 'community_college',
    campus_type: 'main',
    enrollment: 1000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.guttman.cuny.edu'
  },

  // === CUNY Graduate and Professional Schools ===
  {
    id: 'cuny-graduate-center',
    name: 'The Graduate Center, CUNY',
    short_name: 'Graduate Center',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10016',
    latitude: 40.7486,
    longitude: -73.9840,
    type: 'university',
    campus_type: 'main',
    enrollment: 4500,
    international_students: 600,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.gc.cuny.edu'
  },
  {
    id: 'cuny-law',
    name: 'CUNY School of Law',
    short_name: 'CUNY Law',
    system_name: 'CUNY',
    city: 'Long Island City',
    state: 'NY',
    zip_code: '11101',
    latitude: 40.7447,
    longitude: -73.9363,
    type: 'university',
    campus_type: 'main',
    enrollment: 450,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.law.cuny.edu'
  },
  {
    id: 'cuny-sph',
    name: 'CUNY School of Public Health',
    short_name: 'CUNY SPH',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10027',
    latitude: 40.8181,
    longitude: -73.9495,
    type: 'university',
    campus_type: 'main',
    enrollment: 700,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://sph.cuny.edu'
  },
  {
    id: 'cuny-sjc',
    name: 'CUNY School of Professional Studies',
    short_name: 'CUNY SPS',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10010',
    latitude: 40.7398,
    longitude: -73.9834,
    type: 'university',
    campus_type: 'online',
    enrollment: 4000,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://sps.cuny.edu'
  },
  {
    id: 'cuny-journalism',
    name: 'Craig Newmark Graduate School of Journalism at CUNY',
    short_name: 'CUNY Journalism',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10018',
    latitude: 40.7550,
    longitude: -73.9884,
    type: 'university',
    campus_type: 'main',
    enrollment: 250,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.journalism.cuny.edu'
  },
  {
    id: 'cuny-labor',
    name: 'CUNY School of Labor and Urban Studies',
    short_name: 'CUNY SLU',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10001',
    latitude: 40.7505,
    longitude: -73.9934,
    type: 'university',
    campus_type: 'main',
    enrollment: 300,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://slu.cuny.edu'
  },
  {
    id: 'cuny-macaulay',
    name: 'Macaulay Honors College',
    short_name: 'Macaulay',
    system_name: 'CUNY',
    city: 'New York',
    state: 'NY',
    zip_code: '10010',
    latitude: 40.7400,
    longitude: -73.9830,
    type: 'university',
    campus_type: 'main',
    enrollment: 2400,
    is_public: true,
    primary_color: '#660099',
    secondary_color: '#FFD700',
    website: 'https://macaulay.cuny.edu'
  }
];

// Combined NY Universities
export const NY_UNIVERSITIES: University[] = [
  ...SUNY_UNIVERSITIES,
  ...CUNY_UNIVERSITIES
];
