// ============================================================================
// MAJOR STATE UNIVERSITY SYSTEMS
// Big Ten, SEC, Pac-12, ACC, Big 12, and other major state schools
// ============================================================================

import { University } from './types';

// ============================================================================
// BIG TEN CONFERENCE UNIVERSITIES
// ============================================================================
export const BIG_TEN: University[] = [
  {
    id: 'umich',
    name: 'University of Michigan',
    short_name: 'Michigan',
    system_name: 'University of Michigan',
    city: 'Ann Arbor',
    state: 'MI',
    zip_code: '48109',
    latitude: 42.2780,
    longitude: -83.7382,
    type: 'university',
    campus_type: 'main',
    enrollment: 47907,
    international_students: 7500,
    is_public: true,
    primary_color: '#00274C',
    secondary_color: '#FFCB05',
    website: 'https://www.umich.edu',
    aliases: ['UMich', 'Wolverines', 'Michigan'],
  },
  {
    id: 'umich-dearborn',
    name: 'University of Michigan-Dearborn',
    short_name: 'UM-Dearborn',
    system_name: 'University of Michigan',
    city: 'Dearborn',
    state: 'MI',
    zip_code: '48128',
    latitude: 42.3187,
    longitude: -83.2302,
    type: 'university',
    campus_type: 'branch',
    enrollment: 8547,
    international_students: 850,
    is_public: true,
    primary_color: '#00274C',
    secondary_color: '#FFCB05',
    website: 'https://umdearborn.edu',
    aliases: ['UMD'],
  },
  {
    id: 'umich-flint',
    name: 'University of Michigan-Flint',
    short_name: 'UM-Flint',
    system_name: 'University of Michigan',
    city: 'Flint',
    state: 'MI',
    zip_code: '48502',
    latitude: 43.0193,
    longitude: -83.6897,
    type: 'university',
    campus_type: 'branch',
    enrollment: 6892,
    international_students: 420,
    is_public: true,
    primary_color: '#00274C',
    secondary_color: '#FFCB05',
    website: 'https://www.umflint.edu',
    aliases: [],
  },
  {
    id: 'ohio-state',
    name: 'Ohio State University',
    short_name: 'Ohio State',
    system_name: 'Ohio State University',
    city: 'Columbus',
    state: 'OH',
    zip_code: '43210',
    latitude: 40.0067,
    longitude: -83.0305,
    type: 'university',
    campus_type: 'main',
    enrollment: 61369,
    international_students: 8200,
    is_public: true,
    primary_color: '#BB0000',
    secondary_color: '#666666',
    website: 'https://www.osu.edu',
    aliases: ['OSU', 'Buckeyes', 'tOSU'],
  },
  {
    id: 'ohio-state-lima',
    name: 'Ohio State University at Lima',
    short_name: 'OSU Lima',
    system_name: 'Ohio State University',
    city: 'Lima',
    state: 'OH',
    zip_code: '45804',
    latitude: 40.7678,
    longitude: -84.0233,
    type: 'university',
    campus_type: 'regional',
    enrollment: 1047,
    is_public: true,
    primary_color: '#BB0000',
    secondary_color: '#666666',
    website: 'https://lima.osu.edu',
    aliases: [],
  },
  {
    id: 'ohio-state-mansfield',
    name: 'Ohio State University at Mansfield',
    short_name: 'OSU Mansfield',
    system_name: 'Ohio State University',
    city: 'Mansfield',
    state: 'OH',
    zip_code: '44906',
    latitude: 40.7989,
    longitude: -82.5533,
    type: 'university',
    campus_type: 'regional',
    enrollment: 1089,
    is_public: true,
    primary_color: '#BB0000',
    secondary_color: '#666666',
    website: 'https://mansfield.osu.edu',
    aliases: [],
  },
  {
    id: 'ohio-state-marion',
    name: 'Ohio State University at Marion',
    short_name: 'OSU Marion',
    system_name: 'Ohio State University',
    city: 'Marion',
    state: 'OH',
    zip_code: '43302',
    latitude: 40.5806,
    longitude: -83.1250,
    type: 'university',
    campus_type: 'regional',
    enrollment: 1156,
    is_public: true,
    primary_color: '#BB0000',
    secondary_color: '#666666',
    website: 'https://marion.osu.edu',
    aliases: [],
  },
  {
    id: 'ohio-state-newark',
    name: 'Ohio State University at Newark',
    short_name: 'OSU Newark',
    system_name: 'Ohio State University',
    city: 'Newark',
    state: 'OH',
    zip_code: '43055',
    latitude: 40.0567,
    longitude: -82.4111,
    type: 'university',
    campus_type: 'regional',
    enrollment: 2547,
    is_public: true,
    primary_color: '#BB0000',
    secondary_color: '#666666',
    website: 'https://newark.osu.edu',
    aliases: [],
  },
  {
    id: 'penn-state',
    name: 'Pennsylvania State University',
    short_name: 'Penn State',
    system_name: 'Pennsylvania State University',
    city: 'University Park',
    state: 'PA',
    zip_code: '16802',
    latitude: 40.7982,
    longitude: -77.8599,
    type: 'university',
    campus_type: 'main',
    enrollment: 46810,
    international_students: 8900,
    is_public: true,
    primary_color: '#041E42',
    secondary_color: '#FFFFFF',
    website: 'https://www.psu.edu',
    aliases: ['PSU', 'Nittany Lions'],
  },
  {
    id: 'penn-state-abington',
    name: 'Penn State Abington',
    short_name: 'PSU Abington',
    system_name: 'Pennsylvania State University',
    city: 'Abington',
    state: 'PA',
    zip_code: '19001',
    latitude: 40.1169,
    longitude: -75.1183,
    type: 'university',
    campus_type: 'branch',
    enrollment: 3200,
    is_public: true,
    primary_color: '#041E42',
    secondary_color: '#FFFFFF',
    website: 'https://abington.psu.edu',
    aliases: [],
  },
  {
    id: 'penn-state-altoona',
    name: 'Penn State Altoona',
    short_name: 'PSU Altoona',
    system_name: 'Pennsylvania State University',
    city: 'Altoona',
    state: 'PA',
    zip_code: '16601',
    latitude: 40.4850,
    longitude: -78.3947,
    type: 'university',
    campus_type: 'branch',
    enrollment: 3100,
    is_public: true,
    primary_color: '#041E42',
    secondary_color: '#FFFFFF',
    website: 'https://altoona.psu.edu',
    aliases: [],
  },
  {
    id: 'penn-state-behrend',
    name: 'Penn State Erie, The Behrend College',
    short_name: 'Penn State Behrend',
    system_name: 'Pennsylvania State University',
    city: 'Erie',
    state: 'PA',
    zip_code: '16563',
    latitude: 42.1192,
    longitude: -79.9828,
    type: 'university',
    campus_type: 'branch',
    enrollment: 4400,
    is_public: true,
    primary_color: '#041E42',
    secondary_color: '#FFFFFF',
    website: 'https://behrend.psu.edu',
    aliases: ['Behrend'],
  },
  {
    id: 'penn-state-harrisburg',
    name: 'Penn State Harrisburg',
    short_name: 'PSU Harrisburg',
    system_name: 'Pennsylvania State University',
    city: 'Middletown',
    state: 'PA',
    zip_code: '17057',
    latitude: 40.2000,
    longitude: -76.7400,
    type: 'university',
    campus_type: 'branch',
    enrollment: 5200,
    is_public: true,
    primary_color: '#041E42',
    secondary_color: '#FFFFFF',
    website: 'https://harrisburg.psu.edu',
    aliases: [],
  },
  {
    id: 'indiana-bloomington',
    name: 'Indiana University Bloomington',
    short_name: 'IU Bloomington',
    system_name: 'Indiana University',
    city: 'Bloomington',
    state: 'IN',
    zip_code: '47405',
    latitude: 39.1682,
    longitude: -86.5186,
    type: 'university',
    campus_type: 'main',
    enrollment: 45328,
    international_students: 6200,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#FFFFFF',
    website: 'https://www.indiana.edu',
    aliases: ['IU', 'Hoosiers'],
  },
  {
    id: 'iupui',
    name: 'Indiana University-Purdue University Indianapolis',
    short_name: 'IUPUI',
    system_name: 'Indiana University',
    city: 'Indianapolis',
    state: 'IN',
    zip_code: '46202',
    latitude: 39.7739,
    longitude: -86.1752,
    type: 'university',
    campus_type: 'branch',
    enrollment: 26963,
    international_students: 2100,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#998542',
    website: 'https://www.iupui.edu',
    aliases: ['Jaguars'],
  },
  {
    id: 'indiana-south-bend',
    name: 'Indiana University South Bend',
    short_name: 'IU South Bend',
    system_name: 'Indiana University',
    city: 'South Bend',
    state: 'IN',
    zip_code: '46634',
    latitude: 41.6647,
    longitude: -86.2181,
    type: 'university',
    campus_type: 'regional',
    enrollment: 4200,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#FFFFFF',
    website: 'https://www.iusb.edu',
    aliases: ['IUSB'],
  },
  {
    id: 'indiana-northwest',
    name: 'Indiana University Northwest',
    short_name: 'IU Northwest',
    system_name: 'Indiana University',
    city: 'Gary',
    state: 'IN',
    zip_code: '46408',
    latitude: 41.5492,
    longitude: -87.3544,
    type: 'university',
    campus_type: 'regional',
    enrollment: 3100,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#FFFFFF',
    website: 'https://www.iun.edu',
    aliases: ['IUN'],
  },
  {
    id: 'indiana-southeast',
    name: 'Indiana University Southeast',
    short_name: 'IU Southeast',
    system_name: 'Indiana University',
    city: 'New Albany',
    state: 'IN',
    zip_code: '47150',
    latitude: 38.3353,
    longitude: -85.8189,
    type: 'university',
    campus_type: 'regional',
    enrollment: 4100,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#FFFFFF',
    website: 'https://www.ius.edu',
    aliases: ['IUS'],
  },
  {
    id: 'indiana-east',
    name: 'Indiana University East',
    short_name: 'IU East',
    system_name: 'Indiana University',
    city: 'Richmond',
    state: 'IN',
    zip_code: '47374',
    latitude: 39.8447,
    longitude: -84.8906,
    type: 'university',
    campus_type: 'regional',
    enrollment: 3200,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#FFFFFF',
    website: 'https://www.iue.edu',
    aliases: ['IUE'],
  },
  {
    id: 'indiana-kokomo',
    name: 'Indiana University Kokomo',
    short_name: 'IU Kokomo',
    system_name: 'Indiana University',
    city: 'Kokomo',
    state: 'IN',
    zip_code: '46902',
    latitude: 40.4653,
    longitude: -86.1333,
    type: 'university',
    campus_type: 'regional',
    enrollment: 2400,
    is_public: true,
    primary_color: '#990000',
    secondary_color: '#FFFFFF',
    website: 'https://www.iuk.edu',
    aliases: ['IUK'],
  },
  {
    id: 'purdue-west-lafayette',
    name: 'Purdue University',
    short_name: 'Purdue',
    system_name: 'Purdue University',
    city: 'West Lafayette',
    state: 'IN',
    zip_code: '47907',
    latitude: 40.4259,
    longitude: -86.9081,
    type: 'university',
    campus_type: 'main',
    enrollment: 49639,
    international_students: 11200,
    is_public: true,
    primary_color: '#CEB888',
    secondary_color: '#000000',
    website: 'https://www.purdue.edu',
    aliases: ['Boilermakers'],
  },
  {
    id: 'purdue-northwest',
    name: 'Purdue University Northwest',
    short_name: 'Purdue Northwest',
    system_name: 'Purdue University',
    city: 'Hammond',
    state: 'IN',
    zip_code: '46323',
    latitude: 41.5558,
    longitude: -87.4833,
    type: 'university',
    campus_type: 'regional',
    enrollment: 8892,
    international_students: 420,
    is_public: true,
    primary_color: '#CEB888',
    secondary_color: '#000000',
    website: 'https://www.pnw.edu',
    aliases: ['PNW', 'Pride'],
  },
  {
    id: 'purdue-fort-wayne',
    name: 'Purdue University Fort Wayne',
    short_name: 'PFW',
    system_name: 'Purdue University',
    city: 'Fort Wayne',
    state: 'IN',
    zip_code: '46805',
    latitude: 41.1164,
    longitude: -85.1086,
    type: 'university',
    campus_type: 'regional',
    enrollment: 7347,
    international_students: 380,
    is_public: true,
    primary_color: '#CEB888',
    secondary_color: '#000000',
    website: 'https://www.pfw.edu',
    aliases: ['Mastodons'],
  },
  {
    id: 'uiuc',
    name: 'University of Illinois Urbana-Champaign',
    short_name: 'UIUC',
    system_name: 'University of Illinois',
    city: 'Champaign',
    state: 'IL',
    zip_code: '61820',
    latitude: 40.1020,
    longitude: -88.2272,
    type: 'university',
    campus_type: 'main',
    enrollment: 56607,
    international_students: 12800,
    is_public: true,
    primary_color: '#E84A27',
    secondary_color: '#13294B',
    website: 'https://www.illinois.edu',
    aliases: ['Illinois', 'Fighting Illini'],
  },
  {
    id: 'uic',
    name: 'University of Illinois Chicago',
    short_name: 'UIC',
    system_name: 'University of Illinois',
    city: 'Chicago',
    state: 'IL',
    zip_code: '60607',
    latitude: 41.8708,
    longitude: -87.6505,
    type: 'university',
    campus_type: 'main',
    enrollment: 33518,
    international_students: 4200,
    is_public: true,
    primary_color: '#001E62',
    secondary_color: '#D50032',
    website: 'https://www.uic.edu',
    aliases: ['Flames'],
  },
  {
    id: 'uis',
    name: 'University of Illinois Springfield',
    short_name: 'UIS',
    system_name: 'University of Illinois',
    city: 'Springfield',
    state: 'IL',
    zip_code: '62703',
    latitude: 39.7300,
    longitude: -89.6178,
    type: 'university',
    campus_type: 'regional',
    enrollment: 4200,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.uis.edu',
    aliases: ['Prairie Stars'],
  },
  {
    id: 'uw-madison',
    name: 'University of Wisconsin-Madison',
    short_name: 'UW-Madison',
    system_name: 'University of Wisconsin',
    city: 'Madison',
    state: 'WI',
    zip_code: '53706',
    latitude: 43.0731,
    longitude: -89.4012,
    type: 'university',
    campus_type: 'main',
    enrollment: 47932,
    international_students: 7800,
    is_public: true,
    primary_color: '#C5050C',
    secondary_color: '#FFFFFF',
    website: 'https://www.wisc.edu',
    aliases: ['Wisconsin', 'Badgers'],
  },
  {
    id: 'uw-milwaukee',
    name: 'University of Wisconsin-Milwaukee',
    short_name: 'UW-Milwaukee',
    system_name: 'University of Wisconsin',
    city: 'Milwaukee',
    state: 'WI',
    zip_code: '53201',
    latitude: 43.0766,
    longitude: -87.8811,
    type: 'university',
    campus_type: 'main',
    enrollment: 23894,
    international_students: 1800,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFD100',
    website: 'https://www.uwm.edu',
    aliases: ['UWM', 'Panthers'],
  },
  {
    id: 'uw-green-bay',
    name: 'University of Wisconsin-Green Bay',
    short_name: 'UW-Green Bay',
    system_name: 'University of Wisconsin',
    city: 'Green Bay',
    state: 'WI',
    zip_code: '54311',
    latitude: 44.5311,
    longitude: -87.9017,
    type: 'university',
    campus_type: 'regional',
    enrollment: 8200,
    is_public: true,
    primary_color: '#006747',
    secondary_color: '#FFFFFF',
    website: 'https://www.uwgb.edu',
    aliases: ['UWGB', 'Phoenix'],
  },
  {
    id: 'uw-eau-claire',
    name: 'University of Wisconsin-Eau Claire',
    short_name: 'UW-Eau Claire',
    system_name: 'University of Wisconsin',
    city: 'Eau Claire',
    state: 'WI',
    zip_code: '54701',
    latitude: 44.7983,
    longitude: -91.4986,
    type: 'university',
    campus_type: 'regional',
    enrollment: 10200,
    is_public: true,
    primary_color: '#003057',
    secondary_color: '#B8860B',
    website: 'https://www.uwec.edu',
    aliases: ['UWEC', 'Blugolds'],
  },
  {
    id: 'uw-la-crosse',
    name: 'University of Wisconsin-La Crosse',
    short_name: 'UW-La Crosse',
    system_name: 'University of Wisconsin',
    city: 'La Crosse',
    state: 'WI',
    zip_code: '54601',
    latitude: 43.8136,
    longitude: -91.2278,
    type: 'university',
    campus_type: 'regional',
    enrollment: 10500,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#808080',
    website: 'https://www.uwlax.edu',
    aliases: ['UWL', 'Eagles'],
  },
  {
    id: 'uw-oshkosh',
    name: 'University of Wisconsin-Oshkosh',
    short_name: 'UW-Oshkosh',
    system_name: 'University of Wisconsin',
    city: 'Oshkosh',
    state: 'WI',
    zip_code: '54901',
    latitude: 44.0261,
    longitude: -88.5472,
    type: 'university',
    campus_type: 'regional',
    enrollment: 13200,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFD100',
    website: 'https://www.uwosh.edu',
    aliases: ['UWO', 'Titans'],
  },
  {
    id: 'uw-platteville',
    name: 'University of Wisconsin-Platteville',
    short_name: 'UW-Platteville',
    system_name: 'University of Wisconsin',
    city: 'Platteville',
    state: 'WI',
    zip_code: '53818',
    latitude: 42.7267,
    longitude: -90.4847,
    type: 'university',
    campus_type: 'regional',
    enrollment: 7200,
    is_public: true,
    primary_color: '#F47920',
    secondary_color: '#000000',
    website: 'https://www.uwplatt.edu',
    aliases: ['Pioneers'],
  },
  {
    id: 'uw-river-falls',
    name: 'University of Wisconsin-River Falls',
    short_name: 'UW-River Falls',
    system_name: 'University of Wisconsin',
    city: 'River Falls',
    state: 'WI',
    zip_code: '54022',
    latitude: 44.8533,
    longitude: -92.6211,
    type: 'university',
    campus_type: 'regional',
    enrollment: 5200,
    is_public: true,
    primary_color: '#B31B1B',
    secondary_color: '#FFFFFF',
    website: 'https://www.uwrf.edu',
    aliases: ['UWRF', 'Falcons'],
  },
  {
    id: 'uw-stevens-point',
    name: 'University of Wisconsin-Stevens Point',
    short_name: 'UW-Stevens Point',
    system_name: 'University of Wisconsin',
    city: 'Stevens Point',
    state: 'WI',
    zip_code: '54481',
    latitude: 44.5308,
    longitude: -89.5750,
    type: 'university',
    campus_type: 'regional',
    enrollment: 7800,
    is_public: true,
    primary_color: '#512888',
    secondary_color: '#FFD100',
    website: 'https://www.uwsp.edu',
    aliases: ['UWSP', 'Pointers'],
  },
  {
    id: 'uw-stout',
    name: 'University of Wisconsin-Stout',
    short_name: 'UW-Stout',
    system_name: 'University of Wisconsin',
    city: 'Menomonie',
    state: 'WI',
    zip_code: '54751',
    latitude: 44.8758,
    longitude: -91.9197,
    type: 'university',
    campus_type: 'regional',
    enrollment: 7400,
    is_public: true,
    primary_color: '#003057',
    secondary_color: '#FFD100',
    website: 'https://www.uwstout.edu',
    aliases: ['Stout', 'Blue Devils'],
  },
  {
    id: 'uw-superior',
    name: 'University of Wisconsin-Superior',
    short_name: 'UW-Superior',
    system_name: 'University of Wisconsin',
    city: 'Superior',
    state: 'WI',
    zip_code: '54880',
    latitude: 46.7208,
    longitude: -92.0883,
    type: 'university',
    campus_type: 'regional',
    enrollment: 2400,
    is_public: true,
    primary_color: '#FFD100',
    secondary_color: '#000000',
    website: 'https://www.uwsuper.edu',
    aliases: ['UWS', 'Yellowjackets'],
  },
  {
    id: 'uw-whitewater',
    name: 'University of Wisconsin-Whitewater',
    short_name: 'UW-Whitewater',
    system_name: 'University of Wisconsin',
    city: 'Whitewater',
    state: 'WI',
    zip_code: '53190',
    latitude: 42.8353,
    longitude: -88.7392,
    type: 'university',
    campus_type: 'regional',
    enrollment: 11200,
    is_public: true,
    primary_color: '#512888',
    secondary_color: '#FFFFFF',
    website: 'https://www.uww.edu',
    aliases: ['UWW', 'Warhawks'],
  },
  {
    id: 'uw-parkside',
    name: 'University of Wisconsin-Parkside',
    short_name: 'UW-Parkside',
    system_name: 'University of Wisconsin',
    city: 'Kenosha',
    state: 'WI',
    zip_code: '53141',
    latitude: 42.6436,
    longitude: -87.8519,
    type: 'university',
    campus_type: 'regional',
    enrollment: 4100,
    is_public: true,
    primary_color: '#006B54',
    secondary_color: '#000000',
    website: 'https://www.uwp.edu',
    aliases: ['Parkside', 'Rangers'],
  },
  {
    id: 'umn-twin-cities',
    name: 'University of Minnesota Twin Cities',
    short_name: 'UMN',
    system_name: 'University of Minnesota',
    city: 'Minneapolis',
    state: 'MN',
    zip_code: '55455',
    latitude: 44.9740,
    longitude: -93.2277,
    type: 'university',
    campus_type: 'main',
    enrollment: 52376,
    international_students: 7200,
    is_public: true,
    primary_color: '#7A0019',
    secondary_color: '#FFCC33',
    website: 'https://www.umn.edu',
    aliases: ['Minnesota', 'Gophers', 'U of M'],
  },
  {
    id: 'umn-duluth',
    name: 'University of Minnesota Duluth',
    short_name: 'UMD',
    system_name: 'University of Minnesota',
    city: 'Duluth',
    state: 'MN',
    zip_code: '55812',
    latitude: 46.8184,
    longitude: -92.0838,
    type: 'university',
    campus_type: 'regional',
    enrollment: 9200,
    international_students: 420,
    is_public: true,
    primary_color: '#7A0019',
    secondary_color: '#FFCC33',
    website: 'https://www.d.umn.edu',
    aliases: ['Bulldogs'],
  },
  {
    id: 'umn-morris',
    name: 'University of Minnesota Morris',
    short_name: 'UMM',
    system_name: 'University of Minnesota',
    city: 'Morris',
    state: 'MN',
    zip_code: '56267',
    latitude: 45.5847,
    longitude: -95.8933,
    type: 'university',
    campus_type: 'regional',
    enrollment: 1500,
    is_public: true,
    primary_color: '#7A0019',
    secondary_color: '#FFCC33',
    website: 'https://www.morris.umn.edu',
    aliases: ['Cougars'],
  },
  {
    id: 'umn-rochester',
    name: 'University of Minnesota Rochester',
    short_name: 'UMR',
    system_name: 'University of Minnesota',
    city: 'Rochester',
    state: 'MN',
    zip_code: '55904',
    latitude: 44.0194,
    longitude: -92.4631,
    type: 'university',
    campus_type: 'regional',
    enrollment: 850,
    is_public: true,
    primary_color: '#7A0019',
    secondary_color: '#FFCC33',
    website: 'https://r.umn.edu',
    aliases: [],
  },
  {
    id: 'umn-crookston',
    name: 'University of Minnesota Crookston',
    short_name: 'UMC',
    system_name: 'University of Minnesota',
    city: 'Crookston',
    state: 'MN',
    zip_code: '56716',
    latitude: 47.7936,
    longitude: -96.6078,
    type: 'university',
    campus_type: 'regional',
    enrollment: 2100,
    is_public: true,
    primary_color: '#7A0019',
    secondary_color: '#FFCC33',
    website: 'https://www.crk.umn.edu',
    aliases: ['Golden Eagles'],
  },
  {
    id: 'msu',
    name: 'Michigan State University',
    short_name: 'Michigan State',
    city: 'East Lansing',
    state: 'MI',
    zip_code: '48824',
    latitude: 42.7018,
    longitude: -84.4822,
    type: 'university',
    campus_type: 'main',
    enrollment: 50023,
    international_students: 6800,
    is_public: true,
    primary_color: '#18453B',
    secondary_color: '#FFFFFF',
    website: 'https://www.msu.edu',
    aliases: ['MSU', 'Spartans'],
  },
  {
    id: 'iowa',
    name: 'University of Iowa',
    short_name: 'Iowa',
    city: 'Iowa City',
    state: 'IA',
    zip_code: '52242',
    latitude: 41.6611,
    longitude: -91.5302,
    type: 'university',
    campus_type: 'main',
    enrollment: 31240,
    international_students: 3400,
    is_public: true,
    primary_color: '#FFCD00',
    secondary_color: '#000000',
    website: 'https://www.uiowa.edu',
    aliases: ['Hawkeyes'],
  },
  {
    id: 'nebraska',
    name: 'University of Nebraska-Lincoln',
    short_name: 'Nebraska',
    system_name: 'University of Nebraska',
    city: 'Lincoln',
    state: 'NE',
    zip_code: '68588',
    latitude: 40.8202,
    longitude: -96.7005,
    type: 'university',
    campus_type: 'main',
    enrollment: 23805,
    international_students: 2800,
    is_public: true,
    primary_color: '#D00000',
    secondary_color: '#FFFFFF',
    website: 'https://www.unl.edu',
    aliases: ['UNL', 'Huskers', 'Cornhuskers'],
  },
  {
    id: 'unomaha',
    name: 'University of Nebraska at Omaha',
    short_name: 'UNO',
    system_name: 'University of Nebraska',
    city: 'Omaha',
    state: 'NE',
    zip_code: '68182',
    latitude: 41.2579,
    longitude: -96.0086,
    type: 'university',
    campus_type: 'regional',
    enrollment: 15400,
    international_students: 1200,
    is_public: true,
    primary_color: '#D00000',
    secondary_color: '#000000',
    website: 'https://www.unomaha.edu',
    aliases: ['Mavericks'],
  },
  {
    id: 'unk',
    name: 'University of Nebraska at Kearney',
    short_name: 'UNK',
    system_name: 'University of Nebraska',
    city: 'Kearney',
    state: 'NE',
    zip_code: '68849',
    latitude: 40.6986,
    longitude: -99.0903,
    type: 'university',
    campus_type: 'regional',
    enrollment: 5800,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.unk.edu',
    aliases: ['Lopers'],
  },
  {
    id: 'rutgers',
    name: 'Rutgers University-New Brunswick',
    short_name: 'Rutgers',
    system_name: 'Rutgers University',
    city: 'New Brunswick',
    state: 'NJ',
    zip_code: '08901',
    latitude: 40.5008,
    longitude: -74.4474,
    type: 'university',
    campus_type: 'main',
    enrollment: 50254,
    international_students: 8200,
    is_public: true,
    primary_color: '#CC0033',
    secondary_color: '#000000',
    website: 'https://www.rutgers.edu',
    aliases: ['RU', 'Scarlet Knights'],
  },
  {
    id: 'rutgers-newark',
    name: 'Rutgers University-Newark',
    short_name: 'Rutgers Newark',
    system_name: 'Rutgers University',
    city: 'Newark',
    state: 'NJ',
    zip_code: '07102',
    latitude: 40.7418,
    longitude: -74.1733,
    type: 'university',
    campus_type: 'branch',
    enrollment: 11892,
    international_students: 1400,
    is_public: true,
    primary_color: '#CC0033',
    secondary_color: '#000000',
    website: 'https://www.newark.rutgers.edu',
    aliases: ['Scarlet Raiders'],
  },
  {
    id: 'rutgers-camden',
    name: 'Rutgers University-Camden',
    short_name: 'Rutgers Camden',
    system_name: 'Rutgers University',
    city: 'Camden',
    state: 'NJ',
    zip_code: '08102',
    latitude: 39.9486,
    longitude: -75.1225,
    type: 'university',
    campus_type: 'branch',
    enrollment: 6847,
    international_students: 480,
    is_public: true,
    primary_color: '#CC0033',
    secondary_color: '#000000',
    website: 'https://www.camden.rutgers.edu',
    aliases: ['Scarlet Raptors'],
  },
  {
    id: 'maryland',
    name: 'University of Maryland, College Park',
    short_name: 'Maryland',
    system_name: 'University System of Maryland',
    city: 'College Park',
    state: 'MD',
    zip_code: '20742',
    latitude: 38.9869,
    longitude: -76.9426,
    type: 'university',
    campus_type: 'main',
    enrollment: 41200,
    international_students: 5400,
    is_public: true,
    primary_color: '#E03A3E',
    secondary_color: '#FFD200',
    website: 'https://www.umd.edu',
    aliases: ['UMD', 'Terrapins', 'Terps'],
  },
  {
    id: 'umbc',
    name: 'University of Maryland, Baltimore County',
    short_name: 'UMBC',
    system_name: 'University System of Maryland',
    city: 'Baltimore',
    state: 'MD',
    zip_code: '21250',
    latitude: 39.2558,
    longitude: -76.7108,
    type: 'university',
    campus_type: 'main',
    enrollment: 13637,
    international_students: 1800,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFB81C',
    website: 'https://www.umbc.edu',
    aliases: ['Retrievers'],
  },
  {
    id: 'oregon',
    name: 'University of Oregon',
    short_name: 'Oregon',
    city: 'Eugene',
    state: 'OR',
    zip_code: '97403',
    latitude: 44.0448,
    longitude: -123.0726,
    type: 'university',
    campus_type: 'main',
    enrollment: 23634,
    international_students: 2800,
    is_public: true,
    primary_color: '#154733',
    secondary_color: '#FEE123',
    website: 'https://www.uoregon.edu',
    aliases: ['UO', 'Ducks'],
  },
  {
    id: 'oregon-state',
    name: 'Oregon State University',
    short_name: 'Oregon State',
    city: 'Corvallis',
    state: 'OR',
    zip_code: '97331',
    latitude: 44.5646,
    longitude: -123.2820,
    type: 'university',
    campus_type: 'main',
    enrollment: 33189,
    international_students: 3200,
    is_public: true,
    primary_color: '#D73F09',
    secondary_color: '#000000',
    website: 'https://oregonstate.edu',
    aliases: ['OSU', 'Beavers'],
  },
  {
    id: 'washington',
    name: 'University of Washington',
    short_name: 'UW',
    system_name: 'University of Washington',
    city: 'Seattle',
    state: 'WA',
    zip_code: '98195',
    latitude: 47.6553,
    longitude: -122.3035,
    type: 'university',
    campus_type: 'main',
    enrollment: 51448,
    international_students: 8600,
    is_public: true,
    primary_color: '#4B2E83',
    secondary_color: '#B7A57A',
    website: 'https://www.washington.edu',
    aliases: ['UDub', 'Huskies'],
  },
  {
    id: 'uw-tacoma',
    name: 'University of Washington Tacoma',
    short_name: 'UW Tacoma',
    system_name: 'University of Washington',
    city: 'Tacoma',
    state: 'WA',
    zip_code: '98402',
    latitude: 47.2453,
    longitude: -122.4386,
    type: 'university',
    campus_type: 'branch',
    enrollment: 5200,
    is_public: true,
    primary_color: '#4B2E83',
    secondary_color: '#B7A57A',
    website: 'https://www.tacoma.uw.edu',
    aliases: [],
  },
  {
    id: 'uw-bothell',
    name: 'University of Washington Bothell',
    short_name: 'UW Bothell',
    system_name: 'University of Washington',
    city: 'Bothell',
    state: 'WA',
    zip_code: '98011',
    latitude: 47.7594,
    longitude: -122.1894,
    type: 'university',
    campus_type: 'branch',
    enrollment: 5800,
    is_public: true,
    primary_color: '#4B2E83',
    secondary_color: '#B7A57A',
    website: 'https://www.uwb.edu',
    aliases: [],
  },
  {
    id: 'washington-state',
    name: 'Washington State University',
    short_name: 'WSU',
    system_name: 'Washington State University',
    city: 'Pullman',
    state: 'WA',
    zip_code: '99164',
    latitude: 46.7319,
    longitude: -117.1542,
    type: 'university',
    campus_type: 'main',
    enrollment: 29686,
    international_students: 2800,
    is_public: true,
    primary_color: '#981E32',
    secondary_color: '#5E6A71',
    website: 'https://www.wsu.edu',
    aliases: ['Wazzu', 'Cougars'],
  },
  {
    id: 'wsu-spokane',
    name: 'Washington State University Spokane',
    short_name: 'WSU Spokane',
    system_name: 'Washington State University',
    city: 'Spokane',
    state: 'WA',
    zip_code: '99202',
    latitude: 47.6556,
    longitude: -117.4206,
    type: 'university',
    campus_type: 'branch',
    enrollment: 1800,
    is_public: true,
    primary_color: '#981E32',
    secondary_color: '#5E6A71',
    website: 'https://spokane.wsu.edu',
    aliases: [],
  },
  {
    id: 'wsu-vancouver',
    name: 'Washington State University Vancouver',
    short_name: 'WSU Vancouver',
    system_name: 'Washington State University',
    city: 'Vancouver',
    state: 'WA',
    zip_code: '98686',
    latitude: 45.7336,
    longitude: -122.6358,
    type: 'university',
    campus_type: 'branch',
    enrollment: 3400,
    is_public: true,
    primary_color: '#981E32',
    secondary_color: '#5E6A71',
    website: 'https://www.vancouver.wsu.edu',
    aliases: [],
  },
  {
    id: 'wsu-tri-cities',
    name: 'Washington State University Tri-Cities',
    short_name: 'WSU Tri-Cities',
    system_name: 'Washington State University',
    city: 'Richland',
    state: 'WA',
    zip_code: '99354',
    latitude: 46.3361,
    longitude: -119.2764,
    type: 'university',
    campus_type: 'branch',
    enrollment: 1600,
    is_public: true,
    primary_color: '#981E32',
    secondary_color: '#5E6A71',
    website: 'https://tricities.wsu.edu',
    aliases: [],
  },
];

export default BIG_TEN;
