// ============================================================================
// TEXAS UNIVERSITY SYSTEMS
// University of Texas System, Texas A&M System, Texas State, Texas Tech, etc.
// ============================================================================

import { University } from './types';

// ============================================================================
// UNIVERSITY OF TEXAS SYSTEM
// ============================================================================
export const UT_SYSTEM: University[] = [
  {
    id: 'ut-austin',
    name: 'University of Texas at Austin',
    short_name: 'UT Austin',
    system_name: 'University of Texas System',
    city: 'Austin',
    state: 'TX',
    zip_code: '78712',
    latitude: 30.2849,
    longitude: -97.7341,
    type: 'university',
    campus_type: 'main',
    enrollment: 51991,
    international_students: 5800,
    is_public: true,
    primary_color: '#BF5700',
    secondary_color: '#FFFFFF',
    website: 'https://www.utexas.edu',
    aliases: ['UT', 'Texas', 'Longhorns'],
  },
  {
    id: 'ut-dallas',
    name: 'University of Texas at Dallas',
    short_name: 'UT Dallas',
    system_name: 'University of Texas System',
    city: 'Richardson',
    state: 'TX',
    zip_code: '75080',
    latitude: 32.9857,
    longitude: -96.7502,
    type: 'university',
    campus_type: 'main',
    enrollment: 31019,
    international_students: 7200,
    is_public: true,
    primary_color: '#C75B12',
    secondary_color: '#008542',
    website: 'https://www.utdallas.edu',
    aliases: ['UTD', 'Comets'],
  },
  {
    id: 'ut-arlington',
    name: 'University of Texas at Arlington',
    short_name: 'UT Arlington',
    system_name: 'University of Texas System',
    city: 'Arlington',
    state: 'TX',
    zip_code: '76019',
    latitude: 32.7291,
    longitude: -97.1131,
    type: 'university',
    campus_type: 'main',
    enrollment: 42669,
    international_students: 4800,
    is_public: true,
    primary_color: '#0064B1',
    secondary_color: '#F68500',
    website: 'https://www.uta.edu',
    aliases: ['UTA', 'Mavericks'],
  },
  {
    id: 'ut-san-antonio',
    name: 'University of Texas at San Antonio',
    short_name: 'UTSA',
    system_name: 'University of Texas System',
    city: 'San Antonio',
    state: 'TX',
    zip_code: '78249',
    latitude: 29.5826,
    longitude: -98.6200,
    type: 'university',
    campus_type: 'main',
    enrollment: 34909,
    international_students: 2400,
    is_public: true,
    primary_color: '#0C2340',
    secondary_color: '#F15A22',
    website: 'https://www.utsa.edu',
    aliases: ['Roadrunners'],
  },
  {
    id: 'ut-el-paso',
    name: 'University of Texas at El Paso',
    short_name: 'UTEP',
    system_name: 'University of Texas System',
    city: 'El Paso',
    state: 'TX',
    zip_code: '79968',
    latitude: 31.7697,
    longitude: -106.5047,
    type: 'university',
    campus_type: 'main',
    enrollment: 24003,
    international_students: 1200,
    is_public: true,
    primary_color: '#FF8200',
    secondary_color: '#041E42',
    website: 'https://www.utep.edu',
    aliases: ['Miners'],
  },
  {
    id: 'ut-rio-grande-valley',
    name: 'University of Texas Rio Grande Valley',
    short_name: 'UTRGV',
    system_name: 'University of Texas System',
    city: 'Edinburg',
    state: 'TX',
    zip_code: '78539',
    latitude: 26.3064,
    longitude: -98.1797,
    type: 'university',
    campus_type: 'main',
    enrollment: 32000,
    international_students: 1800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#F68500',
    website: 'https://www.utrgv.edu',
    aliases: ['Vaqueros'],
  },
  {
    id: 'ut-tyler',
    name: 'University of Texas at Tyler',
    short_name: 'UT Tyler',
    system_name: 'University of Texas System',
    city: 'Tyler',
    state: 'TX',
    zip_code: '75799',
    latitude: 32.3125,
    longitude: -95.2519,
    type: 'university',
    campus_type: 'main',
    enrollment: 10247,
    international_students: 480,
    is_public: true,
    primary_color: '#00539B',
    secondary_color: '#FFB81C',
    website: 'https://www.uttyler.edu',
    aliases: ['Patriots'],
  },
  {
    id: 'ut-permian-basin',
    name: 'University of Texas of the Permian Basin',
    short_name: 'UTPB',
    system_name: 'University of Texas System',
    city: 'Odessa',
    state: 'TX',
    zip_code: '79762',
    latitude: 31.8689,
    longitude: -102.3833,
    type: 'university',
    campus_type: 'main',
    enrollment: 5800,
    international_students: 280,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FF6B00',
    website: 'https://www.utpb.edu',
    aliases: ['Falcons'],
  },
];

// ============================================================================
// TEXAS A&M UNIVERSITY SYSTEM
// ============================================================================
export const TAMU_SYSTEM: University[] = [
  {
    id: 'tamu',
    name: 'Texas A&M University',
    short_name: 'Texas A&M',
    system_name: 'Texas A&M University System',
    city: 'College Station',
    state: 'TX',
    zip_code: '77843',
    latitude: 30.6180,
    longitude: -96.3388,
    type: 'university',
    campus_type: 'main',
    enrollment: 71109,
    international_students: 7800,
    is_public: true,
    primary_color: '#500000',
    secondary_color: '#FFFFFF',
    website: 'https://www.tamu.edu',
    aliases: ['A&M', 'Aggies', 'TAMU'],
  },
  {
    id: 'tamu-galveston',
    name: 'Texas A&M University at Galveston',
    short_name: 'TAMUG',
    system_name: 'Texas A&M University System',
    city: 'Galveston',
    state: 'TX',
    zip_code: '77553',
    latitude: 29.3003,
    longitude: -94.7906,
    type: 'university',
    campus_type: 'branch',
    enrollment: 2100,
    international_students: 120,
    is_public: true,
    primary_color: '#500000',
    secondary_color: '#003C71',
    website: 'https://www.tamug.edu',
    aliases: ['Sea Aggies'],
  },
  {
    id: 'tamu-commerce',
    name: 'Texas A&M University-Commerce',
    short_name: 'A&M-Commerce',
    system_name: 'Texas A&M University System',
    city: 'Commerce',
    state: 'TX',
    zip_code: '75428',
    latitude: 33.2458,
    longitude: -95.9033,
    type: 'university',
    campus_type: 'regional',
    enrollment: 11892,
    international_students: 680,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFB81C',
    website: 'https://www.tamuc.edu',
    aliases: ['Lions'],
  },
  {
    id: 'tamu-corpus-christi',
    name: 'Texas A&M University-Corpus Christi',
    short_name: 'A&M-Corpus Christi',
    system_name: 'Texas A&M University System',
    city: 'Corpus Christi',
    state: 'TX',
    zip_code: '78412',
    latitude: 27.7147,
    longitude: -97.3236,
    type: 'university',
    campus_type: 'regional',
    enrollment: 11478,
    international_students: 520,
    is_public: true,
    primary_color: '#00539B',
    secondary_color: '#006747',
    website: 'https://www.tamucc.edu',
    aliases: ['TAMUCC', 'Islanders'],
  },
  {
    id: 'tamu-kingsville',
    name: 'Texas A&M University-Kingsville',
    short_name: 'A&M-Kingsville',
    system_name: 'Texas A&M University System',
    city: 'Kingsville',
    state: 'TX',
    zip_code: '78363',
    latitude: 27.5264,
    longitude: -97.8750,
    type: 'university',
    campus_type: 'regional',
    enrollment: 7200,
    international_students: 320,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.tamuk.edu',
    aliases: ['TAMUK', 'Javelinas'],
  },
  {
    id: 'tamu-texarkana',
    name: 'Texas A&M University-Texarkana',
    short_name: 'A&M-Texarkana',
    system_name: 'Texas A&M University System',
    city: 'Texarkana',
    state: 'TX',
    zip_code: '75503',
    latitude: 33.4408,
    longitude: -94.0678,
    type: 'university',
    campus_type: 'regional',
    enrollment: 2400,
    international_students: 80,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.tamut.edu',
    aliases: ['Eagles'],
  },
  {
    id: 'tamu-central-texas',
    name: 'Texas A&M University-Central Texas',
    short_name: 'A&M-Central Texas',
    system_name: 'Texas A&M University System',
    city: 'Killeen',
    state: 'TX',
    zip_code: '76549',
    latitude: 31.0578,
    longitude: -97.7278,
    type: 'university',
    campus_type: 'regional',
    enrollment: 2800,
    international_students: 120,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.tamuct.edu',
    aliases: ['Warriors'],
  },
  {
    id: 'tamu-san-antonio',
    name: 'Texas A&M University-San Antonio',
    short_name: 'A&M-San Antonio',
    system_name: 'Texas A&M University System',
    city: 'San Antonio',
    state: 'TX',
    zip_code: '78224',
    latitude: 29.2867,
    longitude: -98.6247,
    type: 'university',
    campus_type: 'regional',
    enrollment: 7500,
    international_students: 280,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#FFB81C',
    website: 'https://www.tamusa.edu',
    aliases: ['Jaguars'],
  },
  {
    id: 'prairie-view-am',
    name: 'Prairie View A&M University',
    short_name: 'Prairie View',
    system_name: 'Texas A&M University System',
    city: 'Prairie View',
    state: 'TX',
    zip_code: '77446',
    latitude: 30.0894,
    longitude: -95.9878,
    type: 'university',
    campus_type: 'main',
    enrollment: 9200,
    international_students: 380,
    is_public: true,
    primary_color: '#660099',
    secondary_color: '#FFD100',
    website: 'https://www.pvamu.edu',
    aliases: ['PVAMU', 'Panthers'],
  },
  {
    id: 'tarleton-state',
    name: 'Tarleton State University',
    short_name: 'Tarleton',
    system_name: 'Texas A&M University System',
    city: 'Stephenville',
    state: 'TX',
    zip_code: '76402',
    latitude: 32.2192,
    longitude: -98.1958,
    type: 'university',
    campus_type: 'main',
    enrollment: 14892,
    international_students: 420,
    is_public: true,
    primary_color: '#512888',
    secondary_color: '#FFFFFF',
    website: 'https://www.tarleton.edu',
    aliases: ['Texans'],
  },
  {
    id: 'west-texas-am',
    name: 'West Texas A&M University',
    short_name: 'West Texas A&M',
    system_name: 'Texas A&M University System',
    city: 'Canyon',
    state: 'TX',
    zip_code: '79016',
    latitude: 34.9842,
    longitude: -101.9172,
    type: 'university',
    campus_type: 'main',
    enrollment: 10200,
    international_students: 480,
    is_public: true,
    primary_color: '#500000',
    secondary_color: '#FFFFFF',
    website: 'https://www.wtamu.edu',
    aliases: ['WTAMU', 'Buffaloes'],
  },
];

// ============================================================================
// OTHER TEXAS PUBLIC UNIVERSITIES
// ============================================================================
export const TEXAS_OTHER: University[] = [
  {
    id: 'texas-tech',
    name: 'Texas Tech University',
    short_name: 'Texas Tech',
    city: 'Lubbock',
    state: 'TX',
    zip_code: '79409',
    latitude: 33.5842,
    longitude: -101.8783,
    type: 'university',
    campus_type: 'main',
    enrollment: 40322,
    international_students: 3200,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#000000',
    website: 'https://www.ttu.edu',
    aliases: ['TTU', 'Red Raiders'],
  },
  {
    id: 'texas-state',
    name: 'Texas State University',
    short_name: 'Texas State',
    system_name: 'Texas State University System',
    city: 'San Marcos',
    state: 'TX',
    zip_code: '78666',
    latitude: 29.8883,
    longitude: -97.9386,
    type: 'university',
    campus_type: 'main',
    enrollment: 38644,
    international_students: 1800,
    is_public: true,
    primary_color: '#501214',
    secondary_color: '#363534',
    website: 'https://www.txstate.edu',
    aliases: ['TXST', 'Bobcats'],
  },
  {
    id: 'uh',
    name: 'University of Houston',
    short_name: 'Houston',
    system_name: 'University of Houston System',
    city: 'Houston',
    state: 'TX',
    zip_code: '77204',
    latitude: 29.7199,
    longitude: -95.3422,
    type: 'university',
    campus_type: 'main',
    enrollment: 47031,
    international_students: 5200,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#FFFFFF',
    website: 'https://www.uh.edu',
    aliases: ['UH', 'Cougars'],
  },
  {
    id: 'uh-downtown',
    name: 'University of Houston-Downtown',
    short_name: 'UH-Downtown',
    system_name: 'University of Houston System',
    city: 'Houston',
    state: 'TX',
    zip_code: '77002',
    latitude: 29.7650,
    longitude: -95.3594,
    type: 'university',
    campus_type: 'branch',
    enrollment: 14892,
    international_students: 1200,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#005A9C',
    website: 'https://www.uhd.edu',
    aliases: ['UHD', 'Gators'],
  },
  {
    id: 'uh-clear-lake',
    name: 'University of Houston-Clear Lake',
    short_name: 'UH-Clear Lake',
    system_name: 'University of Houston System',
    city: 'Houston',
    state: 'TX',
    zip_code: '77058',
    latitude: 29.5606,
    longitude: -95.0994,
    type: 'university',
    campus_type: 'branch',
    enrollment: 9247,
    international_students: 680,
    is_public: true,
    primary_color: '#005A9C',
    secondary_color: '#006747',
    website: 'https://www.uhcl.edu',
    aliases: ['UHCL', 'Hawks'],
  },
  {
    id: 'uh-victoria',
    name: 'University of Houston-Victoria',
    short_name: 'UH-Victoria',
    system_name: 'University of Houston System',
    city: 'Victoria',
    state: 'TX',
    zip_code: '77901',
    latitude: 28.7967,
    longitude: -97.0031,
    type: 'university',
    campus_type: 'branch',
    enrollment: 4200,
    international_students: 280,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#000000',
    website: 'https://www.uhv.edu',
    aliases: ['UHV', 'Jaguars'],
  },
  {
    id: 'unt',
    name: 'University of North Texas',
    short_name: 'UNT',
    system_name: 'University of North Texas System',
    city: 'Denton',
    state: 'TX',
    zip_code: '76203',
    latitude: 33.2065,
    longitude: -97.1526,
    type: 'university',
    campus_type: 'main',
    enrollment: 42451,
    international_students: 3400,
    is_public: true,
    primary_color: '#00853E',
    secondary_color: '#FFFFFF',
    website: 'https://www.unt.edu',
    aliases: ['North Texas', 'Mean Green'],
  },
  {
    id: 'unt-dallas',
    name: 'University of North Texas at Dallas',
    short_name: 'UNT Dallas',
    system_name: 'University of North Texas System',
    city: 'Dallas',
    state: 'TX',
    zip_code: '75241',
    latitude: 32.6953,
    longitude: -96.7456,
    type: 'university',
    campus_type: 'branch',
    enrollment: 4200,
    international_students: 280,
    is_public: true,
    primary_color: '#00853E',
    secondary_color: '#002868',
    website: 'https://www.untdallas.edu',
    aliases: ['Trailblazers'],
  },
  {
    id: 'sfa',
    name: 'Stephen F. Austin State University',
    short_name: 'SFA',
    city: 'Nacogdoches',
    state: 'TX',
    zip_code: '75962',
    latitude: 31.6111,
    longitude: -94.6481,
    type: 'university',
    campus_type: 'main',
    enrollment: 12047,
    international_students: 380,
    is_public: true,
    primary_color: '#512888',
    secondary_color: '#FFFFFF',
    website: 'https://www.sfasu.edu',
    aliases: ['Lumberjacks'],
  },
  {
    id: 'shsu',
    name: 'Sam Houston State University',
    short_name: 'Sam Houston',
    city: 'Huntsville',
    state: 'TX',
    zip_code: '77340',
    latitude: 30.7152,
    longitude: -95.5450,
    type: 'university',
    campus_type: 'main',
    enrollment: 22892,
    international_students: 1200,
    is_public: true,
    primary_color: '#F68500',
    secondary_color: '#FFFFFF',
    website: 'https://www.shsu.edu',
    aliases: ['SHSU', 'Bearkats'],
  },
  {
    id: 'lamar',
    name: 'Lamar University',
    short_name: 'Lamar',
    system_name: 'Texas State University System',
    city: 'Beaumont',
    state: 'TX',
    zip_code: '77710',
    latitude: 30.0545,
    longitude: -94.0897,
    type: 'university',
    campus_type: 'main',
    enrollment: 16847,
    international_students: 920,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#FFFFFF',
    website: 'https://www.lamar.edu',
    aliases: ['Cardinals'],
  },
  {
    id: 'midwestern-state',
    name: 'Midwestern State University',
    short_name: 'Midwestern State',
    city: 'Wichita Falls',
    state: 'TX',
    zip_code: '76308',
    latitude: 33.8783,
    longitude: -98.5269,
    type: 'university',
    campus_type: 'main',
    enrollment: 5892,
    international_students: 420,
    is_public: true,
    primary_color: '#862633',
    secondary_color: '#FFB81C',
    website: 'https://www.msutexas.edu',
    aliases: ['MSU Texas', 'Mustangs'],
  },
  {
    id: 'sul-ross',
    name: 'Sul Ross State University',
    short_name: 'Sul Ross',
    system_name: 'Texas State University System',
    city: 'Alpine',
    state: 'TX',
    zip_code: '79832',
    latitude: 30.3583,
    longitude: -103.6619,
    type: 'university',
    campus_type: 'main',
    enrollment: 2100,
    international_students: 80,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#FFB81C',
    website: 'https://www.sulross.edu',
    aliases: ['Lobos'],
  },
  {
    id: 'angelo-state',
    name: 'Angelo State University',
    short_name: 'Angelo State',
    system_name: 'Texas Tech University System',
    city: 'San Angelo',
    state: 'TX',
    zip_code: '76909',
    latitude: 31.4419,
    longitude: -100.4619,
    type: 'university',
    campus_type: 'main',
    enrollment: 10847,
    international_students: 380,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#FFB81C',
    website: 'https://www.angelo.edu',
    aliases: ['ASU', 'Rams'],
  },
  {
    id: 'texas-southern',
    name: 'Texas Southern University',
    short_name: 'Texas Southern',
    city: 'Houston',
    state: 'TX',
    zip_code: '77004',
    latitude: 29.7231,
    longitude: -95.3617,
    type: 'university',
    campus_type: 'main',
    enrollment: 9847,
    international_students: 480,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#808080',
    website: 'https://www.tsu.edu',
    aliases: ['TSU', 'Tigers'],
  },
  {
    id: 'texas-womans',
    name: "Texas Woman's University",
    short_name: 'TWU',
    city: 'Denton',
    state: 'TX',
    zip_code: '76204',
    latitude: 33.2297,
    longitude: -97.1322,
    type: 'university',
    campus_type: 'main',
    enrollment: 16247,
    international_students: 1200,
    is_public: true,
    primary_color: '#8B0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.twu.edu',
    aliases: ['Pioneers'],
  },
];

export const ALL_TEXAS = [...UT_SYSTEM, ...TAMU_SYSTEM, ...TEXAS_OTHER];

export default ALL_TEXAS;
