// ============================================================================
// ADDITIONAL TOP US UNIVERSITIES
// Universities ranked in US Top 100-200 not yet included in other files
// Focus on schools with high international student enrollment
// ============================================================================

import { University } from './types';

// ============================================================================
// TOP PRIVATE UNIVERSITIES (Additional)
// ============================================================================
export const TOP_PRIVATE_ADDITIONAL: University[] = [
  {
    id: 'vanderbilt',
    name: 'Vanderbilt University',
    short_name: 'Vanderbilt',
    city: 'Nashville',
    state: 'TN',
    country: 'US',
    zip_code: '37235',
    latitude: 36.1447,
    longitude: -86.8027,
    type: 'university',
    campus_type: 'main',
    enrollment: 13710,
    international_students: 1800,
    is_public: false,
    primary_color: '#866D4B',
    secondary_color: '#000000',
    website: 'https://www.vanderbilt.edu',
    aliases: ['Vandy', 'Commodores'],
  },
  {
    id: 'rice',
    name: 'Rice University',
    short_name: 'Rice',
    city: 'Houston',
    state: 'TX',
    country: 'US',
    zip_code: '77005',
    latitude: 29.7174,
    longitude: -95.4018,
    type: 'university',
    campus_type: 'main',
    enrollment: 8285,
    international_students: 1900,
    is_public: false,
    primary_color: '#00205B',
    secondary_color: '#C1C6C8',
    website: 'https://www.rice.edu',
    aliases: ['Owls'],
  },
  {
    id: 'notre-dame',
    name: 'University of Notre Dame',
    short_name: 'Notre Dame',
    city: 'Notre Dame',
    state: 'IN',
    country: 'US',
    zip_code: '46556',
    latitude: 41.7002,
    longitude: -86.2379,
    type: 'university',
    campus_type: 'main',
    enrollment: 12681,
    international_students: 1200,
    is_public: false,
    primary_color: '#0C2340',
    secondary_color: '#C99700',
    website: 'https://www.nd.edu',
    aliases: ['ND', 'Fighting Irish'],
  },
  {
    id: 'washu',
    name: 'Washington University in St. Louis',
    short_name: 'WashU',
    city: 'St. Louis',
    state: 'MO',
    country: 'US',
    zip_code: '63130',
    latitude: 38.6488,
    longitude: -90.3108,
    type: 'university',
    campus_type: 'main',
    enrollment: 16019,
    international_students: 3200,
    is_public: false,
    primary_color: '#A51417',
    secondary_color: '#007360',
    website: 'https://wustl.edu',
    aliases: ['WashU', 'WUSTL', 'Bears'],
  },
  {
    id: 'emory',
    name: 'Emory University',
    short_name: 'Emory',
    city: 'Atlanta',
    state: 'GA',
    country: 'US',
    zip_code: '30322',
    latitude: 33.7925,
    longitude: -84.3246,
    type: 'university',
    campus_type: 'main',
    enrollment: 15451,
    international_students: 2600,
    is_public: false,
    primary_color: '#012169',
    secondary_color: '#B58500',
    website: 'https://www.emory.edu',
    aliases: ['Eagles'],
  },
  {
    id: 'wake-forest',
    name: 'Wake Forest University',
    short_name: 'Wake Forest',
    city: 'Winston-Salem',
    state: 'NC',
    country: 'US',
    zip_code: '27109',
    latitude: 36.1337,
    longitude: -80.2768,
    type: 'university',
    campus_type: 'main',
    enrollment: 8941,
    international_students: 850,
    is_public: false,
    primary_color: '#9E7E38',
    secondary_color: '#000000',
    website: 'https://www.wfu.edu',
    aliases: ['WFU', 'Demon Deacons'],
  },
  {
    id: 'tufts',
    name: 'Tufts University',
    short_name: 'Tufts',
    city: 'Medford',
    state: 'MA',
    country: 'US',
    zip_code: '02155',
    latitude: 42.4085,
    longitude: -71.1183,
    type: 'university',
    campus_type: 'main',
    enrollment: 12180,
    international_students: 2100,
    is_public: false,
    primary_color: '#3E8EDE',
    secondary_color: '#6C4123',
    website: 'https://www.tufts.edu',
    aliases: ['Jumbos'],
  },
  {
    id: 'tulane',
    name: 'Tulane University',
    short_name: 'Tulane',
    city: 'New Orleans',
    state: 'LA',
    country: 'US',
    zip_code: '70118',
    latitude: 29.9399,
    longitude: -90.1209,
    type: 'university',
    campus_type: 'main',
    enrollment: 14563,
    international_students: 1400,
    is_public: false,
    primary_color: '#006747',
    secondary_color: '#87CEEB',
    website: 'https://tulane.edu',
    aliases: ['Green Wave'],
  },
  {
    id: 'case-western',
    name: 'Case Western Reserve University',
    short_name: 'Case Western',
    city: 'Cleveland',
    state: 'OH',
    country: 'US',
    zip_code: '44106',
    latitude: 41.5044,
    longitude: -81.6081,
    type: 'university',
    campus_type: 'main',
    enrollment: 11664,
    international_students: 2800,
    is_public: false,
    primary_color: '#0A304E',
    secondary_color: '#FFFFFF',
    website: 'https://www.case.edu',
    aliases: ['CWRU', 'Spartans'],
  },
  {
    id: 'miami-fl',
    name: 'University of Miami',
    short_name: 'Miami',
    city: 'Coral Gables',
    state: 'FL',
    country: 'US',
    zip_code: '33146',
    latitude: 25.7174,
    longitude: -80.2794,
    type: 'university',
    campus_type: 'main',
    enrollment: 19096,
    international_students: 3200,
    is_public: false,
    primary_color: '#F47321',
    secondary_color: '#005030',
    website: 'https://www.miami.edu',
    aliases: ['UM', 'Hurricanes', 'The U'],
  },
  {
    id: 'boston-college',
    name: 'Boston College',
    short_name: 'BC',
    city: 'Chestnut Hill',
    state: 'MA',
    country: 'US',
    zip_code: '02467',
    latitude: 42.3355,
    longitude: -71.1685,
    type: 'university',
    campus_type: 'main',
    enrollment: 14957,
    international_students: 1200,
    is_public: false,
    primary_color: '#8C2633',
    secondary_color: '#9D8441',
    website: 'https://www.bc.edu',
    aliases: ['Eagles'],
  },
  {
    id: 'brandeis',
    name: 'Brandeis University',
    short_name: 'Brandeis',
    city: 'Waltham',
    state: 'MA',
    country: 'US',
    zip_code: '02453',
    latitude: 42.3658,
    longitude: -71.2595,
    type: 'university',
    campus_type: 'main',
    enrollment: 5825,
    international_students: 1400,
    is_public: false,
    primary_color: '#003478',
    secondary_color: '#FFFFFF',
    website: 'https://www.brandeis.edu',
    aliases: ['Judges'],
  },
  {
    id: 'rochester',
    name: 'University of Rochester',
    short_name: 'Rochester',
    city: 'Rochester',
    state: 'NY',
    country: 'US',
    zip_code: '14627',
    latitude: 43.1289,
    longitude: -77.6285,
    type: 'university',
    campus_type: 'main',
    enrollment: 11858,
    international_students: 3800,
    is_public: false,
    primary_color: '#003B71',
    secondary_color: '#FFD200',
    website: 'https://www.rochester.edu',
    aliases: ['U of R', 'Yellowjackets'],
  },
  {
    id: 'villanova',
    name: 'Villanova University',
    short_name: 'Villanova',
    city: 'Villanova',
    state: 'PA',
    country: 'US',
    zip_code: '19085',
    latitude: 40.0345,
    longitude: -75.3378,
    type: 'university',
    campus_type: 'main',
    enrollment: 10931,
    international_students: 650,
    is_public: false,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.villanova.edu',
    aliases: ['Nova', 'Wildcats'],
  },
  {
    id: 'lehigh',
    name: 'Lehigh University',
    short_name: 'Lehigh',
    city: 'Bethlehem',
    state: 'PA',
    country: 'US',
    zip_code: '18015',
    latitude: 40.6068,
    longitude: -75.3785,
    type: 'university',
    campus_type: 'main',
    enrollment: 7316,
    international_students: 820,
    is_public: false,
    primary_color: '#502D0E',
    secondary_color: '#FFFFFF',
    website: 'https://www.lehigh.edu',
    aliases: ['Mountain Hawks'],
  },
  {
    id: 'syracuse',
    name: 'Syracuse University',
    short_name: 'Syracuse',
    city: 'Syracuse',
    state: 'NY',
    country: 'US',
    zip_code: '13244',
    latitude: 43.0392,
    longitude: -76.1351,
    type: 'university',
    campus_type: 'main',
    enrollment: 22850,
    international_students: 3200,
    is_public: false,
    primary_color: '#F76900',
    secondary_color: '#002D72',
    website: 'https://www.syracuse.edu',
    aliases: ['Cuse', 'Orange'],
  },
  {
    id: 'gw',
    name: 'George Washington University',
    short_name: 'GW',
    city: 'Washington',
    state: 'DC',
    country: 'US',
    zip_code: '20052',
    latitude: 38.8997,
    longitude: -77.0488,
    type: 'university',
    campus_type: 'main',
    enrollment: 26212,
    international_students: 3800,
    is_public: false,
    primary_color: '#004065',
    secondary_color: '#AA9868',
    website: 'https://www.gwu.edu',
    aliases: ['GWU', 'George Washington', 'Colonials'],
  },
  {
    id: 'pepperdine',
    name: 'Pepperdine University',
    short_name: 'Pepperdine',
    city: 'Malibu',
    state: 'CA',
    country: 'US',
    zip_code: '90263',
    latitude: 34.0394,
    longitude: -118.7053,
    type: 'university',
    campus_type: 'main',
    enrollment: 9067,
    international_students: 1100,
    is_public: false,
    primary_color: '#0D2B52',
    secondary_color: '#ED7D31',
    website: 'https://www.pepperdine.edu',
    aliases: ['Waves'],
  },
  {
    id: 'santa-clara',
    name: 'Santa Clara University',
    short_name: 'Santa Clara',
    city: 'Santa Clara',
    state: 'CA',
    country: 'US',
    zip_code: '95053',
    latitude: 37.3496,
    longitude: -121.9390,
    type: 'university',
    campus_type: 'main',
    enrollment: 9015,
    international_students: 920,
    is_public: false,
    primary_color: '#862633',
    secondary_color: '#FFFFFF',
    website: 'https://www.scu.edu',
    aliases: ['SCU', 'Broncos'],
  },
  {
    id: 'lmu',
    name: 'Loyola Marymount University',
    short_name: 'LMU',
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    zip_code: '90045',
    latitude: 33.9690,
    longitude: -118.4184,
    type: 'university',
    campus_type: 'main',
    enrollment: 9804,
    international_students: 1050,
    is_public: false,
    primary_color: '#862633',
    secondary_color: '#003DA5',
    website: 'https://www.lmu.edu',
    aliases: ['Loyola', 'Lions'],
  },
  {
    id: 'usd',
    name: 'University of San Diego',
    short_name: 'San Diego',
    city: 'San Diego',
    state: 'CA',
    country: 'US',
    zip_code: '92110',
    latitude: 32.7715,
    longitude: -117.1883,
    type: 'university',
    campus_type: 'main',
    enrollment: 8905,
    international_students: 780,
    is_public: false,
    primary_color: '#002855',
    secondary_color: '#A5B8D0',
    website: 'https://www.sandiego.edu',
    aliases: ['USD', 'Toreros'],
  },
  {
    id: 'marquette',
    name: 'Marquette University',
    short_name: 'Marquette',
    city: 'Milwaukee',
    state: 'WI',
    country: 'US',
    zip_code: '53233',
    latitude: 43.0383,
    longitude: -87.9298,
    type: 'university',
    campus_type: 'main',
    enrollment: 11442,
    international_students: 750,
    is_public: false,
    primary_color: '#003366',
    secondary_color: '#FFCC00',
    website: 'https://www.marquette.edu',
    aliases: ['Golden Eagles'],
  },
  {
    id: 'smu',
    name: 'Southern Methodist University',
    short_name: 'SMU',
    city: 'Dallas',
    state: 'TX',
    country: 'US',
    zip_code: '75205',
    latitude: 32.8412,
    longitude: -96.7840,
    type: 'university',
    campus_type: 'main',
    enrollment: 12384,
    international_students: 1500,
    is_public: false,
    primary_color: '#CC0035',
    secondary_color: '#003DA5',
    website: 'https://www.smu.edu',
    aliases: ['Mustangs'],
  },
  {
    id: 'tcu',
    name: 'Texas Christian University',
    short_name: 'TCU',
    city: 'Fort Worth',
    state: 'TX',
    country: 'US',
    zip_code: '76129',
    latitude: 32.7098,
    longitude: -97.3634,
    type: 'university',
    campus_type: 'main',
    enrollment: 12251,
    international_students: 780,
    is_public: false,
    primary_color: '#4D1979',
    secondary_color: '#A3A9AC',
    website: 'https://www.tcu.edu',
    aliases: ['Horned Frogs'],
  },
  {
    id: 'du',
    name: 'University of Denver',
    short_name: 'Denver',
    city: 'Denver',
    state: 'CO',
    country: 'US',
    zip_code: '80208',
    latitude: 39.6769,
    longitude: -104.9619,
    type: 'university',
    campus_type: 'main',
    enrollment: 11767,
    international_students: 1400,
    is_public: false,
    primary_color: '#8B2332',
    secondary_color: '#B5A36A',
    website: 'https://www.du.edu',
    aliases: ['DU', 'Pioneers'],
  },
  {
    id: 'drexel',
    name: 'Drexel University',
    short_name: 'Drexel',
    city: 'Philadelphia',
    state: 'PA',
    country: 'US',
    zip_code: '19104',
    latitude: 39.9550,
    longitude: -75.1897,
    type: 'university',
    campus_type: 'main',
    enrollment: 24190,
    international_students: 4200,
    is_public: false,
    primary_color: '#07294D',
    secondary_color: '#FFC600',
    website: 'https://www.drexel.edu',
    aliases: ['Dragons'],
  },
  {
    id: 'howard',
    name: 'Howard University',
    short_name: 'Howard',
    city: 'Washington',
    state: 'DC',
    country: 'US',
    zip_code: '20059',
    latitude: 38.9217,
    longitude: -77.0195,
    type: 'university',
    campus_type: 'main',
    enrollment: 9399,
    international_students: 680,
    is_public: false,
    primary_color: '#003A63',
    secondary_color: '#E51937',
    website: 'https://www.howard.edu',
    aliases: ['Bison'],
  },
  {
    id: 'american',
    name: 'American University',
    short_name: 'American',
    city: 'Washington',
    state: 'DC',
    country: 'US',
    zip_code: '20016',
    latitude: 38.9376,
    longitude: -77.0873,
    type: 'university',
    campus_type: 'main',
    enrollment: 14491,
    international_students: 2200,
    is_public: false,
    primary_color: '#CC0033',
    secondary_color: '#002B5C',
    website: 'https://www.american.edu',
    aliases: ['AU', 'Eagles'],
  },
  {
    id: 'fordham',
    name: 'Fordham University',
    short_name: 'Fordham',
    city: 'Bronx',
    state: 'NY',
    country: 'US',
    zip_code: '10458',
    latitude: 40.8622,
    longitude: -73.8855,
    type: 'university',
    campus_type: 'main',
    enrollment: 16935,
    international_students: 1800,
    is_public: false,
    primary_color: '#8A0034',
    secondary_color: '#FFFFFF',
    website: 'https://www.fordham.edu',
    aliases: ['Rams'],
  },
  {
    id: 'stevens',
    name: 'Stevens Institute of Technology',
    short_name: 'Stevens',
    city: 'Hoboken',
    state: 'NJ',
    country: 'US',
    zip_code: '07030',
    latitude: 40.7440,
    longitude: -74.0255,
    type: 'university',
    campus_type: 'main',
    enrollment: 8014,
    international_students: 2400,
    is_public: false,
    primary_color: '#9E1B32',
    secondary_color: '#A5ACAF',
    website: 'https://www.stevens.edu',
    aliases: ['SIT', 'Ducks'],
  },
  {
    id: 'rpi',
    name: 'Rensselaer Polytechnic Institute',
    short_name: 'RPI',
    city: 'Troy',
    state: 'NY',
    country: 'US',
    zip_code: '12180',
    latitude: 42.7298,
    longitude: -73.6789,
    type: 'university',
    campus_type: 'main',
    enrollment: 7761,
    international_students: 1800,
    is_public: false,
    primary_color: '#D6001C',
    secondary_color: '#FFFFFF',
    website: 'https://www.rpi.edu',
    aliases: ['Rensselaer', 'Engineers'],
  },
  {
    id: 'wpi',
    name: 'Worcester Polytechnic Institute',
    short_name: 'WPI',
    city: 'Worcester',
    state: 'MA',
    country: 'US',
    zip_code: '01609',
    latitude: 42.2746,
    longitude: -71.8063,
    type: 'university',
    campus_type: 'main',
    enrollment: 7094,
    international_students: 1600,
    is_public: false,
    primary_color: '#AC2B37',
    secondary_color: '#A9B0B7',
    website: 'https://www.wpi.edu',
    aliases: ['Worcester Poly', 'Engineers'],
  },
  {
    id: 'rit',
    name: 'Rochester Institute of Technology',
    short_name: 'RIT',
    city: 'Rochester',
    state: 'NY',
    country: 'US',
    zip_code: '14623',
    latitude: 43.0849,
    longitude: -77.6744,
    type: 'university',
    campus_type: 'main',
    enrollment: 18599,
    international_students: 3200,
    is_public: false,
    primary_color: '#F36E21',
    secondary_color: '#000000',
    website: 'https://www.rit.edu',
    aliases: ['Tigers'],
  },
  {
    id: 'iit',
    name: 'Illinois Institute of Technology',
    short_name: 'IIT',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    zip_code: '60616',
    latitude: 41.8349,
    longitude: -87.6270,
    type: 'university',
    campus_type: 'main',
    enrollment: 6954,
    international_students: 2800,
    is_public: false,
    primary_color: '#9E1B32',
    secondary_color: '#000000',
    website: 'https://www.iit.edu',
    aliases: ['Illinois Tech', 'Scarlet Hawks'],
  },
  {
    id: 'depaul',
    name: 'DePaul University',
    short_name: 'DePaul',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    zip_code: '60604',
    latitude: 41.8786,
    longitude: -87.6270,
    type: 'university',
    campus_type: 'main',
    enrollment: 21053,
    international_students: 1800,
    is_public: false,
    primary_color: '#003DA5',
    secondary_color: '#CC0000',
    website: 'https://www.depaul.edu',
    aliases: ['Blue Demons'],
  },
  {
    id: 'loyola-chicago',
    name: 'Loyola University Chicago',
    short_name: 'Loyola Chicago',
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    zip_code: '60660',
    latitude: 41.9998,
    longitude: -87.6581,
    type: 'university',
    campus_type: 'main',
    enrollment: 17007,
    international_students: 1200,
    is_public: false,
    primary_color: '#8E0028',
    secondary_color: '#9D8441',
    website: 'https://www.luc.edu',
    aliases: ['LUC', 'Ramblers'],
  },
  {
    id: 'st-louis',
    name: 'Saint Louis University',
    short_name: 'SLU',
    city: 'St. Louis',
    state: 'MO',
    country: 'US',
    zip_code: '63103',
    latitude: 38.6352,
    longitude: -90.2346,
    type: 'university',
    campus_type: 'main',
    enrollment: 12492,
    international_students: 1100,
    is_public: false,
    primary_color: '#003DA5',
    secondary_color: '#FFFFFF',
    website: 'https://www.slu.edu',
    aliases: ['Saint Louis', 'Billikens'],
  },
  {
    id: 'creighton',
    name: 'Creighton University',
    short_name: 'Creighton',
    city: 'Omaha',
    state: 'NE',
    country: 'US',
    zip_code: '68178',
    latitude: 41.2619,
    longitude: -95.9346,
    type: 'university',
    campus_type: 'main',
    enrollment: 8836,
    international_students: 480,
    is_public: false,
    primary_color: '#003DA5',
    secondary_color: '#FFFFFF',
    website: 'https://www.creighton.edu',
    aliases: ['Bluejays'],
  },
  {
    id: 'gonzaga',
    name: 'Gonzaga University',
    short_name: 'Gonzaga',
    city: 'Spokane',
    state: 'WA',
    country: 'US',
    zip_code: '99258',
    latitude: 47.6671,
    longitude: -117.4024,
    type: 'university',
    campus_type: 'main',
    enrollment: 7654,
    international_students: 350,
    is_public: false,
    primary_color: '#002967',
    secondary_color: '#C8102E',
    website: 'https://www.gonzaga.edu',
    aliases: ['Zags', 'Bulldogs'],
  },
  {
    id: 'byu',
    name: 'Brigham Young University',
    short_name: 'BYU',
    city: 'Provo',
    state: 'UT',
    country: 'US',
    zip_code: '84602',
    latitude: 40.2519,
    longitude: -111.6493,
    type: 'university',
    campus_type: 'main',
    enrollment: 36000,
    international_students: 2400,
    is_public: false,
    primary_color: '#002E5D',
    secondary_color: '#FFFFFF',
    website: 'https://www.byu.edu',
    aliases: ['Brigham Young', 'Cougars'],
  },
];

// ============================================================================
// ADDITIONAL STATE UNIVERSITIES (Not in other files)
// ============================================================================
export const STATE_UNIVERSITIES_ADDITIONAL: University[] = [
  // KANSAS
  {
    id: 'ku',
    name: 'University of Kansas',
    short_name: 'Kansas',
    city: 'Lawrence',
    state: 'KS',
    country: 'US',
    zip_code: '66045',
    latitude: 38.9543,
    longitude: -95.2558,
    type: 'university',
    campus_type: 'main',
    enrollment: 27259,
    international_students: 2100,
    is_public: true,
    primary_color: '#0051BA',
    secondary_color: '#E8000D',
    website: 'https://www.ku.edu',
    aliases: ['KU', 'Jayhawks'],
  },
  {
    id: 'ksu',
    name: 'Kansas State University',
    short_name: 'K-State',
    city: 'Manhattan',
    state: 'KS',
    country: 'US',
    zip_code: '66506',
    latitude: 39.1836,
    longitude: -96.5717,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 1600,
    is_public: true,
    primary_color: '#512888',
    secondary_color: '#FFFFFF',
    website: 'https://www.k-state.edu',
    aliases: ['KSU', 'Wildcats'],
  },
  // OKLAHOMA
  {
    id: 'ou',
    name: 'University of Oklahoma',
    short_name: 'Oklahoma',
    city: 'Norman',
    state: 'OK',
    country: 'US',
    zip_code: '73019',
    latitude: 35.2058,
    longitude: -97.4457,
    type: 'university',
    campus_type: 'main',
    enrollment: 32147,
    international_students: 1800,
    is_public: true,
    primary_color: '#841617',
    secondary_color: '#FFFFFF',
    website: 'https://www.ou.edu',
    aliases: ['OU', 'Sooners'],
  },
  {
    id: 'osu-ok',
    name: 'Oklahoma State University',
    short_name: 'Oklahoma State',
    city: 'Stillwater',
    state: 'OK',
    country: 'US',
    zip_code: '74078',
    latitude: 36.1261,
    longitude: -97.0715,
    type: 'university',
    campus_type: 'main',
    enrollment: 24649,
    international_students: 2200,
    is_public: true,
    primary_color: '#FF7300',
    secondary_color: '#000000',
    website: 'https://go.okstate.edu',
    aliases: ['OSU', 'Cowboys'],
  },
  // MISSOURI
  {
    id: 'mizzou',
    name: 'University of Missouri',
    short_name: 'Mizzou',
    city: 'Columbia',
    state: 'MO',
    country: 'US',
    zip_code: '65211',
    latitude: 38.9404,
    longitude: -92.3277,
    type: 'university',
    campus_type: 'main',
    enrollment: 31103,
    international_students: 2400,
    is_public: true,
    primary_color: '#F1B82D',
    secondary_color: '#000000',
    website: 'https://missouri.edu',
    aliases: ['Missouri', 'Tigers'],
  },
  {
    id: 'umkc',
    name: 'University of Missouri-Kansas City',
    short_name: 'UMKC',
    system_name: 'University of Missouri',
    city: 'Kansas City',
    state: 'MO',
    country: 'US',
    zip_code: '64110',
    latitude: 39.0330,
    longitude: -94.5757,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 1200,
    is_public: true,
    primary_color: '#0047BB',
    secondary_color: '#FFB81C',
    website: 'https://www.umkc.edu',
    aliases: ['Kansas City', 'Roos'],
  },
  {
    id: 'missouri-st',
    name: 'Missouri State University',
    short_name: 'Missouri State',
    city: 'Springfield',
    state: 'MO',
    country: 'US',
    zip_code: '65897',
    latitude: 37.2050,
    longitude: -93.2851,
    type: 'university',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 1100,
    is_public: true,
    primary_color: '#5F0023',
    secondary_color: '#FFFFFF',
    website: 'https://www.missouristate.edu',
    aliases: ['MSU', 'Bears'],
  },
  // ARKANSAS
  {
    id: 'uark',
    name: 'University of Arkansas',
    short_name: 'Arkansas',
    city: 'Fayetteville',
    state: 'AR',
    country: 'US',
    zip_code: '72701',
    latitude: 36.0677,
    longitude: -94.1743,
    type: 'university',
    campus_type: 'main',
    enrollment: 29068,
    international_students: 1600,
    is_public: true,
    primary_color: '#9D2235',
    secondary_color: '#FFFFFF',
    website: 'https://www.uark.edu',
    aliases: ['Razorbacks', 'UA'],
  },
  // LOUISIANA
  {
    id: 'lsu',
    name: 'Louisiana State University',
    short_name: 'LSU',
    city: 'Baton Rouge',
    state: 'LA',
    country: 'US',
    zip_code: '70803',
    latitude: 30.4133,
    longitude: -91.1800,
    type: 'university',
    campus_type: 'main',
    enrollment: 35093,
    international_students: 2200,
    is_public: true,
    primary_color: '#461D7C',
    secondary_color: '#FDD023',
    website: 'https://www.lsu.edu',
    aliases: ['Louisiana State', 'Tigers'],
  },
  {
    id: 'uno',
    name: 'University of New Orleans',
    short_name: 'UNO',
    city: 'New Orleans',
    state: 'LA',
    country: 'US',
    zip_code: '70148',
    latitude: 30.0266,
    longitude: -90.0669,
    type: 'university',
    campus_type: 'main',
    enrollment: 8100,
    international_students: 650,
    is_public: true,
    primary_color: '#003399',
    secondary_color: '#C0C0C0',
    website: 'https://www.uno.edu',
    aliases: ['New Orleans', 'Privateers'],
  },
  // TENNESSEE
  {
    id: 'utk',
    name: 'University of Tennessee',
    short_name: 'Tennessee',
    city: 'Knoxville',
    state: 'TN',
    country: 'US',
    zip_code: '37996',
    latitude: 35.9544,
    longitude: -83.9295,
    type: 'university',
    campus_type: 'main',
    enrollment: 31701,
    international_students: 1800,
    is_public: true,
    primary_color: '#FF8200',
    secondary_color: '#FFFFFF',
    website: 'https://www.utk.edu',
    aliases: ['UTK', 'Volunteers', 'Vols'],
  },
  {
    id: 'memphis',
    name: 'University of Memphis',
    short_name: 'Memphis',
    city: 'Memphis',
    state: 'TN',
    country: 'US',
    zip_code: '38152',
    latitude: 35.1186,
    longitude: -89.9371,
    type: 'university',
    campus_type: 'main',
    enrollment: 21917,
    international_students: 1400,
    is_public: true,
    primary_color: '#003087',
    secondary_color: '#8A8D8F',
    website: 'https://www.memphis.edu',
    aliases: ['U of M', 'Tigers'],
  },
  // KENTUCKY
  {
    id: 'uk',
    name: 'University of Kentucky',
    short_name: 'Kentucky',
    city: 'Lexington',
    state: 'KY',
    country: 'US',
    zip_code: '40506',
    latitude: 38.0308,
    longitude: -84.5040,
    type: 'university',
    campus_type: 'main',
    enrollment: 30545,
    international_students: 2100,
    is_public: true,
    primary_color: '#0033A0',
    secondary_color: '#FFFFFF',
    website: 'https://www.uky.edu',
    aliases: ['UK', 'Wildcats'],
  },
  {
    id: 'louisville',
    name: 'University of Louisville',
    short_name: 'Louisville',
    city: 'Louisville',
    state: 'KY',
    country: 'US',
    zip_code: '40292',
    latitude: 38.2113,
    longitude: -85.7588,
    type: 'university',
    campus_type: 'main',
    enrollment: 22640,
    international_students: 1600,
    is_public: true,
    primary_color: '#AD0000',
    secondary_color: '#000000',
    website: 'https://www.louisville.edu',
    aliases: ['UofL', 'Cardinals'],
  },
  // ALABAMA
  {
    id: 'alabama',
    name: 'University of Alabama',
    short_name: 'Alabama',
    city: 'Tuscaloosa',
    state: 'AL',
    country: 'US',
    zip_code: '35487',
    latitude: 33.2140,
    longitude: -87.5391,
    type: 'university',
    campus_type: 'main',
    enrollment: 38390,
    international_students: 1800,
    is_public: true,
    primary_color: '#9E1B32',
    secondary_color: '#FFFFFF',
    website: 'https://www.ua.edu',
    aliases: ['Bama', 'Crimson Tide'],
  },
  {
    id: 'auburn',
    name: 'Auburn University',
    short_name: 'Auburn',
    city: 'Auburn',
    state: 'AL',
    country: 'US',
    zip_code: '36849',
    latitude: 32.6035,
    longitude: -85.4869,
    type: 'university',
    campus_type: 'main',
    enrollment: 31526,
    international_students: 1600,
    is_public: true,
    primary_color: '#0C2340',
    secondary_color: '#E87722',
    website: 'https://www.auburn.edu',
    aliases: ['Tigers', 'War Eagles'],
  },
  {
    id: 'uab',
    name: 'University of Alabama at Birmingham',
    short_name: 'UAB',
    city: 'Birmingham',
    state: 'AL',
    country: 'US',
    zip_code: '35294',
    latitude: 33.5021,
    longitude: -86.8006,
    type: 'university',
    campus_type: 'main',
    enrollment: 22563,
    international_students: 1200,
    is_public: true,
    primary_color: '#1E6B52',
    secondary_color: '#FFD200',
    website: 'https://www.uab.edu',
    aliases: ['Blazers'],
  },
  // MISSISSIPPI
  {
    id: 'ole-miss',
    name: 'University of Mississippi',
    short_name: 'Ole Miss',
    city: 'University',
    state: 'MS',
    country: 'US',
    zip_code: '38677',
    latitude: 34.3656,
    longitude: -89.5345,
    type: 'university',
    campus_type: 'main',
    enrollment: 22456,
    international_students: 800,
    is_public: true,
    primary_color: '#14213D',
    secondary_color: '#CE1126',
    website: 'https://www.olemiss.edu',
    aliases: ['Mississippi', 'Rebels'],
  },
  {
    id: 'msstate',
    name: 'Mississippi State University',
    short_name: 'Mississippi State',
    city: 'Starkville',
    state: 'MS',
    country: 'US',
    zip_code: '39762',
    latitude: 33.4552,
    longitude: -88.7896,
    type: 'university',
    campus_type: 'main',
    enrollment: 22986,
    international_students: 1100,
    is_public: true,
    primary_color: '#660000',
    secondary_color: '#FFFFFF',
    website: 'https://www.msstate.edu',
    aliases: ['MSU', 'Bulldogs'],
  },
  // SOUTH CAROLINA
  {
    id: 'usc-sc',
    name: 'University of South Carolina',
    short_name: 'South Carolina',
    city: 'Columbia',
    state: 'SC',
    country: 'US',
    zip_code: '29208',
    latitude: 33.9940,
    longitude: -81.0277,
    type: 'university',
    campus_type: 'main',
    enrollment: 35364,
    international_students: 1400,
    is_public: true,
    primary_color: '#73000A',
    secondary_color: '#000000',
    website: 'https://www.sc.edu',
    aliases: ['USC', 'Gamecocks'],
  },
  {
    id: 'clemson',
    name: 'Clemson University',
    short_name: 'Clemson',
    city: 'Clemson',
    state: 'SC',
    country: 'US',
    zip_code: '29634',
    latitude: 34.6834,
    longitude: -82.8374,
    type: 'university',
    campus_type: 'main',
    enrollment: 26406,
    international_students: 1800,
    is_public: true,
    primary_color: '#F56600',
    secondary_color: '#522D80',
    website: 'https://www.clemson.edu',
    aliases: ['Tigers'],
  },
  // UTAH
  {
    id: 'utah',
    name: 'University of Utah',
    short_name: 'Utah',
    city: 'Salt Lake City',
    state: 'UT',
    country: 'US',
    zip_code: '84112',
    latitude: 40.7649,
    longitude: -111.8421,
    type: 'university',
    campus_type: 'main',
    enrollment: 34800,
    international_students: 3200,
    is_public: true,
    primary_color: '#CC0000',
    secondary_color: '#FFFFFF',
    website: 'https://www.utah.edu',
    aliases: ['U of U', 'Utes'],
  },
  {
    id: 'usu',
    name: 'Utah State University',
    short_name: 'Utah State',
    city: 'Logan',
    state: 'UT',
    country: 'US',
    zip_code: '84322',
    latitude: 41.7457,
    longitude: -111.8097,
    type: 'university',
    campus_type: 'main',
    enrollment: 27000,
    international_students: 1200,
    is_public: true,
    primary_color: '#0F2439',
    secondary_color: '#FFFFFF',
    website: 'https://www.usu.edu',
    aliases: ['USU', 'Aggies'],
  },
  // NEW MEXICO
  {
    id: 'unm',
    name: 'University of New Mexico',
    short_name: 'New Mexico',
    city: 'Albuquerque',
    state: 'NM',
    country: 'US',
    zip_code: '87131',
    latitude: 35.0844,
    longitude: -106.6189,
    type: 'university',
    campus_type: 'main',
    enrollment: 25488,
    international_students: 1600,
    is_public: true,
    primary_color: '#BA0C2F',
    secondary_color: '#A7A8AA',
    website: 'https://www.unm.edu',
    aliases: ['UNM', 'Lobos'],
  },
  {
    id: 'nmsu',
    name: 'New Mexico State University',
    short_name: 'NMSU',
    city: 'Las Cruces',
    state: 'NM',
    country: 'US',
    zip_code: '88003',
    latitude: 32.2824,
    longitude: -106.7470,
    type: 'university',
    campus_type: 'main',
    enrollment: 12500,
    international_students: 950,
    is_public: true,
    primary_color: '#8C0037',
    secondary_color: '#FFFFFF',
    website: 'https://www.nmsu.edu',
    aliases: ['Aggies'],
  },
  // IDAHO
  {
    id: 'uidaho',
    name: 'University of Idaho',
    short_name: 'Idaho',
    city: 'Moscow',
    state: 'ID',
    country: 'US',
    zip_code: '83844',
    latitude: 46.7260,
    longitude: -117.0142,
    type: 'university',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 650,
    is_public: true,
    primary_color: '#B5985A',
    secondary_color: '#000000',
    website: 'https://www.uidaho.edu',
    aliases: ['U of I', 'Vandals'],
  },
  {
    id: 'bsu',
    name: 'Boise State University',
    short_name: 'Boise State',
    city: 'Boise',
    state: 'ID',
    country: 'US',
    zip_code: '83725',
    latitude: 43.6027,
    longitude: -116.2014,
    type: 'university',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 1200,
    is_public: true,
    primary_color: '#0033A0',
    secondary_color: '#F47920',
    website: 'https://www.boisestate.edu',
    aliases: ['BSU', 'Broncos'],
  },
  // MONTANA
  {
    id: 'umt',
    name: 'University of Montana',
    short_name: 'Montana',
    city: 'Missoula',
    state: 'MT',
    country: 'US',
    zip_code: '59812',
    latitude: 46.8625,
    longitude: -113.9850,
    type: 'university',
    campus_type: 'main',
    enrollment: 9400,
    international_students: 350,
    is_public: true,
    primary_color: '#632631',
    secondary_color: '#999999',
    website: 'https://www.umt.edu',
    aliases: ['UM', 'Grizzlies'],
  },
  {
    id: 'msu-mt',
    name: 'Montana State University',
    short_name: 'Montana State',
    city: 'Bozeman',
    state: 'MT',
    country: 'US',
    zip_code: '59717',
    latitude: 45.6677,
    longitude: -111.0456,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 650,
    is_public: true,
    primary_color: '#003865',
    secondary_color: '#D4A843',
    website: 'https://www.montana.edu',
    aliases: ['MSU', 'Bobcats'],
  },
  // WYOMING
  {
    id: 'uwyo',
    name: 'University of Wyoming',
    short_name: 'Wyoming',
    city: 'Laramie',
    state: 'WY',
    country: 'US',
    zip_code: '82071',
    latitude: 41.3149,
    longitude: -105.5666,
    type: 'university',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 850,
    is_public: true,
    primary_color: '#492F24',
    secondary_color: '#FFC425',
    website: 'https://www.uwyo.edu',
    aliases: ['UW', 'Cowboys'],
  },
  // NORTH & SOUTH DAKOTA
  {
    id: 'und',
    name: 'University of North Dakota',
    short_name: 'North Dakota',
    city: 'Grand Forks',
    state: 'ND',
    country: 'US',
    zip_code: '58202',
    latitude: 47.9212,
    longitude: -97.0736,
    type: 'university',
    campus_type: 'main',
    enrollment: 13500,
    international_students: 1200,
    is_public: true,
    primary_color: '#009A44',
    secondary_color: '#FFFFFF',
    website: 'https://www.und.edu',
    aliases: ['UND', 'Fighting Hawks'],
  },
  {
    id: 'ndsu',
    name: 'North Dakota State University',
    short_name: 'NDSU',
    city: 'Fargo',
    state: 'ND',
    country: 'US',
    zip_code: '58108',
    latitude: 46.8973,
    longitude: -96.8037,
    type: 'university',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 1400,
    is_public: true,
    primary_color: '#006338',
    secondary_color: '#FFC82E',
    website: 'https://www.ndsu.edu',
    aliases: ['Bison'],
  },
  {
    id: 'usd',
    name: 'University of South Dakota',
    short_name: 'South Dakota',
    city: 'Vermillion',
    state: 'SD',
    country: 'US',
    zip_code: '57069',
    latitude: 42.7882,
    longitude: -96.9289,
    type: 'university',
    campus_type: 'main',
    enrollment: 9700,
    international_students: 450,
    is_public: true,
    primary_color: '#C71C2D',
    secondary_color: '#FFFFFF',
    website: 'https://www.usd.edu',
    aliases: ['USD', 'Coyotes'],
  },
  {
    id: 'sdsu-sd',
    name: 'South Dakota State University',
    short_name: 'SDSU',
    city: 'Brookings',
    state: 'SD',
    country: 'US',
    zip_code: '57007',
    latitude: 44.3205,
    longitude: -96.7852,
    type: 'university',
    campus_type: 'main',
    enrollment: 11300,
    international_students: 600,
    is_public: true,
    primary_color: '#0033A0',
    secondary_color: '#FFCD00',
    website: 'https://www.sdstate.edu',
    aliases: ['Jackrabbits'],
  },
  // HAWAII & ALASKA
  {
    id: 'uh-manoa',
    name: 'University of Hawaii at Manoa',
    short_name: 'Hawaii',
    city: 'Honolulu',
    state: 'HI',
    country: 'US',
    zip_code: '96822',
    latitude: 21.2969,
    longitude: -157.8171,
    type: 'university',
    campus_type: 'main',
    enrollment: 17710,
    international_students: 2100,
    is_public: true,
    primary_color: '#024731',
    secondary_color: '#FFFFFF',
    website: 'https://www.hawaii.edu',
    aliases: ['UH', 'Rainbow Warriors'],
  },
  {
    id: 'uaf',
    name: 'University of Alaska Fairbanks',
    short_name: 'Alaska Fairbanks',
    city: 'Fairbanks',
    state: 'AK',
    country: 'US',
    zip_code: '99775',
    latitude: 64.8591,
    longitude: -147.8480,
    type: 'university',
    campus_type: 'main',
    enrollment: 7000,
    international_students: 420,
    is_public: true,
    primary_color: '#236192',
    secondary_color: '#FFCD00',
    website: 'https://www.uaf.edu',
    aliases: ['UAF', 'Nanooks'],
  },
  // CONNECTICUT
  {
    id: 'uconn',
    name: 'University of Connecticut',
    short_name: 'UConn',
    city: 'Storrs',
    state: 'CT',
    country: 'US',
    zip_code: '06269',
    latitude: 41.8084,
    longitude: -72.2495,
    type: 'university',
    campus_type: 'main',
    enrollment: 32257,
    international_students: 3200,
    is_public: true,
    primary_color: '#000E2F',
    secondary_color: '#FFFFFF',
    website: 'https://www.uconn.edu',
    aliases: ['Connecticut', 'Huskies'],
  },
  // MAINE
  {
    id: 'umaine',
    name: 'University of Maine',
    short_name: 'Maine',
    city: 'Orono',
    state: 'ME',
    country: 'US',
    zip_code: '04469',
    latitude: 44.9012,
    longitude: -68.6719,
    type: 'university',
    campus_type: 'main',
    enrollment: 11200,
    international_students: 580,
    is_public: true,
    primary_color: '#003263',
    secondary_color: '#B4D8E7',
    website: 'https://www.umaine.edu',
    aliases: ['UMaine', 'Black Bears'],
  },
  // VERMONT
  {
    id: 'uvm',
    name: 'University of Vermont',
    short_name: 'Vermont',
    city: 'Burlington',
    state: 'VT',
    country: 'US',
    zip_code: '05405',
    latitude: 44.4779,
    longitude: -73.1965,
    type: 'university',
    campus_type: 'main',
    enrollment: 13712,
    international_students: 680,
    is_public: true,
    primary_color: '#154734',
    secondary_color: '#FFB81C',
    website: 'https://www.uvm.edu',
    aliases: ['UVM', 'Catamounts'],
  },
  // RHODE ISLAND
  {
    id: 'uri',
    name: 'University of Rhode Island',
    short_name: 'Rhode Island',
    city: 'Kingston',
    state: 'RI',
    country: 'US',
    zip_code: '02881',
    latitude: 41.4833,
    longitude: -71.5266,
    type: 'university',
    campus_type: 'main',
    enrollment: 17389,
    international_students: 780,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#7BAFD4',
    website: 'https://www.uri.edu',
    aliases: ['URI', 'Rams'],
  },
  // DELAWARE
  {
    id: 'udel',
    name: 'University of Delaware',
    short_name: 'Delaware',
    city: 'Newark',
    state: 'DE',
    country: 'US',
    zip_code: '19716',
    latitude: 39.6778,
    longitude: -75.7506,
    type: 'university',
    campus_type: 'main',
    enrollment: 23000,
    international_students: 1800,
    is_public: true,
    primary_color: '#00539F',
    secondary_color: '#FFD200',
    website: 'https://www.udel.edu',
    aliases: ['UD', 'Blue Hens'],
  },
  // WEST VIRGINIA
  {
    id: 'wvu',
    name: 'West Virginia University',
    short_name: 'West Virginia',
    city: 'Morgantown',
    state: 'WV',
    country: 'US',
    zip_code: '26506',
    latitude: 39.6355,
    longitude: -79.9545,
    type: 'university',
    campus_type: 'main',
    enrollment: 26839,
    international_students: 1400,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#EAAA00',
    website: 'https://www.wvu.edu',
    aliases: ['WVU', 'Mountaineers'],
  },
  // NEVADA
  {
    id: 'unlv',
    name: 'University of Nevada, Las Vegas',
    short_name: 'UNLV',
    city: 'Las Vegas',
    state: 'NV',
    country: 'US',
    zip_code: '89154',
    latitude: 36.1080,
    longitude: -115.1447,
    type: 'university',
    campus_type: 'main',
    enrollment: 31142,
    international_students: 2400,
    is_public: true,
    primary_color: '#B10202',
    secondary_color: '#666666',
    website: 'https://www.unlv.edu',
    aliases: ['Las Vegas', 'Rebels'],
  },
  {
    id: 'unr',
    name: 'University of Nevada, Reno',
    short_name: 'Nevada',
    city: 'Reno',
    state: 'NV',
    country: 'US',
    zip_code: '89557',
    latitude: 39.5468,
    longitude: -119.8173,
    type: 'university',
    campus_type: 'main',
    enrollment: 21000,
    international_students: 1800,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#9E9E9E',
    website: 'https://www.unr.edu',
    aliases: ['UNR', 'Wolf Pack'],
  },
];

// ============================================================================
// COMBINE ALL ADDITIONAL UNIVERSITIES
// ============================================================================
export const ALL_TOP_ADDITIONS: University[] = [
  ...TOP_PRIVATE_ADDITIONAL,
  ...STATE_UNIVERSITIES_ADDITIONAL,
];

export default ALL_TOP_ADDITIONS;
