// ============================================================================
// UNITED KINGDOM UNIVERSITIES - COMPREHENSIVE LIST
// ============================================================================

import { University } from './types';

// Russell Group Universities (24 members)
export const RUSSELL_GROUP_UNIVERSITIES: University[] = [
  {
    id: 'oxford',
    name: 'University of Oxford',
    short_name: 'Oxford',
    city: 'Oxford',
    state: 'Oxfordshire',
    country: 'UK',
    zip_code: 'OX1 2JD',
    latitude: 51.7548,
    longitude: -1.2544,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 10800,
    international_percentage: 45,
    is_public: true,
    primary_color: '#002147',
    secondary_color: '#A79D96',
    website: 'https://www.ox.ac.uk',
    aliases: ['Oxford University', 'Oxon'],
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    short_name: 'Cambridge',
    city: 'Cambridge',
    state: 'Cambridgeshire',
    country: 'UK',
    zip_code: 'CB2 1TN',
    latitude: 52.2043,
    longitude: 0.1149,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 23000,
    international_students: 9200,
    international_percentage: 40,
    is_public: true,
    primary_color: '#A3C1AD',
    secondary_color: '#88B04B',
    website: 'https://www.cam.ac.uk',
    aliases: ['Cambridge University', 'Cantab'],
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    short_name: 'Imperial',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'SW7 2AZ',
    latitude: 51.4988,
    longitude: -0.1749,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 10450,
    international_percentage: 55,
    is_public: true,
    primary_color: '#003E74',
    secondary_color: '#002147',
    website: 'https://www.imperial.ac.uk',
    aliases: ['Imperial', 'ICL'],
  },
  {
    id: 'lse',
    name: 'London School of Economics and Political Science',
    short_name: 'LSE',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'WC2A 2AE',
    latitude: 51.5144,
    longitude: -0.1165,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 8400,
    international_percentage: 70,
    is_public: true,
    primary_color: '#E40046',
    secondary_color: '#000000',
    website: 'https://www.lse.ac.uk',
    aliases: ['London School of Economics'],
  },
  {
    id: 'ucl',
    name: 'University College London',
    short_name: 'UCL',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'WC1E 6BT',
    latitude: 51.5246,
    longitude: -0.1340,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 43000,
    international_students: 21500,
    international_percentage: 50,
    is_public: true,
    primary_color: '#500778',
    secondary_color: '#AC145A',
    website: 'https://www.ucl.ac.uk',
    aliases: ['University College London'],
  },
  {
    id: 'kcl',
    name: "King's College London",
    short_name: "King's",
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'WC2R 2LS',
    latitude: 51.5115,
    longitude: -0.1160,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 14850,
    international_percentage: 45,
    is_public: true,
    primary_color: '#D5093B',
    secondary_color: '#002147',
    website: 'https://www.kcl.ac.uk',
    aliases: ["King's College", 'KCL'],
  },
  {
    id: 'edinburgh',
    name: 'University of Edinburgh',
    short_name: 'Edinburgh',
    city: 'Edinburgh',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'EH8 9YL',
    latitude: 55.9445,
    longitude: -3.1892,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 35000,
    international_students: 15750,
    international_percentage: 45,
    is_public: true,
    primary_color: '#7A0019',
    secondary_color: '#333333',
    website: 'https://www.ed.ac.uk',
    aliases: ['Edinburgh University'],
  },
  {
    id: 'manchester',
    name: 'University of Manchester',
    short_name: 'Manchester',
    city: 'Manchester',
    state: 'Greater Manchester',
    country: 'UK',
    zip_code: 'M13 9PL',
    latitude: 53.4668,
    longitude: -2.2339,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 40000,
    international_students: 16000,
    international_percentage: 40,
    is_public: true,
    primary_color: '#660099',
    secondary_color: '#FFD700',
    website: 'https://www.manchester.ac.uk',
    aliases: ['Manchester University', 'UoM'],
  },
  {
    id: 'bristol',
    name: 'University of Bristol',
    short_name: 'Bristol',
    city: 'Bristol',
    state: 'Bristol',
    country: 'UK',
    zip_code: 'BS8 1TH',
    latitude: 51.4584,
    longitude: -2.6030,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 27000,
    international_students: 8100,
    international_percentage: 30,
    is_public: true,
    primary_color: '#B01C2E',
    secondary_color: '#002147',
    website: 'https://www.bristol.ac.uk',
    aliases: ['Bristol University'],
  },
  {
    id: 'warwick',
    name: 'University of Warwick',
    short_name: 'Warwick',
    city: 'Coventry',
    state: 'West Midlands',
    country: 'UK',
    zip_code: 'CV4 7AL',
    latitude: 52.3838,
    longitude: -1.5606,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 27000,
    international_students: 10800,
    international_percentage: 40,
    is_public: true,
    primary_color: '#5B2D8A',
    secondary_color: '#E8D630',
    website: 'https://www.warwick.ac.uk',
    aliases: ['Warwick University'],
  },
  {
    id: 'durham',
    name: 'Durham University',
    short_name: 'Durham',
    city: 'Durham',
    state: 'County Durham',
    country: 'UK',
    zip_code: 'DH1 3LE',
    latitude: 54.7680,
    longitude: -1.5731,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 5700,
    international_percentage: 30,
    is_public: true,
    primary_color: '#7E317B',
    secondary_color: '#000000',
    website: 'https://www.durham.ac.uk',
    aliases: ['University of Durham'],
  },
  {
    id: 'glasgow',
    name: 'University of Glasgow',
    short_name: 'Glasgow',
    city: 'Glasgow',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'G12 8QQ',
    latitude: 55.8721,
    longitude: -4.2882,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 9000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003865',
    secondary_color: '#D4A03C',
    website: 'https://www.gla.ac.uk',
    aliases: ['Glasgow University'],
  },
  {
    id: 'birmingham',
    name: 'University of Birmingham',
    short_name: 'Birmingham',
    city: 'Birmingham',
    state: 'West Midlands',
    country: 'UK',
    zip_code: 'B15 2TT',
    latitude: 52.4508,
    longitude: -1.9305,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 35000,
    international_students: 10500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#002855',
    secondary_color: '#B61F29',
    website: 'https://www.birmingham.ac.uk',
    aliases: ['Birmingham University', 'UoB'],
  },
  {
    id: 'leeds',
    name: 'University of Leeds',
    short_name: 'Leeds',
    city: 'Leeds',
    state: 'West Yorkshire',
    country: 'UK',
    zip_code: 'LS2 9JT',
    latitude: 53.8067,
    longitude: -1.5550,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 35000,
    international_students: 10500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#006C3E',
    secondary_color: '#FFFFFF',
    website: 'https://www.leeds.ac.uk',
    aliases: ['Leeds University'],
  },
  {
    id: 'sheffield',
    name: 'University of Sheffield',
    short_name: 'Sheffield',
    city: 'Sheffield',
    state: 'South Yorkshire',
    country: 'UK',
    zip_code: 'S10 2TN',
    latitude: 53.3811,
    longitude: -1.4861,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 29000,
    international_students: 10150,
    international_percentage: 35,
    is_public: true,
    primary_color: '#003A70',
    secondary_color: '#B10035',
    website: 'https://www.sheffield.ac.uk',
    aliases: ['Sheffield University'],
  },
  {
    id: 'nottingham',
    name: 'University of Nottingham',
    short_name: 'Nottingham',
    city: 'Nottingham',
    state: 'Nottinghamshire',
    country: 'UK',
    zip_code: 'NG7 2RD',
    latitude: 52.9388,
    longitude: -1.1963,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 34000,
    international_students: 10200,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFFFFF',
    website: 'https://www.nottingham.ac.uk',
    aliases: ['Nottingham University'],
  },
  {
    id: 'southampton',
    name: 'University of Southampton',
    short_name: 'Southampton',
    city: 'Southampton',
    state: 'Hampshire',
    country: 'UK',
    zip_code: 'SO17 1BJ',
    latitude: 50.9346,
    longitude: -1.3958,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 7200,
    international_percentage: 30,
    is_public: true,
    primary_color: '#005A87',
    secondary_color: '#E73F33',
    website: 'https://www.southampton.ac.uk',
    aliases: ['Southampton University'],
  },
  {
    id: 'liverpool',
    name: 'University of Liverpool',
    short_name: 'Liverpool',
    city: 'Liverpool',
    state: 'Merseyside',
    country: 'UK',
    zip_code: 'L69 3BX',
    latitude: 53.4056,
    longitude: -2.9671,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 7200,
    international_percentage: 30,
    is_public: true,
    primary_color: '#A4343A',
    secondary_color: '#000000',
    website: 'https://www.liverpool.ac.uk',
    aliases: ['Liverpool University'],
  },
  {
    id: 'newcastle',
    name: 'Newcastle University',
    short_name: 'Newcastle',
    city: 'Newcastle upon Tyne',
    state: 'Tyne and Wear',
    country: 'UK',
    zip_code: 'NE1 7RU',
    latitude: 54.9783,
    longitude: -1.6178,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 27000,
    international_students: 8100,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003865',
    secondary_color: '#FFBB00',
    website: 'https://www.ncl.ac.uk',
    aliases: ['Newcastle University'],
  },
  {
    id: 'cardiff',
    name: 'Cardiff University',
    short_name: 'Cardiff',
    city: 'Cardiff',
    state: 'Wales',
    country: 'UK',
    zip_code: 'CF10 3AT',
    latitude: 51.4816,
    longitude: -3.1791,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 33000,
    international_students: 9900,
    international_percentage: 30,
    is_public: true,
    primary_color: '#D40000',
    secondary_color: '#000000',
    website: 'https://www.cardiff.ac.uk',
    aliases: ['Cardiff University'],
  },
  {
    id: 'qmul',
    name: 'Queen Mary University of London',
    short_name: 'QMUL',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'E1 4NS',
    latitude: 51.5244,
    longitude: -0.0393,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 10000,
    international_percentage: 40,
    is_public: true,
    primary_color: '#005B82',
    secondary_color: '#DB0032',
    website: 'https://www.qmul.ac.uk',
    aliases: ['Queen Mary'],
  },
  {
    id: 'york',
    name: 'University of York',
    short_name: 'York',
    city: 'York',
    state: 'North Yorkshire',
    country: 'UK',
    zip_code: 'YO10 5DD',
    latitude: 53.9476,
    longitude: -1.0532,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 6000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003A63',
    secondary_color: '#79C3C3',
    website: 'https://www.york.ac.uk',
    aliases: ['York University UK'],
  },
  {
    id: 'exeter',
    name: 'University of Exeter',
    short_name: 'Exeter',
    city: 'Exeter',
    state: 'Devon',
    country: 'UK',
    zip_code: 'EX4 4QJ',
    latitude: 50.7362,
    longitude: -3.5340,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 7200,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C3C',
    secondary_color: '#8DB600',
    website: 'https://www.exeter.ac.uk',
    aliases: ['Exeter University'],
  },
  {
    id: 'qub',
    name: "Queen's University Belfast",
    short_name: "Queen's Belfast",
    city: 'Belfast',
    state: 'Northern Ireland',
    country: 'UK',
    zip_code: 'BT7 1NN',
    latitude: 54.5847,
    longitude: -5.9340,
    type: 'russell_group',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 4800,
    international_percentage: 20,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#000000',
    website: 'https://www.qub.ac.uk',
    aliases: ['QUB'],
  },
];

// Other Major UK Universities
export const OTHER_UK_UNIVERSITIES: University[] = [
  {
    id: 'st-andrews',
    name: 'University of St Andrews',
    short_name: 'St Andrews',
    city: 'St Andrews',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'KY16 9AJ',
    latitude: 56.3398,
    longitude: -2.7967,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 4500,
    international_percentage: 45,
    is_public: true,
    primary_color: '#00539B',
    secondary_color: '#FFDD00',
    website: 'https://www.st-andrews.ac.uk',
    aliases: ['St Andrews University'],
  },
  {
    id: 'bath',
    name: 'University of Bath',
    short_name: 'Bath',
    city: 'Bath',
    state: 'Somerset',
    country: 'UK',
    zip_code: 'BA2 7AY',
    latitude: 51.3796,
    longitude: -2.3279,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 5400,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.bath.ac.uk',
    aliases: ['Bath University'],
  },
  {
    id: 'lancaster',
    name: 'Lancaster University',
    short_name: 'Lancaster',
    city: 'Lancaster',
    state: 'Lancashire',
    country: 'UK',
    zip_code: 'LA1 4YW',
    latitude: 54.0104,
    longitude: -2.7877,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 4500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#B5121B',
    secondary_color: '#000000',
    website: 'https://www.lancaster.ac.uk',
    aliases: ['Lancaster University'],
  },
  {
    id: 'surrey',
    name: 'University of Surrey',
    short_name: 'Surrey',
    city: 'Guildford',
    state: 'Surrey',
    country: 'UK',
    zip_code: 'GU2 7XH',
    latitude: 51.2430,
    longitude: -0.5898,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 4800,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003B71',
    secondary_color: '#FFCD00',
    website: 'https://www.surrey.ac.uk',
    aliases: ['Surrey University'],
  },
  {
    id: 'loughborough',
    name: 'Loughborough University',
    short_name: 'Loughborough',
    city: 'Loughborough',
    state: 'Leicestershire',
    country: 'UK',
    zip_code: 'LE11 3TU',
    latitude: 52.7672,
    longitude: -1.2278,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 3600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#7E317B',
    secondary_color: '#000000',
    website: 'https://www.lboro.ac.uk',
    aliases: ['Loughborough University'],
  },
  {
    id: 'east-anglia',
    name: 'University of East Anglia',
    short_name: 'UEA',
    city: 'Norwich',
    state: 'Norfolk',
    country: 'UK',
    zip_code: 'NR4 7TJ',
    latitude: 52.6217,
    longitude: 1.2407,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 4250,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C69',
    secondary_color: '#FFD100',
    website: 'https://www.uea.ac.uk',
    aliases: ['East Anglia', 'UEA'],
  },
  {
    id: 'sussex',
    name: 'University of Sussex',
    short_name: 'Sussex',
    city: 'Brighton',
    state: 'East Sussex',
    country: 'UK',
    zip_code: 'BN1 9RH',
    latitude: 50.8673,
    longitude: -0.0871,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 5400,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#CC0000',
    website: 'https://www.sussex.ac.uk',
    aliases: ['Sussex University'],
  },
  {
    id: 'reading',
    name: 'University of Reading',
    short_name: 'Reading',
    city: 'Reading',
    state: 'Berkshire',
    country: 'UK',
    zip_code: 'RG6 6AH',
    latitude: 51.4412,
    longitude: -0.9456,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 4250,
    international_percentage: 25,
    is_public: true,
    primary_color: '#9B0000',
    secondary_color: '#000000',
    website: 'https://www.reading.ac.uk',
    aliases: ['Reading University'],
  },
  {
    id: 'leicester',
    name: 'University of Leicester',
    short_name: 'Leicester',
    city: 'Leicester',
    state: 'Leicestershire',
    country: 'UK',
    zip_code: 'LE1 7RH',
    latitude: 52.6212,
    longitude: -1.1242,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 4000,
    international_percentage: 25,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#000000',
    website: 'https://www.le.ac.uk',
    aliases: ['Leicester University'],
  },
  {
    id: 'strathclyde',
    name: 'University of Strathclyde',
    short_name: 'Strathclyde',
    city: 'Glasgow',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'G1 1XQ',
    latitude: 55.8617,
    longitude: -4.2431,
    type: 'university',
    campus_type: 'main',
    enrollment: 23000,
    international_students: 5750,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#9B2335',
    website: 'https://www.strath.ac.uk',
    aliases: ['Strathclyde University'],
  },
  {
    id: 'aberdeen',
    name: 'University of Aberdeen',
    short_name: 'Aberdeen',
    city: 'Aberdeen',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'AB24 3FX',
    latitude: 57.1667,
    longitude: -2.1000,
    type: 'university',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 3500,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C71',
    secondary_color: '#FFCC00',
    website: 'https://www.abdn.ac.uk',
    aliases: ['Aberdeen University'],
  },
  {
    id: 'kent',
    name: 'University of Kent',
    short_name: 'Kent',
    city: 'Canterbury',
    state: 'Kent',
    country: 'UK',
    zip_code: 'CT2 7NZ',
    latitude: 51.2991,
    longitude: 1.0665,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 4500,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00B2A9',
    website: 'https://www.kent.ac.uk',
    aliases: ['Kent University'],
  },
  {
    id: 'essex',
    name: 'University of Essex',
    short_name: 'Essex',
    city: 'Colchester',
    state: 'Essex',
    country: 'UK',
    zip_code: 'CO4 3SQ',
    latitude: 51.8773,
    longitude: 0.9457,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 5600,
    international_percentage: 35,
    is_public: true,
    primary_color: '#E40046',
    secondary_color: '#000000',
    website: 'https://www.essex.ac.uk',
    aliases: ['Essex University'],
  },
  {
    id: 'royal-holloway',
    name: 'Royal Holloway, University of London',
    short_name: 'Royal Holloway',
    city: 'Egham',
    state: 'Surrey',
    country: 'UK',
    zip_code: 'TW20 0EX',
    latitude: 51.4253,
    longitude: -0.5633,
    type: 'university',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 3600,
    international_percentage: 30,
    is_public: true,
    primary_color: '#8A1538',
    secondary_color: '#000000',
    website: 'https://www.royalholloway.ac.uk',
    aliases: ['RHUL', 'Royal Holloway'],
  },
  {
    id: 'soas',
    name: 'SOAS University of London',
    short_name: 'SOAS',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'WC1H 0XG',
    latitude: 51.5223,
    longitude: -0.1295,
    type: 'university',
    campus_type: 'main',
    enrollment: 6000,
    international_students: 3000,
    international_percentage: 50,
    is_public: true,
    primary_color: '#7E317B',
    secondary_color: '#000000',
    website: 'https://www.soas.ac.uk',
    aliases: ['School of Oriental and African Studies'],
  },
  {
    id: 'city-london',
    name: 'City, University of London',
    short_name: 'City',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'EC1V 0HB',
    latitude: 51.5281,
    longitude: -0.1025,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 8000,
    international_percentage: 40,
    is_public: true,
    primary_color: '#C8102E',
    secondary_color: '#000000',
    website: 'https://www.city.ac.uk',
    aliases: ['City University London'],
  },
  {
    id: 'brunel',
    name: 'Brunel University London',
    short_name: 'Brunel',
    city: 'Uxbridge',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'UB8 3PH',
    latitude: 51.5324,
    longitude: -0.4725,
    type: 'university',
    campus_type: 'main',
    enrollment: 15000,
    international_students: 4500,
    international_percentage: 30,
    is_public: true,
    primary_color: '#002D72',
    secondary_color: '#C8102E',
    website: 'https://www.brunel.ac.uk',
    aliases: ['Brunel University'],
  },
  {
    id: 'heriot-watt',
    name: 'Heriot-Watt University',
    short_name: 'Heriot-Watt',
    city: 'Edinburgh',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'EH14 4AS',
    latitude: 55.9117,
    longitude: -3.3217,
    type: 'university',
    campus_type: 'main',
    enrollment: 11000,
    international_students: 4400,
    international_percentage: 40,
    is_public: true,
    primary_color: '#00205B',
    secondary_color: '#C8102E',
    website: 'https://www.hw.ac.uk',
    aliases: ['Heriot Watt'],
  },
  {
    id: 'dundee',
    name: 'University of Dundee',
    short_name: 'Dundee',
    city: 'Dundee',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'DD1 4HN',
    latitude: 56.4578,
    longitude: -2.9780,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 4000,
    international_percentage: 25,
    is_public: true,
    primary_color: '#006600',
    secondary_color: '#000000',
    website: 'https://www.dundee.ac.uk',
    aliases: ['Dundee University'],
  },
  {
    id: 'stirling',
    name: 'University of Stirling',
    short_name: 'Stirling',
    city: 'Stirling',
    state: 'Scotland',
    country: 'UK',
    zip_code: 'FK9 4LA',
    latitude: 56.1451,
    longitude: -3.9189,
    type: 'university',
    campus_type: 'main',
    enrollment: 14000,
    international_students: 3500,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.stir.ac.uk',
    aliases: ['Stirling University'],
  },
  {
    id: 'aston',
    name: 'Aston University',
    short_name: 'Aston',
    city: 'Birmingham',
    state: 'West Midlands',
    country: 'UK',
    zip_code: 'B4 7ET',
    latitude: 52.4866,
    longitude: -1.8900,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 5100,
    international_percentage: 30,
    is_public: true,
    primary_color: '#7E317B',
    secondary_color: '#000000',
    website: 'https://www.aston.ac.uk',
    aliases: ['Aston University'],
  },
  {
    id: 'swansea',
    name: 'Swansea University',
    short_name: 'Swansea',
    city: 'Swansea',
    state: 'Wales',
    country: 'UK',
    zip_code: 'SA2 8PP',
    latitude: 51.6101,
    longitude: -3.9820,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 5000,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFCC00',
    website: 'https://www.swansea.ac.uk',
    aliases: ['Swansea University'],
  },
  {
    id: 'hull',
    name: 'University of Hull',
    short_name: 'Hull',
    city: 'Hull',
    state: 'East Yorkshire',
    country: 'UK',
    zip_code: 'HU6 7RX',
    latitude: 53.7701,
    longitude: -0.3670,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 3200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003366',
    secondary_color: '#FFD700',
    website: 'https://www.hull.ac.uk',
    aliases: ['Hull University'],
  },
  {
    id: 'keele',
    name: 'Keele University',
    short_name: 'Keele',
    city: 'Keele',
    state: 'Staffordshire',
    country: 'UK',
    zip_code: 'ST5 5BG',
    latitude: 53.0007,
    longitude: -2.2742,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 2000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#7E317B',
    secondary_color: '#000000',
    website: 'https://www.keele.ac.uk',
    aliases: ['Keele University'],
  },
  {
    id: 'bangor',
    name: 'Bangor University',
    short_name: 'Bangor',
    city: 'Bangor',
    state: 'Wales',
    country: 'UK',
    zip_code: 'LL57 2DG',
    latitude: 53.2277,
    longitude: -4.1292,
    type: 'university',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 2400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#C8102E',
    website: 'https://www.bangor.ac.uk',
    aliases: ['Bangor University'],
  },
  {
    id: 'aberystwyth',
    name: 'Aberystwyth University',
    short_name: 'Aberystwyth',
    city: 'Aberystwyth',
    state: 'Wales',
    country: 'UK',
    zip_code: 'SY23 2AX',
    latitude: 52.4167,
    longitude: -4.0833,
    type: 'university',
    campus_type: 'main',
    enrollment: 9000,
    international_students: 1800,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.aber.ac.uk',
    aliases: ['Aberystwyth University'],
  },
  {
    id: 'ulster',
    name: 'Ulster University',
    short_name: 'Ulster',
    city: 'Coleraine',
    state: 'Northern Ireland',
    country: 'UK',
    zip_code: 'BT52 1SA',
    latitude: 55.1425,
    longitude: -6.6756,
    type: 'university',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 5000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#000000',
    website: 'https://www.ulster.ac.uk',
    aliases: ['Ulster University'],
  },
  {
    id: 'bradford',
    name: 'University of Bradford',
    short_name: 'Bradford',
    city: 'Bradford',
    state: 'West Yorkshire',
    country: 'UK',
    zip_code: 'BD7 1DP',
    latitude: 53.7921,
    longitude: -1.7642,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 2500,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.bradford.ac.uk',
    aliases: ['Bradford University'],
  },
  {
    id: 'plymouth',
    name: 'University of Plymouth',
    short_name: 'Plymouth',
    city: 'Plymouth',
    state: 'Devon',
    country: 'UK',
    zip_code: 'PL4 8AA',
    latitude: 50.3755,
    longitude: -4.1427,
    type: 'university',
    campus_type: 'main',
    enrollment: 21000,
    international_students: 4200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.plymouth.ac.uk',
    aliases: ['Plymouth University'],
  },
  {
    id: 'portsmouth',
    name: 'University of Portsmouth',
    short_name: 'Portsmouth',
    city: 'Portsmouth',
    state: 'Hampshire',
    country: 'UK',
    zip_code: 'PO1 2UP',
    latitude: 50.7989,
    longitude: -1.0978,
    type: 'university',
    campus_type: 'main',
    enrollment: 24000,
    international_students: 4800,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#C8102E',
    website: 'https://www.port.ac.uk',
    aliases: ['Portsmouth University'],
  },
  {
    id: 'brighton',
    name: 'University of Brighton',
    short_name: 'Brighton',
    city: 'Brighton',
    state: 'East Sussex',
    country: 'UK',
    zip_code: 'BN2 4AT',
    latitude: 50.8225,
    longitude: -0.1372,
    type: 'university',
    campus_type: 'main',
    enrollment: 21000,
    international_students: 4200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.brighton.ac.uk',
    aliases: ['Brighton University'],
  },
  {
    id: 'greenwich',
    name: 'University of Greenwich',
    short_name: 'Greenwich',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'SE10 9LS',
    latitude: 51.4826,
    longitude: -0.0077,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 6000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.greenwich.ac.uk',
    aliases: ['Greenwich University'],
  },
  {
    id: 'westminster',
    name: 'University of Westminster',
    short_name: 'Westminster',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'W1W 6UW',
    latitude: 51.5175,
    longitude: -0.1420,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 5700,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#C8102E',
    website: 'https://www.westminster.ac.uk',
    aliases: ['Westminster University'],
  },
  {
    id: 'middlesex',
    name: 'Middlesex University',
    short_name: 'Middlesex',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'NW4 4BT',
    latitude: 51.5899,
    longitude: -0.2286,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 5700,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FF6600',
    website: 'https://www.mdx.ac.uk',
    aliases: ['Middlesex University'],
  },
  {
    id: 'goldsmiths',
    name: 'Goldsmiths, University of London',
    short_name: 'Goldsmiths',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'SE14 6NW',
    latitude: 51.4745,
    longitude: -0.0350,
    type: 'university',
    campus_type: 'main',
    enrollment: 10000,
    international_students: 3000,
    international_percentage: 30,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#FFD700',
    website: 'https://www.gold.ac.uk',
    aliases: ['Goldsmiths'],
  },
  {
    id: 'birkbeck',
    name: 'Birkbeck, University of London',
    short_name: 'Birkbeck',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'WC1E 7HX',
    latitude: 51.5209,
    longitude: -0.1301,
    type: 'university',
    campus_type: 'main',
    enrollment: 13000,
    international_students: 2600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#00539B',
    secondary_color: '#000000',
    website: 'https://www.bbk.ac.uk',
    aliases: ['Birkbeck'],
  },
  {
    id: 'oxford-brookes',
    name: 'Oxford Brookes University',
    short_name: 'Oxford Brookes',
    city: 'Oxford',
    state: 'Oxfordshire',
    country: 'UK',
    zip_code: 'OX3 0BP',
    latitude: 51.7536,
    longitude: -1.2224,
    type: 'university',
    campus_type: 'main',
    enrollment: 18000,
    international_students: 4500,
    international_percentage: 25,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.brookes.ac.uk',
    aliases: ['Oxford Brookes'],
  },
  {
    id: 'nottingham-trent',
    name: 'Nottingham Trent University',
    short_name: 'NTU',
    city: 'Nottingham',
    state: 'Nottinghamshire',
    country: 'UK',
    zip_code: 'NG1 4FQ',
    latitude: 52.9583,
    longitude: -1.1547,
    type: 'university',
    campus_type: 'main',
    enrollment: 35000,
    international_students: 7000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#00B2A9',
    secondary_color: '#000000',
    website: 'https://www.ntu.ac.uk',
    aliases: ['Nottingham Trent', 'NTU'],
  },
  {
    id: 'sheffield-hallam',
    name: 'Sheffield Hallam University',
    short_name: 'Sheffield Hallam',
    city: 'Sheffield',
    state: 'South Yorkshire',
    country: 'UK',
    zip_code: 'S1 1WB',
    latitude: 53.3784,
    longitude: -1.4666,
    type: 'university',
    campus_type: 'main',
    enrollment: 31000,
    international_students: 6200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.shu.ac.uk',
    aliases: ['Sheffield Hallam', 'SHU'],
  },
  {
    id: 'manchester-met',
    name: 'Manchester Metropolitan University',
    short_name: 'MMU',
    city: 'Manchester',
    state: 'Greater Manchester',
    country: 'UK',
    zip_code: 'M15 6BH',
    latitude: 53.4706,
    longitude: -2.2397,
    type: 'university',
    campus_type: 'main',
    enrollment: 36000,
    international_students: 7200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#6E2585',
    secondary_color: '#000000',
    website: 'https://www.mmu.ac.uk',
    aliases: ['Manchester Met', 'MMU'],
  },
  {
    id: 'leeds-beckett',
    name: 'Leeds Beckett University',
    short_name: 'Leeds Beckett',
    city: 'Leeds',
    state: 'West Yorkshire',
    country: 'UK',
    zip_code: 'LS1 3HE',
    latitude: 53.8008,
    longitude: -1.5491,
    type: 'university',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 5000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.leedsbeckett.ac.uk',
    aliases: ['Leeds Beckett', 'LBU'],
  },
  {
    id: 'de-montfort',
    name: 'De Montfort University',
    short_name: 'DMU',
    city: 'Leicester',
    state: 'Leicestershire',
    country: 'UK',
    zip_code: 'LE1 9BH',
    latitude: 52.6293,
    longitude: -1.1391,
    type: 'university',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 5000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#00447C',
    secondary_color: '#000000',
    website: 'https://www.dmu.ac.uk',
    aliases: ['De Montfort', 'DMU'],
  },
  {
    id: 'uwe-bristol',
    name: 'University of the West of England',
    short_name: 'UWE Bristol',
    city: 'Bristol',
    state: 'Bristol',
    country: 'UK',
    zip_code: 'BS16 1QY',
    latitude: 51.5000,
    longitude: -2.5500,
    type: 'university',
    campus_type: 'main',
    enrollment: 32000,
    international_students: 6400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#7E317B',
    secondary_color: '#00A76E',
    website: 'https://www.uwe.ac.uk',
    aliases: ['UWE', 'UWE Bristol'],
  },
  {
    id: 'coventry',
    name: 'Coventry University',
    short_name: 'Coventry',
    city: 'Coventry',
    state: 'West Midlands',
    country: 'UK',
    zip_code: 'CV1 5FB',
    latitude: 52.4068,
    longitude: -1.5197,
    type: 'university',
    campus_type: 'main',
    enrollment: 32000,
    international_students: 9600,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.coventry.ac.uk',
    aliases: ['Coventry University'],
  },
  {
    id: 'birmingham-city',
    name: 'Birmingham City University',
    short_name: 'BCU',
    city: 'Birmingham',
    state: 'West Midlands',
    country: 'UK',
    zip_code: 'B4 7BD',
    latitude: 52.4847,
    longitude: -1.8897,
    type: 'university',
    campus_type: 'main',
    enrollment: 28000,
    international_students: 5600,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#C8102E',
    website: 'https://www.bcu.ac.uk',
    aliases: ['Birmingham City', 'BCU'],
  },
  {
    id: 'northumbria',
    name: 'Northumbria University',
    short_name: 'Northumbria',
    city: 'Newcastle upon Tyne',
    state: 'Tyne and Wear',
    country: 'UK',
    zip_code: 'NE1 8ST',
    latitude: 54.9739,
    longitude: -1.6062,
    type: 'university',
    campus_type: 'main',
    enrollment: 32000,
    international_students: 6400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#000000',
    website: 'https://www.northumbria.ac.uk',
    aliases: ['Northumbria University'],
  },
  {
    id: 'liverpool-john-moores',
    name: 'Liverpool John Moores University',
    short_name: 'LJMU',
    city: 'Liverpool',
    state: 'Merseyside',
    country: 'UK',
    zip_code: 'L3 5UX',
    latitude: 53.4072,
    longitude: -2.9797,
    type: 'university',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 5000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.ljmu.ac.uk',
    aliases: ['LJMU', 'Liverpool John Moores'],
  },
  {
    id: 'central-lancashire',
    name: 'University of Central Lancashire',
    short_name: 'UCLan',
    city: 'Preston',
    state: 'Lancashire',
    country: 'UK',
    zip_code: 'PR1 2HE',
    latitude: 53.7632,
    longitude: -2.7044,
    type: 'university',
    campus_type: 'main',
    enrollment: 26000,
    international_students: 5200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#E40046',
    secondary_color: '#000000',
    website: 'https://www.uclan.ac.uk',
    aliases: ['UCLan', 'Central Lancashire'],
  },
  {
    id: 'salford',
    name: 'University of Salford',
    short_name: 'Salford',
    city: 'Salford',
    state: 'Greater Manchester',
    country: 'UK',
    zip_code: 'M5 4WT',
    latitude: 53.4875,
    longitude: -2.2739,
    type: 'university',
    campus_type: 'main',
    enrollment: 22000,
    international_students: 4400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#C8102E',
    website: 'https://www.salford.ac.uk',
    aliases: ['Salford University'],
  },
  {
    id: 'huddersfield',
    name: 'University of Huddersfield',
    short_name: 'Huddersfield',
    city: 'Huddersfield',
    state: 'West Yorkshire',
    country: 'UK',
    zip_code: 'HD1 3DH',
    latitude: 53.6439,
    longitude: -1.7773,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 4000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.hud.ac.uk',
    aliases: ['Huddersfield University'],
  },
  {
    id: 'teesside',
    name: 'Teesside University',
    short_name: 'Teesside',
    city: 'Middlesbrough',
    state: 'North Yorkshire',
    country: 'UK',
    zip_code: 'TS1 3BX',
    latitude: 54.5733,
    longitude: -1.2350,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 4000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.tees.ac.uk',
    aliases: ['Teesside University'],
  },
  {
    id: 'hertfordshire',
    name: 'University of Hertfordshire',
    short_name: 'Hertfordshire',
    city: 'Hatfield',
    state: 'Hertfordshire',
    country: 'UK',
    zip_code: 'AL10 9AB',
    latitude: 51.7524,
    longitude: -0.2395,
    type: 'university',
    campus_type: 'main',
    enrollment: 25000,
    international_students: 5000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.herts.ac.uk',
    aliases: ['Hertfordshire University'],
  },
  {
    id: 'edge-hill',
    name: 'Edge Hill University',
    short_name: 'Edge Hill',
    city: 'Ormskirk',
    state: 'Lancashire',
    country: 'UK',
    zip_code: 'L39 4QP',
    latitude: 53.5562,
    longitude: -2.8636,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 1600,
    international_percentage: 10,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.edgehill.ac.uk',
    aliases: ['Edge Hill University'],
  },
  {
    id: 'lincoln',
    name: 'University of Lincoln',
    short_name: 'Lincoln',
    city: 'Lincoln',
    state: 'Lincolnshire',
    country: 'UK',
    zip_code: 'LN6 7TS',
    latitude: 53.2282,
    longitude: -0.5472,
    type: 'university',
    campus_type: 'main',
    enrollment: 16000,
    international_students: 3200,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#C8102E',
    website: 'https://www.lincoln.ac.uk',
    aliases: ['Lincoln University UK'],
  },
  {
    id: 'london-south-bank',
    name: 'London South Bank University',
    short_name: 'LSBU',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'SE1 0AA',
    latitude: 51.4980,
    longitude: -0.1026,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 5100,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.lsbu.ac.uk',
    aliases: ['LSBU', 'London South Bank'],
  },
  {
    id: 'kingston',
    name: 'Kingston University',
    short_name: 'Kingston',
    city: 'Kingston upon Thames',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'KT1 1LQ',
    latitude: 51.4048,
    longitude: -0.3064,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 5100,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#E40046',
    website: 'https://www.kingston.ac.uk',
    aliases: ['Kingston University'],
  },
  {
    id: 'roehampton',
    name: 'University of Roehampton',
    short_name: 'Roehampton',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'SW15 5PU',
    latitude: 51.4545,
    longitude: -0.2453,
    type: 'university',
    campus_type: 'main',
    enrollment: 12000,
    international_students: 3600,
    international_percentage: 30,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.roehampton.ac.uk',
    aliases: ['Roehampton University'],
  },
  {
    id: 'derby',
    name: 'University of Derby',
    short_name: 'Derby',
    city: 'Derby',
    state: 'Derbyshire',
    country: 'UK',
    zip_code: 'DE22 1GB',
    latitude: 52.9373,
    longitude: -1.4972,
    type: 'university',
    campus_type: 'main',
    enrollment: 17000,
    international_students: 3400,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.derby.ac.uk',
    aliases: ['Derby University'],
  },
  {
    id: 'wolverhampton',
    name: 'University of Wolverhampton',
    short_name: 'Wolverhampton',
    city: 'Wolverhampton',
    state: 'West Midlands',
    country: 'UK',
    zip_code: 'WV1 1LY',
    latitude: 52.5862,
    longitude: -2.1282,
    type: 'university',
    campus_type: 'main',
    enrollment: 20000,
    international_students: 4000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.wlv.ac.uk',
    aliases: ['Wolverhampton University'],
  },
  {
    id: 'south-wales',
    name: 'University of South Wales',
    short_name: 'South Wales',
    city: 'Pontypridd',
    state: 'Wales',
    country: 'UK',
    zip_code: 'CF37 1DL',
    latitude: 51.5886,
    longitude: -3.3275,
    type: 'university',
    campus_type: 'main',
    enrollment: 30000,
    international_students: 6000,
    international_percentage: 20,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.southwales.ac.uk',
    aliases: ['USW', 'South Wales'],
  },
  {
    id: 'arts-london',
    name: 'University of the Arts London',
    short_name: 'UAL',
    city: 'London',
    state: 'Greater London',
    country: 'UK',
    zip_code: 'SE1 6SB',
    latitude: 51.5014,
    longitude: -0.1070,
    type: 'university',
    campus_type: 'main',
    enrollment: 19000,
    international_students: 8550,
    international_percentage: 45,
    is_public: true,
    primary_color: '#000000',
    secondary_color: '#E40046',
    website: 'https://www.arts.ac.uk',
    aliases: ['UAL', 'Arts London'],
  },
  {
    id: 'cranfield',
    name: 'Cranfield University',
    short_name: 'Cranfield',
    city: 'Cranfield',
    state: 'Bedfordshire',
    country: 'UK',
    zip_code: 'MK43 0AL',
    latitude: 52.0720,
    longitude: -0.6282,
    type: 'university',
    campus_type: 'main',
    enrollment: 4500,
    international_students: 2700,
    international_percentage: 60,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#FFD700',
    website: 'https://www.cranfield.ac.uk',
    aliases: ['Cranfield University'],
  },
  {
    id: 'open-university',
    name: 'The Open University',
    short_name: 'OU',
    city: 'Milton Keynes',
    state: 'Buckinghamshire',
    country: 'UK',
    zip_code: 'MK7 6AA',
    latitude: 52.0252,
    longitude: -0.7107,
    type: 'university',
    campus_type: 'online',
    enrollment: 170000,
    international_students: 17000,
    international_percentage: 10,
    is_public: true,
    primary_color: '#003C6C',
    secondary_color: '#00A76E',
    website: 'https://www.open.ac.uk',
    aliases: ['Open University', 'OU'],
  },
];

// Combine all UK universities
export const ALL_UK_UNIVERSITIES: University[] = [
  ...RUSSELL_GROUP_UNIVERSITIES,
  ...OTHER_UK_UNIVERSITIES,
];

export default ALL_UK_UNIVERSITIES;
