/**
 * Complete Canadian Universities and Colleges Database
 * Based on Universities Canada and Colleges and Institutes Canada official data
 *
 * Includes:
 * - All Canadian universities (~100)
 * - Major colleges (~150)
 * - CEGEPs (Quebec) (~48)
 */

export interface CanadaInstitution {
  id: string;
  name: string;
  short_name: string;
  city: string;
  state: string; // Province code
  country: string;
  zip_code: string;
  latitude: number;
  longitude: number;
  type: string;
  campus_type: string;
  sector: string;
  is_public: boolean;
  enrollment?: number;
  international_students?: number;
  website: string;
  aliases: string[];
  source: string;
  source_id: string;
}

// Canadian Universities
export const CANADIAN_UNIVERSITIES: CanadaInstitution[] = [
  // Ontario
  { id: 'ca-uoft', name: 'University of Toronto', short_name: 'U of T', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M5S 1A1', latitude: 43.6629, longitude: -79.3957, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 97000, international_students: 27000, website: 'https://www.utoronto.ca', aliases: ['UofT', 'Toronto', 'U of T'], source: 'universities_canada', source_id: 'uoft' },
  { id: 'ca-uoft-scarborough', name: 'University of Toronto Scarborough', short_name: 'UTSC', city: 'Scarborough', state: 'ON', country: 'CA', zip_code: 'M1C 1A4', latitude: 43.7844, longitude: -79.1865, type: 'university', campus_type: 'branch', sector: 'public', is_public: true, enrollment: 14000, website: 'https://www.utsc.utoronto.ca', aliases: ['UTSC', 'Scarborough'], source: 'universities_canada', source_id: 'utsc' },
  { id: 'ca-uoft-mississauga', name: 'University of Toronto Mississauga', short_name: 'UTM', city: 'Mississauga', state: 'ON', country: 'CA', zip_code: 'L5L 1C6', latitude: 43.5489, longitude: -79.6625, type: 'university', campus_type: 'branch', sector: 'public', is_public: true, enrollment: 15000, website: 'https://www.utm.utoronto.ca', aliases: ['UTM', 'Mississauga'], source: 'universities_canada', source_id: 'utm' },
  { id: 'ca-waterloo', name: 'University of Waterloo', short_name: 'Waterloo', city: 'Waterloo', state: 'ON', country: 'CA', zip_code: 'N2L 3G1', latitude: 43.4723, longitude: -80.5449, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 42000, international_students: 9000, website: 'https://uwaterloo.ca', aliases: ['UW', 'Waterloo'], source: 'universities_canada', source_id: 'waterloo' },
  { id: 'ca-western', name: 'Western University', short_name: 'Western', city: 'London', state: 'ON', country: 'CA', zip_code: 'N6A 3K7', latitude: 43.0096, longitude: -81.2737, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 34000, international_students: 6500, website: 'https://www.uwo.ca', aliases: ['UWO', 'Western Ontario'], source: 'universities_canada', source_id: 'western' },
  { id: 'ca-mcmaster', name: 'McMaster University', short_name: 'McMaster', city: 'Hamilton', state: 'ON', country: 'CA', zip_code: 'L8S 4L8', latitude: 43.2609, longitude: -79.9192, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 37000, international_students: 7500, website: 'https://www.mcmaster.ca', aliases: ['Mac', 'McMaster'], source: 'universities_canada', source_id: 'mcmaster' },
  { id: 'ca-queens', name: "Queen's University", short_name: "Queen's", city: 'Kingston', state: 'ON', country: 'CA', zip_code: 'K7L 3N6', latitude: 44.2253, longitude: -76.4951, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 5000, website: 'https://www.queensu.ca', aliases: ["Queen's", 'Queens'], source: 'universities_canada', source_id: 'queens' },
  { id: 'ca-ottawa', name: 'University of Ottawa', short_name: 'uOttawa', city: 'Ottawa', state: 'ON', country: 'CA', zip_code: 'K1N 6N5', latitude: 45.4231, longitude: -75.6831, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 44000, international_students: 8000, website: 'https://www.uottawa.ca', aliases: ['uOttawa', 'Ottawa'], source: 'universities_canada', source_id: 'ottawa' },
  { id: 'ca-york', name: 'York University', short_name: 'York', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M3J 1P3', latitude: 43.7735, longitude: -79.5019, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 55000, international_students: 11000, website: 'https://www.yorku.ca', aliases: ['York', 'YorkU'], source: 'universities_canada', source_id: 'york' },
  { id: 'ca-carleton', name: 'Carleton University', short_name: 'Carleton', city: 'Ottawa', state: 'ON', country: 'CA', zip_code: 'K1S 5B6', latitude: 45.3876, longitude: -75.6960, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 31000, international_students: 5500, website: 'https://carleton.ca', aliases: ['Carleton'], source: 'universities_canada', source_id: 'carleton' },
  { id: 'ca-guelph', name: 'University of Guelph', short_name: 'Guelph', city: 'Guelph', state: 'ON', country: 'CA', zip_code: 'N1G 2W1', latitude: 43.5327, longitude: -80.2262, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 4000, website: 'https://www.uoguelph.ca', aliases: ['Guelph'], source: 'universities_canada', source_id: 'guelph' },
  { id: 'ca-ryerson', name: 'Toronto Metropolitan University', short_name: 'TMU', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M5B 2K3', latitude: 43.6577, longitude: -79.3788, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 46000, international_students: 8500, website: 'https://www.torontomu.ca', aliases: ['TMU', 'Ryerson', 'Toronto Met'], source: 'universities_canada', source_id: 'tmu' },
  { id: 'ca-windsor', name: 'University of Windsor', short_name: 'Windsor', city: 'Windsor', state: 'ON', country: 'CA', zip_code: 'N9B 3P4', latitude: 42.3045, longitude: -83.0669, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 16000, international_students: 5000, website: 'https://www.uwindsor.ca', aliases: ['Windsor', 'UWindsor'], source: 'universities_canada', source_id: 'windsor' },
  { id: 'ca-wilfrid-laurier', name: 'Wilfrid Laurier University', short_name: 'Laurier', city: 'Waterloo', state: 'ON', country: 'CA', zip_code: 'N2L 3C5', latitude: 43.4738, longitude: -80.5275, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 2500, website: 'https://www.wlu.ca', aliases: ['Laurier', 'WLU'], source: 'universities_canada', source_id: 'laurier' },
  { id: 'ca-brock', name: 'Brock University', short_name: 'Brock', city: 'St. Catharines', state: 'ON', country: 'CA', zip_code: 'L2S 3A1', latitude: 43.1175, longitude: -79.2477, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 19000, international_students: 2500, website: 'https://brocku.ca', aliases: ['Brock'], source: 'universities_canada', source_id: 'brock' },
  { id: 'ca-lakehead', name: 'Lakehead University', short_name: 'Lakehead', city: 'Thunder Bay', state: 'ON', country: 'CA', zip_code: 'P7B 5E1', latitude: 48.4197, longitude: -89.2619, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 1200, website: 'https://www.lakeheadu.ca', aliases: ['Lakehead'], source: 'universities_canada', source_id: 'lakehead' },
  { id: 'ca-laurentian', name: 'Laurentian University', short_name: 'Laurentian', city: 'Sudbury', state: 'ON', country: 'CA', zip_code: 'P3E 2C6', latitude: 46.4675, longitude: -80.9722, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 9000, international_students: 1000, website: 'https://laurentian.ca', aliases: ['Laurentian'], source: 'universities_canada', source_id: 'laurentian' },
  { id: 'ca-nipissing', name: 'Nipissing University', short_name: 'Nipissing', city: 'North Bay', state: 'ON', country: 'CA', zip_code: 'P1B 8L7', latitude: 46.3342, longitude: -79.4839, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 600, website: 'https://www.nipissingu.ca', aliases: ['Nipissing'], source: 'universities_canada', source_id: 'nipissing' },
  { id: 'ca-trent', name: 'Trent University', short_name: 'Trent', city: 'Peterborough', state: 'ON', country: 'CA', zip_code: 'K9L 0G2', latitude: 44.3594, longitude: -78.2889, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 1500, website: 'https://www.trentu.ca', aliases: ['Trent'], source: 'universities_canada', source_id: 'trent' },
  { id: 'ca-ontario-tech', name: 'Ontario Tech University', short_name: 'Ontario Tech', city: 'Oshawa', state: 'ON', country: 'CA', zip_code: 'L1G 0C5', latitude: 43.9446, longitude: -78.8965, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 2000, website: 'https://ontariotechu.ca', aliases: ['Ontario Tech', 'UOIT'], source: 'universities_canada', source_id: 'ontariotech' },
  { id: 'ca-ocad', name: 'OCAD University', short_name: 'OCAD', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M5T 1W1', latitude: 43.6516, longitude: -79.3918, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 1200, website: 'https://www.ocadu.ca', aliases: ['OCAD'], source: 'universities_canada', source_id: 'ocad' },
  { id: 'ca-algoma', name: 'Algoma University', short_name: 'Algoma', city: 'Sault Ste. Marie', state: 'ON', country: 'CA', zip_code: 'P6A 2G4', latitude: 46.5277, longitude: -84.3347, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 1500, international_students: 400, website: 'https://algomau.ca', aliases: ['Algoma'], source: 'universities_canada', source_id: 'algoma' },

  // Quebec
  { id: 'ca-mcgill', name: 'McGill University', short_name: 'McGill', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3A 0G4', latitude: 45.5048, longitude: -73.5772, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 40000, international_students: 12500, website: 'https://www.mcgill.ca', aliases: ['McGill'], source: 'universities_canada', source_id: 'mcgill' },
  { id: 'ca-udem', name: 'Université de Montréal', short_name: 'UdeM', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3T 1J4', latitude: 45.5017, longitude: -73.6162, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 67000, international_students: 11000, website: 'https://www.umontreal.ca', aliases: ['UdeM', 'Montreal'], source: 'universities_canada', source_id: 'udem' },
  { id: 'ca-concordia', name: 'Concordia University', short_name: 'Concordia', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3G 1M8', latitude: 45.4972, longitude: -73.5785, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 51000, international_students: 11500, website: 'https://www.concordia.ca', aliases: ['Concordia'], source: 'universities_canada', source_id: 'concordia' },
  { id: 'ca-uqam', name: 'Université du Québec à Montréal', short_name: 'UQAM', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H2X 3R9', latitude: 45.5088, longitude: -73.5694, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 40000, international_students: 5000, website: 'https://uqam.ca', aliases: ['UQAM'], source: 'universities_canada', source_id: 'uqam' },
  { id: 'ca-laval', name: 'Université Laval', short_name: 'Laval', city: 'Quebec City', state: 'QC', country: 'CA', zip_code: 'G1V 0A6', latitude: 46.7808, longitude: -71.2748, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 44000, international_students: 7000, website: 'https://www.ulaval.ca', aliases: ['Laval'], source: 'universities_canada', source_id: 'laval' },
  { id: 'ca-sherbrooke', name: 'Université de Sherbrooke', short_name: 'Sherbrooke', city: 'Sherbrooke', state: 'QC', country: 'CA', zip_code: 'J1K 2R1', latitude: 45.3792, longitude: -71.9306, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 31000, international_students: 4000, website: 'https://www.usherbrooke.ca', aliases: ['Sherbrooke', 'UdeS'], source: 'universities_canada', source_id: 'sherbrooke' },
  { id: 'ca-polytechnique', name: 'Polytechnique Montréal', short_name: 'Polytechnique', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3T 1J4', latitude: 45.5049, longitude: -73.6132, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 9000, international_students: 2500, website: 'https://www.polymtl.ca', aliases: ['Poly', 'Polytechnique'], source: 'universities_canada', source_id: 'polymtl' },
  { id: 'ca-hec', name: 'HEC Montréal', short_name: 'HEC', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3T 2A7', latitude: 45.5019, longitude: -73.6197, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 4000, website: 'https://www.hec.ca', aliases: ['HEC', 'HEC Montreal'], source: 'universities_canada', source_id: 'hec' },
  { id: 'ca-ets', name: 'École de technologie supérieure', short_name: 'ÉTS', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3C 1K3', latitude: 45.4945, longitude: -73.5626, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 2500, website: 'https://www.etsmtl.ca', aliases: ['ETS', 'ÉTS'], source: 'universities_canada', source_id: 'ets' },
  { id: 'ca-enap', name: "École nationale d'administration publique", short_name: 'ENAP', city: 'Quebec City', state: 'QC', country: 'CA', zip_code: 'G1K 9E5', latitude: 46.8139, longitude: -71.2080, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 3000, international_students: 500, website: 'https://www.enap.ca', aliases: ['ENAP'], source: 'universities_canada', source_id: 'enap' },
  { id: 'ca-inrs', name: 'Institut national de la recherche scientifique', short_name: 'INRS', city: 'Quebec City', state: 'QC', country: 'CA', zip_code: 'G1K 9A9', latitude: 46.8115, longitude: -71.2233, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 800, international_students: 400, website: 'https://www.inrs.ca', aliases: ['INRS'], source: 'universities_canada', source_id: 'inrs' },
  { id: 'ca-uqtr', name: 'Université du Québec à Trois-Rivières', short_name: 'UQTR', city: 'Trois-Rivières', state: 'QC', country: 'CA', zip_code: 'G8Z 4M3', latitude: 46.3498, longitude: -72.5778, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 1500, website: 'https://www.uqtr.ca', aliases: ['UQTR'], source: 'universities_canada', source_id: 'uqtr' },
  { id: 'ca-uqac', name: 'Université du Québec à Chicoutimi', short_name: 'UQAC', city: 'Saguenay', state: 'QC', country: 'CA', zip_code: 'G7H 2B1', latitude: 48.4192, longitude: -71.0520, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6500, international_students: 800, website: 'https://www.uqac.ca', aliases: ['UQAC'], source: 'universities_canada', source_id: 'uqac' },
  { id: 'ca-uqar', name: 'Université du Québec à Rimouski', short_name: 'UQAR', city: 'Rimouski', state: 'QC', country: 'CA', zip_code: 'G5L 3A1', latitude: 48.4536, longitude: -68.5230, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 7000, international_students: 800, website: 'https://www.uqar.ca', aliases: ['UQAR'], source: 'universities_canada', source_id: 'uqar' },
  { id: 'ca-uqo', name: "Université du Québec en Outaouais", short_name: 'UQO', city: 'Gatineau', state: 'QC', country: 'CA', zip_code: 'J8X 3X7', latitude: 45.4258, longitude: -75.7372, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 7500, international_students: 900, website: 'https://uqo.ca', aliases: ['UQO'], source: 'universities_canada', source_id: 'uqo' },
  { id: 'ca-uqat', name: 'Université du Québec en Abitibi-Témiscamingue', short_name: 'UQAT', city: 'Rouyn-Noranda', state: 'QC', country: 'CA', zip_code: 'J9X 5E4', latitude: 48.2381, longitude: -79.0288, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 3500, international_students: 300, website: 'https://www.uqat.ca', aliases: ['UQAT'], source: 'universities_canada', source_id: 'uqat' },
  { id: 'ca-bishops', name: "Bishop's University", short_name: "Bishop's", city: 'Sherbrooke', state: 'QC', country: 'CA', zip_code: 'J1M 1Z7', latitude: 45.3667, longitude: -71.8460, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 2800, international_students: 500, website: 'https://www.ubishops.ca', aliases: ["Bishop's"], source: 'universities_canada', source_id: 'bishops' },

  // British Columbia
  { id: 'ca-ubc', name: 'University of British Columbia', short_name: 'UBC', city: 'Vancouver', state: 'BC', country: 'CA', zip_code: 'V6T 1Z4', latitude: 49.2606, longitude: -123.2460, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 71000, international_students: 18000, website: 'https://www.ubc.ca', aliases: ['UBC'], source: 'universities_canada', source_id: 'ubc' },
  { id: 'ca-ubc-okanagan', name: 'University of British Columbia Okanagan', short_name: 'UBCO', city: 'Kelowna', state: 'BC', country: 'CA', zip_code: 'V1V 1V7', latitude: 49.9401, longitude: -119.3959, type: 'university', campus_type: 'branch', sector: 'public', is_public: true, enrollment: 11000, international_students: 2500, website: 'https://ok.ubc.ca', aliases: ['UBCO', 'UBC Okanagan'], source: 'universities_canada', source_id: 'ubco' },
  { id: 'ca-sfu', name: 'Simon Fraser University', short_name: 'SFU', city: 'Burnaby', state: 'BC', country: 'CA', zip_code: 'V5A 1S6', latitude: 49.2781, longitude: -122.9199, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 35000, international_students: 7500, website: 'https://www.sfu.ca', aliases: ['SFU', 'Simon Fraser'], source: 'universities_canada', source_id: 'sfu' },
  { id: 'ca-uvic', name: 'University of Victoria', short_name: 'UVic', city: 'Victoria', state: 'BC', country: 'CA', zip_code: 'V8P 5C2', latitude: 48.4634, longitude: -123.3117, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 22000, international_students: 4500, website: 'https://www.uvic.ca', aliases: ['UVic', 'Victoria'], source: 'universities_canada', source_id: 'uvic' },
  { id: 'ca-unbc', name: 'University of Northern British Columbia', short_name: 'UNBC', city: 'Prince George', state: 'BC', country: 'CA', zip_code: 'V2N 4Z9', latitude: 53.8933, longitude: -122.8117, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 4000, international_students: 600, website: 'https://www.unbc.ca', aliases: ['UNBC'], source: 'universities_canada', source_id: 'unbc' },
  { id: 'ca-tru', name: 'Thompson Rivers University', short_name: 'TRU', city: 'Kamloops', state: 'BC', country: 'CA', zip_code: 'V2C 0C8', latitude: 50.6682, longitude: -120.3639, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 3500, website: 'https://www.tru.ca', aliases: ['TRU', 'Thompson Rivers'], source: 'universities_canada', source_id: 'tru' },
  { id: 'ca-royalroads', name: 'Royal Roads University', short_name: 'Royal Roads', city: 'Victoria', state: 'BC', country: 'CA', zip_code: 'V9B 5Y2', latitude: 48.4335, longitude: -123.4702, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 1200, website: 'https://www.royalroads.ca', aliases: ['Royal Roads', 'RRU'], source: 'universities_canada', source_id: 'royalroads' },
  { id: 'ca-capilano', name: 'Capilano University', short_name: 'CapU', city: 'North Vancouver', state: 'BC', country: 'CA', zip_code: 'V7J 3H5', latitude: 49.3501, longitude: -123.0756, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 8000, international_students: 1500, website: 'https://www.capilanou.ca', aliases: ['CapU', 'Capilano'], source: 'universities_canada', source_id: 'capilano' },
  { id: 'ca-kpu', name: 'Kwantlen Polytechnic University', short_name: 'KPU', city: 'Surrey', state: 'BC', country: 'CA', zip_code: 'V3W 2M8', latitude: 49.1328, longitude: -122.8712, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 5000, website: 'https://www.kpu.ca', aliases: ['KPU', 'Kwantlen'], source: 'universities_canada', source_id: 'kpu' },
  { id: 'ca-ufv', name: 'University of the Fraser Valley', short_name: 'UFV', city: 'Abbotsford', state: 'BC', country: 'CA', zip_code: 'V2S 7M8', latitude: 49.0303, longitude: -122.2844, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 4000, website: 'https://www.ufv.ca', aliases: ['UFV', 'Fraser Valley'], source: 'universities_canada', source_id: 'ufv' },
  { id: 'ca-ecuad', name: 'Emily Carr University of Art + Design', short_name: 'Emily Carr', city: 'Vancouver', state: 'BC', country: 'CA', zip_code: 'V6H 3R9', latitude: 49.2692, longitude: -123.1386, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 2000, international_students: 500, website: 'https://www.ecuad.ca', aliases: ['Emily Carr', 'ECUAD'], source: 'universities_canada', source_id: 'ecuad' },
  { id: 'ca-viu', name: 'Vancouver Island University', short_name: 'VIU', city: 'Nanaimo', state: 'BC', country: 'CA', zip_code: 'V9R 5S5', latitude: 49.1571, longitude: -123.9677, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 3000, website: 'https://www.viu.ca', aliases: ['VIU'], source: 'universities_canada', source_id: 'viu' },

  // Alberta
  { id: 'ca-ualberta', name: 'University of Alberta', short_name: 'UAlberta', city: 'Edmonton', state: 'AB', country: 'CA', zip_code: 'T6G 2R3', latitude: 53.5232, longitude: -113.5263, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 44000, international_students: 10000, website: 'https://www.ualberta.ca', aliases: ['UofA', 'Alberta'], source: 'universities_canada', source_id: 'ualberta' },
  { id: 'ca-ucalgary', name: 'University of Calgary', short_name: 'UCalgary', city: 'Calgary', state: 'AB', country: 'CA', zip_code: 'T2N 1N4', latitude: 51.0776, longitude: -114.1397, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 36000, international_students: 7000, website: 'https://www.ucalgary.ca', aliases: ['UCalgary', 'Calgary'], source: 'universities_canada', source_id: 'ucalgary' },
  { id: 'ca-ulethbridge', name: 'University of Lethbridge', short_name: 'ULethbridge', city: 'Lethbridge', state: 'AB', country: 'CA', zip_code: 'T1K 3M4', latitude: 49.6815, longitude: -112.8715, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 9000, international_students: 1000, website: 'https://www.uleth.ca', aliases: ['ULethbridge', 'Lethbridge'], source: 'universities_canada', source_id: 'ulethbridge' },
  { id: 'ca-athabasca', name: 'Athabasca University', short_name: 'Athabasca', city: 'Athabasca', state: 'AB', country: 'CA', zip_code: 'T9S 3A3', latitude: 54.7166, longitude: -113.2871, type: 'university', campus_type: 'online', sector: 'public', is_public: true, enrollment: 40000, international_students: 2000, website: 'https://www.athabascau.ca', aliases: ['AU', 'Athabasca'], source: 'universities_canada', source_id: 'athabasca' },
  { id: 'ca-macewan', name: 'MacEwan University', short_name: 'MacEwan', city: 'Edmonton', state: 'AB', country: 'CA', zip_code: 'T5J 4S2', latitude: 53.5472, longitude: -113.5050, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 19000, international_students: 2500, website: 'https://www.macewan.ca', aliases: ['MacEwan'], source: 'universities_canada', source_id: 'macewan' },
  { id: 'ca-mru', name: 'Mount Royal University', short_name: 'MRU', city: 'Calgary', state: 'AB', country: 'CA', zip_code: 'T3E 6K6', latitude: 51.0116, longitude: -114.1294, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 1500, website: 'https://www.mtroyal.ca', aliases: ['MRU', 'Mount Royal'], source: 'universities_canada', source_id: 'mru' },

  // Manitoba
  { id: 'ca-umanitoba', name: 'University of Manitoba', short_name: 'UManitoba', city: 'Winnipeg', state: 'MB', country: 'CA', zip_code: 'R3T 2N2', latitude: 49.8076, longitude: -97.1339, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 30000, international_students: 5000, website: 'https://umanitoba.ca', aliases: ['UofM', 'Manitoba'], source: 'universities_canada', source_id: 'umanitoba' },
  { id: 'ca-uwinnipeg', name: 'University of Winnipeg', short_name: 'UWinnipeg', city: 'Winnipeg', state: 'MB', country: 'CA', zip_code: 'R3B 2E9', latitude: 49.8916, longitude: -97.1404, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 1500, website: 'https://www.uwinnipeg.ca', aliases: ['UWinnipeg', 'Winnipeg'], source: 'universities_canada', source_id: 'uwinnipeg' },
  { id: 'ca-brandon', name: 'Brandon University', short_name: 'Brandon', city: 'Brandon', state: 'MB', country: 'CA', zip_code: 'R7A 6A9', latitude: 49.8447, longitude: -99.9532, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 3500, international_students: 400, website: 'https://www.brandonu.ca', aliases: ['Brandon', 'BU'], source: 'universities_canada', source_id: 'brandon' },

  // Saskatchewan
  { id: 'ca-usask', name: 'University of Saskatchewan', short_name: 'USask', city: 'Saskatoon', state: 'SK', country: 'CA', zip_code: 'S7N 5A2', latitude: 52.1332, longitude: -106.6314, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 26000, international_students: 4000, website: 'https://www.usask.ca', aliases: ['USask', 'Saskatchewan'], source: 'universities_canada', source_id: 'usask' },
  { id: 'ca-uregina', name: 'University of Regina', short_name: 'URegina', city: 'Regina', state: 'SK', country: 'CA', zip_code: 'S4S 0A2', latitude: 50.4193, longitude: -104.5873, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 16000, international_students: 3000, website: 'https://www.uregina.ca', aliases: ['URegina', 'Regina'], source: 'universities_canada', source_id: 'uregina' },

  // Nova Scotia
  { id: 'ca-dalhousie', name: 'Dalhousie University', short_name: 'Dal', city: 'Halifax', state: 'NS', country: 'CA', zip_code: 'B3H 4R2', latitude: 44.6366, longitude: -63.5917, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 5000, website: 'https://www.dal.ca', aliases: ['Dal', 'Dalhousie'], source: 'universities_canada', source_id: 'dalhousie' },
  { id: 'ca-smu', name: "Saint Mary's University", short_name: "Saint Mary's", city: 'Halifax', state: 'NS', country: 'CA', zip_code: 'B3H 3C3', latitude: 44.6299, longitude: -63.5789, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 7500, international_students: 2500, website: 'https://www.smu.ca', aliases: ['SMU', "Saint Mary's"], source: 'universities_canada', source_id: 'smu' },
  { id: 'ca-stfx', name: 'St. Francis Xavier University', short_name: 'StFX', city: 'Antigonish', state: 'NS', country: 'CA', zip_code: 'B2G 2W5', latitude: 45.6214, longitude: -61.9948, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 600, website: 'https://www.stfx.ca', aliases: ['StFX', 'St. Francis Xavier'], source: 'universities_canada', source_id: 'stfx' },
  { id: 'ca-acadia', name: 'Acadia University', short_name: 'Acadia', city: 'Wolfville', state: 'NS', country: 'CA', zip_code: 'B4P 2R6', latitude: 45.0867, longitude: -64.3683, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 4000, international_students: 500, website: 'https://www.acadiau.ca', aliases: ['Acadia'], source: 'universities_canada', source_id: 'acadia' },
  { id: 'ca-msvu', name: 'Mount Saint Vincent University', short_name: 'MSVU', city: 'Halifax', state: 'NS', country: 'CA', zip_code: 'B3M 2J6', latitude: 44.6768, longitude: -63.6499, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 4000, international_students: 700, website: 'https://www.msvu.ca', aliases: ['MSVU', 'The Mount'], source: 'universities_canada', source_id: 'msvu' },
  { id: 'ca-cbu', name: 'Cape Breton University', short_name: 'CBU', city: 'Sydney', state: 'NS', country: 'CA', zip_code: 'B1P 6L2', latitude: 46.1355, longitude: -60.1849, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 2000, website: 'https://www.cbu.ca', aliases: ['CBU', 'Cape Breton'], source: 'universities_canada', source_id: 'cbu' },
  { id: 'ca-nscad', name: 'NSCAD University', short_name: 'NSCAD', city: 'Halifax', state: 'NS', country: 'CA', zip_code: 'B3J 3J6', latitude: 44.6476, longitude: -63.5728, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 1000, international_students: 150, website: 'https://www.nscad.ca', aliases: ['NSCAD'], source: 'universities_canada', source_id: 'nscad' },

  // New Brunswick
  { id: 'ca-unb', name: 'University of New Brunswick', short_name: 'UNB', city: 'Fredericton', state: 'NB', country: 'CA', zip_code: 'E3B 5A3', latitude: 45.9453, longitude: -66.6409, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 2500, website: 'https://www.unb.ca', aliases: ['UNB'], source: 'universities_canada', source_id: 'unb' },
  { id: 'ca-moncton', name: 'Université de Moncton', short_name: 'UdeM', city: 'Moncton', state: 'NB', country: 'CA', zip_code: 'E1A 3E9', latitude: 46.1023, longitude: -64.7834, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6000, international_students: 800, website: 'https://www.umoncton.ca', aliases: ['UdeM Moncton'], source: 'universities_canada', source_id: 'moncton' },
  { id: 'ca-stu', name: 'St. Thomas University', short_name: 'STU', city: 'Fredericton', state: 'NB', country: 'CA', zip_code: 'E3B 5G3', latitude: 45.9468, longitude: -66.6434, type: 'university', campus_type: 'main', sector: 'private_nonprofit', is_public: false, enrollment: 2000, international_students: 200, website: 'https://www.stu.ca', aliases: ['STU', 'St. Thomas'], source: 'universities_canada', source_id: 'stu' },
  { id: 'ca-mta', name: 'Mount Allison University', short_name: 'MtA', city: 'Sackville', state: 'NB', country: 'CA', zip_code: 'E4L 1E4', latitude: 45.9022, longitude: -64.3684, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 2500, international_students: 350, website: 'https://www.mta.ca', aliases: ['MtA', 'Mount Allison'], source: 'universities_canada', source_id: 'mta' },

  // Newfoundland and Labrador
  { id: 'ca-mun', name: 'Memorial University of Newfoundland', short_name: 'MUN', city: "St. John's", state: 'NL', country: 'CA', zip_code: 'A1B 3X9', latitude: 47.5735, longitude: -52.7329, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 3500, website: 'https://www.mun.ca', aliases: ['MUN', 'Memorial'], source: 'universities_canada', source_id: 'mun' },

  // Prince Edward Island
  { id: 'ca-upei', name: 'University of Prince Edward Island', short_name: 'UPEI', city: 'Charlottetown', state: 'PE', country: 'CA', zip_code: 'C1A 4P3', latitude: 46.2596, longitude: -63.1337, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 1200, website: 'https://www.upei.ca', aliases: ['UPEI'], source: 'universities_canada', source_id: 'upei' },
];

// Major Canadian Colleges
export const CANADIAN_COLLEGES: CanadaInstitution[] = [
  // Ontario Colleges
  { id: 'ca-seneca', name: 'Seneca Polytechnic', short_name: 'Seneca', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M2J 2X5', latitude: 43.7960, longitude: -79.3486, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 12000, website: 'https://www.senecapolytechnic.ca', aliases: ['Seneca'], source: 'colleges_canada', source_id: 'seneca' },
  { id: 'ca-humber', name: 'Humber College', short_name: 'Humber', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M9W 5L7', latitude: 43.7293, longitude: -79.6079, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 33000, international_students: 11000, website: 'https://humber.ca', aliases: ['Humber'], source: 'colleges_canada', source_id: 'humber' },
  { id: 'ca-george-brown', name: 'George Brown College', short_name: 'George Brown', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M5A 4E1', latitude: 43.6511, longitude: -79.3699, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 10000, website: 'https://www.georgebrown.ca', aliases: ['GBC', 'George Brown'], source: 'colleges_canada', source_id: 'georgebrown' },
  { id: 'ca-centennial', name: 'Centennial College', short_name: 'Centennial', city: 'Toronto', state: 'ON', country: 'CA', zip_code: 'M1K 5E9', latitude: 43.7853, longitude: -79.2268, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 26000, international_students: 9000, website: 'https://www.centennialcollege.ca', aliases: ['Centennial'], source: 'colleges_canada', source_id: 'centennial' },
  { id: 'ca-sheridan', name: 'Sheridan College', short_name: 'Sheridan', city: 'Oakville', state: 'ON', country: 'CA', zip_code: 'L6H 2L1', latitude: 43.4687, longitude: -79.7003, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 24000, international_students: 7000, website: 'https://www.sheridancollege.ca', aliases: ['Sheridan'], source: 'colleges_canada', source_id: 'sheridan' },
  { id: 'ca-conestoga', name: 'Conestoga College', short_name: 'Conestoga', city: 'Kitchener', state: 'ON', country: 'CA', zip_code: 'N2G 4M4', latitude: 43.3907, longitude: -80.4045, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 26000, international_students: 8500, website: 'https://www.conestogac.on.ca', aliases: ['Conestoga'], source: 'colleges_canada', source_id: 'conestoga' },
  { id: 'ca-mohawk', name: 'Mohawk College', short_name: 'Mohawk', city: 'Hamilton', state: 'ON', country: 'CA', zip_code: 'L9C 0E5', latitude: 43.2387, longitude: -79.8881, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 6000, website: 'https://www.mohawkcollege.ca', aliases: ['Mohawk'], source: 'colleges_canada', source_id: 'mohawk' },
  { id: 'ca-fanshawe', name: 'Fanshawe College', short_name: 'Fanshawe', city: 'London', state: 'ON', country: 'CA', zip_code: 'N5Y 5R6', latitude: 43.0130, longitude: -81.2003, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 7000, website: 'https://www.fanshawec.ca', aliases: ['Fanshawe'], source: 'colleges_canada', source_id: 'fanshawe' },
  { id: 'ca-algonquin', name: 'Algonquin College', short_name: 'Algonquin', city: 'Ottawa', state: 'ON', country: 'CA', zip_code: 'K2G 1V8', latitude: 45.3508, longitude: -75.7565, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 6000, website: 'https://www.algonquincollege.com', aliases: ['Algonquin'], source: 'colleges_canada', source_id: 'algonquin' },
  { id: 'ca-durham', name: 'Durham College', short_name: 'Durham', city: 'Oshawa', state: 'ON', country: 'CA', zip_code: 'L1H 7K4', latitude: 43.9448, longitude: -78.8973, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 4000, website: 'https://durhamcollege.ca', aliases: ['Durham'], source: 'colleges_canada', source_id: 'durham' },
  { id: 'ca-niagara', name: 'Niagara College', short_name: 'Niagara', city: 'Welland', state: 'ON', country: 'CA', zip_code: 'L3C 7L3', latitude: 42.9765, longitude: -79.2567, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 13000, international_students: 5000, website: 'https://www.niagaracollege.ca', aliases: ['Niagara'], source: 'colleges_canada', source_id: 'niagara' },
  { id: 'ca-fleming', name: 'Fleming College', short_name: 'Fleming', city: 'Peterborough', state: 'ON', country: 'CA', zip_code: 'K9J 7B1', latitude: 44.3622, longitude: -78.2847, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 7000, international_students: 1500, website: 'https://flemingcollege.ca', aliases: ['Fleming'], source: 'colleges_canada', source_id: 'fleming' },
  { id: 'ca-lambton', name: 'Lambton College', short_name: 'Lambton', city: 'Sarnia', state: 'ON', country: 'CA', zip_code: 'N7S 6K4', latitude: 42.9994, longitude: -82.3842, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 2500, website: 'https://www.lambtoncollege.ca', aliases: ['Lambton'], source: 'colleges_canada', source_id: 'lambton' },
  { id: 'ca-st-clair', name: 'St. Clair College', short_name: 'St. Clair', city: 'Windsor', state: 'ON', country: 'CA', zip_code: 'N9A 6S4', latitude: 42.3193, longitude: -83.0556, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 13000, international_students: 5000, website: 'https://www.stclaircollege.ca', aliases: ['St. Clair'], source: 'colleges_canada', source_id: 'stclair' },
  { id: 'ca-georgian', name: 'Georgian College', short_name: 'Georgian', city: 'Barrie', state: 'ON', country: 'CA', zip_code: 'L4M 3X9', latitude: 44.4081, longitude: -79.6683, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 13000, international_students: 4000, website: 'https://www.georgiancollege.ca', aliases: ['Georgian'], source: 'colleges_canada', source_id: 'georgian' },
  { id: 'ca-cambrian', name: 'Cambrian College', short_name: 'Cambrian', city: 'Sudbury', state: 'ON', country: 'CA', zip_code: 'P3A 3V8', latitude: 46.4709, longitude: -81.0003, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 4500, international_students: 1000, website: 'https://cambriancollege.ca', aliases: ['Cambrian'], source: 'colleges_canada', source_id: 'cambrian' },

  // BC Colleges
  { id: 'ca-bcit', name: 'British Columbia Institute of Technology', short_name: 'BCIT', city: 'Burnaby', state: 'BC', country: 'CA', zip_code: 'V5G 3H2', latitude: 49.2500, longitude: -123.0024, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 48000, international_students: 6000, website: 'https://www.bcit.ca', aliases: ['BCIT'], source: 'colleges_canada', source_id: 'bcit' },
  { id: 'ca-langara', name: 'Langara College', short_name: 'Langara', city: 'Vancouver', state: 'BC', country: 'CA', zip_code: 'V5Y 2Z6', latitude: 49.2245, longitude: -123.1088, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 23000, international_students: 7000, website: 'https://langara.ca', aliases: ['Langara'], source: 'colleges_canada', source_id: 'langara' },
  { id: 'ca-douglas', name: 'Douglas College', short_name: 'Douglas', city: 'New Westminster', state: 'BC', country: 'CA', zip_code: 'V3L 5B2', latitude: 49.2035, longitude: -122.9127, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 25000, international_students: 8000, website: 'https://www.douglascollege.ca', aliases: ['Douglas'], source: 'colleges_canada', source_id: 'douglas' },
  { id: 'ca-camosun', name: 'Camosun College', short_name: 'Camosun', city: 'Victoria', state: 'BC', country: 'CA', zip_code: 'V8P 5J2', latitude: 48.4610, longitude: -123.3077, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 3000, website: 'https://camosun.ca', aliases: ['Camosun'], source: 'colleges_canada', source_id: 'camosun' },
  { id: 'ca-okanagan', name: 'Okanagan College', short_name: 'OC', city: 'Kelowna', state: 'BC', country: 'CA', zip_code: 'V1Y 4X8', latitude: 49.8792, longitude: -119.4379, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 9000, international_students: 2000, website: 'https://www.okanagan.bc.ca', aliases: ['Okanagan College', 'OC'], source: 'colleges_canada', source_id: 'okanagan' },

  // Alberta Colleges
  { id: 'ca-nait', name: 'Northern Alberta Institute of Technology', short_name: 'NAIT', city: 'Edmonton', state: 'AB', country: 'CA', zip_code: 'T5G 2R1', latitude: 53.5689, longitude: -113.5028, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 1500, website: 'https://www.nait.ca', aliases: ['NAIT'], source: 'colleges_canada', source_id: 'nait' },
  { id: 'ca-sait', name: 'Southern Alberta Institute of Technology', short_name: 'SAIT', city: 'Calgary', state: 'AB', country: 'CA', zip_code: 'T2M 0L4', latitude: 51.0644, longitude: -114.0883, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 2000, website: 'https://www.sait.ca', aliases: ['SAIT'], source: 'colleges_canada', source_id: 'sait' },
  { id: 'ca-bow-valley', name: 'Bow Valley College', short_name: 'Bow Valley', city: 'Calgary', state: 'AB', country: 'CA', zip_code: 'T2G 4T8', latitude: 51.0453, longitude: -114.0620, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 3000, website: 'https://bowvalleycollege.ca', aliases: ['Bow Valley'], source: 'colleges_canada', source_id: 'bowvalley' },
  { id: 'ca-norquest', name: 'NorQuest College', short_name: 'NorQuest', city: 'Edmonton', state: 'AB', country: 'CA', zip_code: 'T5J 1L4', latitude: 53.5461, longitude: -113.4938, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 2500, website: 'https://www.norquest.ca', aliases: ['NorQuest'], source: 'colleges_canada', source_id: 'norquest' },

  // Quebec CEGEPs
  { id: 'ca-dawson', name: 'Dawson College', short_name: 'Dawson', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H3Z 1A4', latitude: 45.4603, longitude: -73.5830, type: 'cegep', campus_type: 'main', sector: 'public', is_public: true, enrollment: 11000, international_students: 500, website: 'https://www.dawsoncollege.qc.ca', aliases: ['Dawson'], source: 'colleges_canada', source_id: 'dawson' },
  { id: 'ca-vanier', name: 'Vanier College', short_name: 'Vanier', city: 'Montreal', state: 'QC', country: 'CA', zip_code: 'H4L 3X9', latitude: 45.5342, longitude: -73.6702, type: 'cegep', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6500, international_students: 400, website: 'https://www.vaniercollege.qc.ca', aliases: ['Vanier'], source: 'colleges_canada', source_id: 'vanier' },
  { id: 'ca-john-abbott', name: 'John Abbott College', short_name: 'John Abbott', city: 'Sainte-Anne-de-Bellevue', state: 'QC', country: 'CA', zip_code: 'H9X 3L9', latitude: 45.4105, longitude: -73.9431, type: 'cegep', campus_type: 'main', sector: 'public', is_public: true, enrollment: 7000, international_students: 300, website: 'https://www.johnabbott.qc.ca', aliases: ['John Abbott', 'JAC'], source: 'colleges_canada', source_id: 'johnabbott' },
  { id: 'ca-marianopolis', name: 'Marianopolis College', short_name: 'Marianopolis', city: 'Westmount', state: 'QC', country: 'CA', zip_code: 'H3Y 1R9', latitude: 45.4829, longitude: -73.5925, type: 'cegep', campus_type: 'main', sector: 'private_nonprofit', is_public: false, enrollment: 2000, international_students: 150, website: 'https://www.marianopolis.edu', aliases: ['Marianopolis'], source: 'colleges_canada', source_id: 'marianopolis' },
  { id: 'ca-champlain-lennoxville', name: 'Champlain Regional College - Lennoxville', short_name: 'Champlain Lennoxville', city: 'Sherbrooke', state: 'QC', country: 'CA', zip_code: 'J1M 2A1', latitude: 45.3710, longitude: -71.8540, type: 'cegep', campus_type: 'main', sector: 'public', is_public: true, enrollment: 1500, international_students: 100, website: 'https://www.crc-lennox.qc.ca', aliases: ['Champlain Lennoxville'], source: 'colleges_canada', source_id: 'champlain-lennox' },
  { id: 'ca-champlain-stlawrence', name: 'Champlain Regional College - St-Lawrence', short_name: 'Champlain St-Lawrence', city: 'Quebec City', state: 'QC', country: 'CA', zip_code: 'G1V 4K2', latitude: 46.7800, longitude: -71.2690, type: 'cegep', campus_type: 'main', sector: 'public', is_public: true, enrollment: 1200, international_students: 80, website: 'https://slc.qc.ca', aliases: ['Champlain St-Lawrence'], source: 'colleges_canada', source_id: 'champlain-stl' },
  { id: 'ca-heritage', name: 'Heritage College', short_name: 'Heritage', city: 'Gatineau', state: 'QC', country: 'CA', zip_code: 'J8Y 6R8', latitude: 45.4475, longitude: -75.7362, type: 'cegep', campus_type: 'main', sector: 'public', is_public: true, enrollment: 1500, international_students: 100, website: 'https://www.cegep-heritage.qc.ca', aliases: ['Heritage'], source: 'colleges_canada', source_id: 'heritage' },

  // Manitoba Colleges
  { id: 'ca-rrc', name: 'Red River College Polytechnic', short_name: 'RRC', city: 'Winnipeg', state: 'MB', country: 'CA', zip_code: 'R3H 0J9', latitude: 49.8915, longitude: -97.2001, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 4000, website: 'https://www.rrc.ca', aliases: ['RRC', 'Red River'], source: 'colleges_canada', source_id: 'rrc' },

  // Nova Scotia Colleges
  { id: 'ca-nscc', name: 'Nova Scotia Community College', short_name: 'NSCC', city: 'Halifax', state: 'NS', country: 'CA', zip_code: 'B3J 2A1', latitude: 44.6488, longitude: -63.5752, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 1500, website: 'https://www.nscc.ca', aliases: ['NSCC'], source: 'colleges_canada', source_id: 'nscc' },

  // Saskatchewan Colleges
  { id: 'ca-sask-poly', name: 'Saskatchewan Polytechnic', short_name: 'Sask Polytech', city: 'Saskatoon', state: 'SK', country: 'CA', zip_code: 'S7K 3R5', latitude: 52.1332, longitude: -106.6314, type: 'college', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 2000, website: 'https://saskpolytech.ca', aliases: ['Sask Polytech', 'SIAST'], source: 'colleges_canada', source_id: 'saskpoly' },
];

// All Canadian institutions combined
export const ALL_CANADIAN_INSTITUTIONS: CanadaInstitution[] = [
  ...CANADIAN_UNIVERSITIES,
  ...CANADIAN_COLLEGES,
];

export default ALL_CANADIAN_INSTITUTIONS;
