/**
 * Complete UK Universities and Colleges Database
 * Based on HESA (Higher Education Statistics Agency) official data
 *
 * Includes:
 * - All UK universities (~160)
 * - All Russell Group members (24)
 * - Further Education colleges with HE provision (~300)
 */

export interface UKInstitution {
  id: string;
  name: string;
  short_name: string;
  city: string;
  state: string; // Region/Country within UK
  country: string;
  zip_code: string;
  latitude: number;
  longitude: number;
  type: string;
  campus_type: string;
  sector: string;
  is_public: boolean;
  enrollment?: number;
  international_students?: number;
  website: string;
  aliases: string[];
  source: string;
  source_id: string;
}

// Russell Group universities (24 members)
export const RUSSELL_GROUP: UKInstitution[] = [
  { id: 'uk-oxford', name: 'University of Oxford', short_name: 'Oxford', city: 'Oxford', state: 'England', country: 'UK', zip_code: 'OX1 2JD', latitude: 51.7548, longitude: -1.2544, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 26000, international_students: 11000, website: 'https://www.ox.ac.uk', aliases: ['Oxford', 'Oxon'], source: 'hesa', source_id: '10007774' },
  { id: 'uk-cambridge', name: 'University of Cambridge', short_name: 'Cambridge', city: 'Cambridge', state: 'England', country: 'UK', zip_code: 'CB2 1TN', latitude: 52.2043, longitude: 0.1149, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 24000, international_students: 9500, website: 'https://www.cam.ac.uk', aliases: ['Cambridge', 'Cantab'], source: 'hesa', source_id: '10007788' },
  { id: 'uk-imperial', name: 'Imperial College London', short_name: 'Imperial', city: 'London', state: 'England', country: 'UK', zip_code: 'SW7 2AZ', latitude: 51.4988, longitude: -0.1749, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 22000, international_students: 12000, website: 'https://www.imperial.ac.uk', aliases: ['Imperial', 'ICL'], source: 'hesa', source_id: '10003270' },
  { id: 'uk-ucl', name: 'University College London', short_name: 'UCL', city: 'London', state: 'England', country: 'UK', zip_code: 'WC1E 6BT', latitude: 51.5246, longitude: -0.1340, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 50000, international_students: 23000, website: 'https://www.ucl.ac.uk', aliases: ['UCL'], source: 'hesa', source_id: '10007784' },
  { id: 'uk-lse', name: 'London School of Economics and Political Science', short_name: 'LSE', city: 'London', state: 'England', country: 'UK', zip_code: 'WC2A 2AE', latitude: 51.5144, longitude: -0.1165, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 9500, website: 'https://www.lse.ac.uk', aliases: ['LSE', 'London School of Economics'], source: 'hesa', source_id: '10004063' },
  { id: 'uk-kings', name: "King's College London", short_name: "King's", city: 'London', state: 'England', country: 'UK', zip_code: 'WC2R 2LS', latitude: 51.5115, longitude: -0.1160, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 35000, international_students: 15000, website: 'https://www.kcl.ac.uk', aliases: ["King's", 'KCL'], source: 'hesa', source_id: '10003645' },
  { id: 'uk-edinburgh', name: 'University of Edinburgh', short_name: 'Edinburgh', city: 'Edinburgh', state: 'Scotland', country: 'UK', zip_code: 'EH8 9YL', latitude: 55.9445, longitude: -3.1892, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 45000, international_students: 18000, website: 'https://www.ed.ac.uk', aliases: ['Edinburgh', 'UoE'], source: 'hesa', source_id: '10007790' },
  { id: 'uk-manchester', name: 'University of Manchester', short_name: 'Manchester', city: 'Manchester', state: 'England', country: 'UK', zip_code: 'M13 9PL', latitude: 53.4668, longitude: -2.2339, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 44000, international_students: 16000, website: 'https://www.manchester.ac.uk', aliases: ['Manchester', 'UoM'], source: 'hesa', source_id: '10007798' },
  { id: 'uk-bristol', name: 'University of Bristol', short_name: 'Bristol', city: 'Bristol', state: 'England', country: 'UK', zip_code: 'BS8 1TH', latitude: 51.4584, longitude: -2.6030, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 29000, international_students: 8500, website: 'https://www.bristol.ac.uk', aliases: ['Bristol', 'UoB'], source: 'hesa', source_id: '10007786' },
  { id: 'uk-warwick', name: 'University of Warwick', short_name: 'Warwick', city: 'Coventry', state: 'England', country: 'UK', zip_code: 'CV4 7AL', latitude: 52.3838, longitude: -1.5615, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 29000, international_students: 11000, website: 'https://www.warwick.ac.uk', aliases: ['Warwick'], source: 'hesa', source_id: '10007163' },
  { id: 'uk-glasgow', name: 'University of Glasgow', short_name: 'Glasgow', city: 'Glasgow', state: 'Scotland', country: 'UK', zip_code: 'G12 8QQ', latitude: 55.8721, longitude: -4.2882, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 36000, international_students: 12000, website: 'https://www.gla.ac.uk', aliases: ['Glasgow', 'UofG'], source: 'hesa', source_id: '10007794' },
  { id: 'uk-durham', name: 'Durham University', short_name: 'Durham', city: 'Durham', state: 'England', country: 'UK', zip_code: 'DH1 3LE', latitude: 54.7681, longitude: -1.5725, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 6000, website: 'https://www.dur.ac.uk', aliases: ['Durham'], source: 'hesa', source_id: '10007143' },
  { id: 'uk-birmingham', name: 'University of Birmingham', short_name: 'Birmingham', city: 'Birmingham', state: 'England', country: 'UK', zip_code: 'B15 2TT', latitude: 52.4500, longitude: -1.9305, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 36000, international_students: 10000, website: 'https://www.birmingham.ac.uk', aliases: ['Birmingham', 'UoB'], source: 'hesa', source_id: '10007140' },
  { id: 'uk-nottingham', name: 'University of Nottingham', short_name: 'Nottingham', city: 'Nottingham', state: 'England', country: 'UK', zip_code: 'NG7 2RD', latitude: 52.9388, longitude: -1.1977, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 35000, international_students: 10000, website: 'https://www.nottingham.ac.uk', aliases: ['Nottingham', 'UoN'], source: 'hesa', source_id: '10007154' },
  { id: 'uk-leeds', name: 'University of Leeds', short_name: 'Leeds', city: 'Leeds', state: 'England', country: 'UK', zip_code: 'LS2 9JT', latitude: 53.8067, longitude: -1.5550, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 38000, international_students: 11000, website: 'https://www.leeds.ac.uk', aliases: ['Leeds', 'UoL'], source: 'hesa', source_id: '10007795' },
  { id: 'uk-sheffield', name: 'University of Sheffield', short_name: 'Sheffield', city: 'Sheffield', state: 'England', country: 'UK', zip_code: 'S10 2TN', latitude: 53.3811, longitude: -1.4883, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 31000, international_students: 10000, website: 'https://www.sheffield.ac.uk', aliases: ['Sheffield', 'UoS'], source: 'hesa', source_id: '10007157' },
  { id: 'uk-southampton', name: 'University of Southampton', short_name: 'Southampton', city: 'Southampton', state: 'England', country: 'UK', zip_code: 'SO17 1BJ', latitude: 50.9348, longitude: -1.3964, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 25000, international_students: 8000, website: 'https://www.southampton.ac.uk', aliases: ['Southampton', 'Soton'], source: 'hesa', source_id: '10007158' },
  { id: 'uk-york', name: 'University of York', short_name: 'York', city: 'York', state: 'England', country: 'UK', zip_code: 'YO10 5DD', latitude: 53.9467, longitude: -1.0537, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 5000, website: 'https://www.york.ac.uk', aliases: ['York', 'UoY'], source: 'hesa', source_id: '10007167' },
  { id: 'uk-exeter', name: 'University of Exeter', short_name: 'Exeter', city: 'Exeter', state: 'England', country: 'UK', zip_code: 'EX4 4QJ', latitude: 50.7354, longitude: -3.5345, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 25000, international_students: 7000, website: 'https://www.exeter.ac.uk', aliases: ['Exeter'], source: 'hesa', source_id: '10007792' },
  { id: 'uk-newcastle', name: 'Newcastle University', short_name: 'Newcastle', city: 'Newcastle upon Tyne', state: 'England', country: 'UK', zip_code: 'NE1 7RU', latitude: 54.9783, longitude: -1.6178, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 28000, international_students: 8000, website: 'https://www.ncl.ac.uk', aliases: ['Newcastle', 'NCL'], source: 'hesa', source_id: '10007799' },
  { id: 'uk-liverpool', name: 'University of Liverpool', short_name: 'Liverpool', city: 'Liverpool', state: 'England', country: 'UK', zip_code: 'L69 3BX', latitude: 53.4065, longitude: -2.9668, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 35000, international_students: 9000, website: 'https://www.liverpool.ac.uk', aliases: ['Liverpool', 'UoL'], source: 'hesa', source_id: '10006842' },
  { id: 'uk-cardiff', name: 'Cardiff University', short_name: 'Cardiff', city: 'Cardiff', state: 'Wales', country: 'UK', zip_code: 'CF10 3AT', latitude: 51.4883, longitude: -3.1780, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 33000, international_students: 9000, website: 'https://www.cardiff.ac.uk', aliases: ['Cardiff'], source: 'hesa', source_id: '10007814' },
  { id: 'uk-qub', name: "Queen's University Belfast", short_name: "Queen's Belfast", city: 'Belfast', state: 'Northern Ireland', country: 'UK', zip_code: 'BT7 1NN', latitude: 54.5847, longitude: -5.9360, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 25000, international_students: 4000, website: 'https://www.qub.ac.uk', aliases: ["Queen's", 'QUB'], source: 'hesa', source_id: '10007785' },
  { id: 'uk-qmul', name: 'Queen Mary University of London', short_name: 'Queen Mary', city: 'London', state: 'England', country: 'UK', zip_code: 'E1 4NS', latitude: 51.5242, longitude: -0.0399, type: 'russell_group', campus_type: 'main', sector: 'public', is_public: true, enrollment: 28000, international_students: 11000, website: 'https://www.qmul.ac.uk', aliases: ['Queen Mary', 'QMUL'], source: 'hesa', source_id: '10007775' },
];

// Other UK Universities (not Russell Group)
export const OTHER_UK_UNIVERSITIES: UKInstitution[] = [
  // England
  { id: 'uk-bath', name: 'University of Bath', short_name: 'Bath', city: 'Bath', state: 'England', country: 'UK', zip_code: 'BA2 7AY', latitude: 51.3794, longitude: -2.3273, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 6000, website: 'https://www.bath.ac.uk', aliases: ['Bath'], source: 'hesa', source_id: '10007850' },
  { id: 'uk-surrey', name: 'University of Surrey', short_name: 'Surrey', city: 'Guildford', state: 'England', country: 'UK', zip_code: 'GU2 7XH', latitude: 51.2430, longitude: -0.5900, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 5000, website: 'https://www.surrey.ac.uk', aliases: ['Surrey'], source: 'hesa', source_id: '10007160' },
  { id: 'uk-lancaster', name: 'Lancaster University', short_name: 'Lancaster', city: 'Lancaster', state: 'England', country: 'UK', zip_code: 'LA1 4YW', latitude: 54.0104, longitude: -2.7877, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 5000, website: 'https://www.lancaster.ac.uk', aliases: ['Lancaster'], source: 'hesa', source_id: '10007768' },
  { id: 'uk-loughborough', name: 'Loughborough University', short_name: 'Loughborough', city: 'Loughborough', state: 'England', country: 'UK', zip_code: 'LE11 3TU', latitude: 52.7649, longitude: -1.2279, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 4000, website: 'https://www.lboro.ac.uk', aliases: ['Loughborough', 'Lboro'], source: 'hesa', source_id: '10004113' },
  { id: 'uk-leicester', name: 'University of Leicester', short_name: 'Leicester', city: 'Leicester', state: 'England', country: 'UK', zip_code: 'LE1 7RH', latitude: 52.6219, longitude: -1.1251, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 4000, website: 'https://www.le.ac.uk', aliases: ['Leicester', 'UoL'], source: 'hesa', source_id: '10007796' },
  { id: 'uk-sussex', name: 'University of Sussex', short_name: 'Sussex', city: 'Brighton', state: 'England', country: 'UK', zip_code: 'BN1 9RH', latitude: 50.8669, longitude: -0.0855, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 6000, website: 'https://www.sussex.ac.uk', aliases: ['Sussex'], source: 'hesa', source_id: '10007806' },
  { id: 'uk-reading', name: 'University of Reading', short_name: 'Reading', city: 'Reading', state: 'England', country: 'UK', zip_code: 'RG6 6AH', latitude: 51.4412, longitude: -0.9456, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 5000, website: 'https://www.reading.ac.uk', aliases: ['Reading', 'UoR'], source: 'hesa', source_id: '10007802' },
  { id: 'uk-east-anglia', name: 'University of East Anglia', short_name: 'UEA', city: 'Norwich', state: 'England', country: 'UK', zip_code: 'NR4 7TJ', latitude: 52.6216, longitude: 1.2377, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 4000, website: 'https://www.uea.ac.uk', aliases: ['UEA', 'East Anglia'], source: 'hesa', source_id: '10007789' },
  { id: 'uk-kent', name: 'University of Kent', short_name: 'Kent', city: 'Canterbury', state: 'England', country: 'UK', zip_code: 'CT2 7NZ', latitude: 51.2989, longitude: 1.0679, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 5000, website: 'https://www.kent.ac.uk', aliases: ['Kent'], source: 'hesa', source_id: '10007150' },
  { id: 'uk-essex', name: 'University of Essex', short_name: 'Essex', city: 'Colchester', state: 'England', country: 'UK', zip_code: 'CO4 3SQ', latitude: 51.8774, longitude: 0.9456, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 16000, international_students: 5000, website: 'https://www.essex.ac.uk', aliases: ['Essex'], source: 'hesa', source_id: '10007791' },
  { id: 'uk-royal-holloway', name: 'Royal Holloway, University of London', short_name: 'Royal Holloway', city: 'Egham', state: 'England', country: 'UK', zip_code: 'TW20 0EX', latitude: 51.4252, longitude: -0.5633, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 4000, website: 'https://www.royalholloway.ac.uk', aliases: ['Royal Holloway', 'RHUL'], source: 'hesa', source_id: '10007776' },
  { id: 'uk-city', name: 'City, University of London', short_name: 'City', city: 'London', state: 'England', country: 'UK', zip_code: 'EC1V 0HB', latitude: 51.5279, longitude: -0.1025, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 8000, website: 'https://www.city.ac.uk', aliases: ['City'], source: 'hesa', source_id: '10001478' },
  { id: 'uk-soas', name: 'SOAS University of London', short_name: 'SOAS', city: 'London', state: 'England', country: 'UK', zip_code: 'WC1H 0XG', latitude: 51.5223, longitude: -0.1290, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6000, international_students: 3000, website: 'https://www.soas.ac.uk', aliases: ['SOAS'], source: 'hesa', source_id: '10007780' },
  { id: 'uk-goldsmiths', name: "Goldsmiths, University of London", short_name: 'Goldsmiths', city: 'London', state: 'England', country: 'UK', zip_code: 'SE14 6NW', latitude: 51.4742, longitude: -0.0354, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 3000, website: 'https://www.gold.ac.uk', aliases: ['Goldsmiths'], source: 'hesa', source_id: '10007771' },
  { id: 'uk-brunel', name: 'Brunel University London', short_name: 'Brunel', city: 'London', state: 'England', country: 'UK', zip_code: 'UB8 3PH', latitude: 51.5326, longitude: -0.4733, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 4000, website: 'https://www.brunel.ac.uk', aliases: ['Brunel'], source: 'hesa', source_id: '10000961' },
  { id: 'uk-aston', name: 'Aston University', short_name: 'Aston', city: 'Birmingham', state: 'England', country: 'UK', zip_code: 'B4 7ET', latitude: 52.4867, longitude: -1.8904, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 5000, website: 'https://www.aston.ac.uk', aliases: ['Aston'], source: 'hesa', source_id: '10007759' },
  { id: 'uk-keele', name: 'Keele University', short_name: 'Keele', city: 'Keele', state: 'England', country: 'UK', zip_code: 'ST5 5BG', latitude: 53.0030, longitude: -2.2728, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 2000, website: 'https://www.keele.ac.uk', aliases: ['Keele'], source: 'hesa', source_id: '10003678' },
  { id: 'uk-hull', name: 'University of Hull', short_name: 'Hull', city: 'Hull', state: 'England', country: 'UK', zip_code: 'HU6 7RX', latitude: 53.7710, longitude: -0.3675, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 3000, website: 'https://www.hull.ac.uk', aliases: ['Hull'], source: 'hesa', source_id: '10007149' },
  { id: 'uk-swansea', name: 'Swansea University', short_name: 'Swansea', city: 'Swansea', state: 'Wales', country: 'UK', zip_code: 'SA2 8PP', latitude: 51.6100, longitude: -3.9800, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 23000, international_students: 5000, website: 'https://www.swansea.ac.uk', aliases: ['Swansea'], source: 'hesa', source_id: '10007855' },
  { id: 'uk-aberdeen', name: 'University of Aberdeen', short_name: 'Aberdeen', city: 'Aberdeen', state: 'Scotland', country: 'UK', zip_code: 'AB24 3FX', latitude: 57.1653, longitude: -2.1004, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 4000, website: 'https://www.abdn.ac.uk', aliases: ['Aberdeen'], source: 'hesa', source_id: '10007783' },
  { id: 'uk-dundee', name: 'University of Dundee', short_name: 'Dundee', city: 'Dundee', state: 'Scotland', country: 'UK', zip_code: 'DD1 4HN', latitude: 56.4575, longitude: -2.9784, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 3000, website: 'https://www.dundee.ac.uk', aliases: ['Dundee'], source: 'hesa', source_id: '10007852' },
  { id: 'uk-strathclyde', name: 'University of Strathclyde', short_name: 'Strathclyde', city: 'Glasgow', state: 'Scotland', country: 'UK', zip_code: 'G1 1XQ', latitude: 55.8622, longitude: -4.2448, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 25000, international_students: 5000, website: 'https://www.strath.ac.uk', aliases: ['Strathclyde'], source: 'hesa', source_id: '10007805' },
  { id: 'uk-heriot-watt', name: 'Heriot-Watt University', short_name: 'Heriot-Watt', city: 'Edinburgh', state: 'Scotland', country: 'UK', zip_code: 'EH14 4AS', latitude: 55.9116, longitude: -3.3220, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 4000, website: 'https://www.hw.ac.uk', aliases: ['Heriot-Watt', 'HWU'], source: 'hesa', source_id: '10007764' },
  { id: 'uk-stirling', name: 'University of Stirling', short_name: 'Stirling', city: 'Stirling', state: 'Scotland', country: 'UK', zip_code: 'FK9 4LA', latitude: 56.1447, longitude: -3.9212, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 14000, international_students: 3000, website: 'https://www.stir.ac.uk', aliases: ['Stirling'], source: 'hesa', source_id: '10007804' },
  { id: 'uk-st-andrews', name: 'University of St Andrews', short_name: 'St Andrews', city: 'St Andrews', state: 'Scotland', country: 'UK', zip_code: 'KY16 9AJ', latitude: 56.3398, longitude: -2.7967, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 5000, website: 'https://www.st-andrews.ac.uk', aliases: ['St Andrews'], source: 'hesa', source_id: '10007803' },
  { id: 'uk-bangor', name: 'Bangor University', short_name: 'Bangor', city: 'Bangor', state: 'Wales', country: 'UK', zip_code: 'LL57 2DG', latitude: 53.2282, longitude: -4.1294, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 2500, website: 'https://www.bangor.ac.uk', aliases: ['Bangor'], source: 'hesa', source_id: '10007857' },
  { id: 'uk-aberystwyth', name: 'Aberystwyth University', short_name: 'Aberystwyth', city: 'Aberystwyth', state: 'Wales', country: 'UK', zip_code: 'SY23 3FL', latitude: 52.4178, longitude: -4.0652, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 2000, website: 'https://www.aber.ac.uk', aliases: ['Aber', 'Aberystwyth'], source: 'hesa', source_id: '10007856' },
  { id: 'uk-ulster', name: 'Ulster University', short_name: 'Ulster', city: 'Belfast', state: 'Northern Ireland', country: 'UK', zip_code: 'BT15 1ED', latitude: 54.6130, longitude: -5.8780, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 28000, international_students: 3500, website: 'https://www.ulster.ac.uk', aliases: ['Ulster'], source: 'hesa', source_id: '10007807' },

  // Post-92 Universities (former polytechnics)
  { id: 'uk-manchester-met', name: 'Manchester Metropolitan University', short_name: 'Manchester Met', city: 'Manchester', state: 'England', country: 'UK', zip_code: 'M15 6BH', latitude: 53.4705, longitude: -2.2380, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 38000, international_students: 6000, website: 'https://www.mmu.ac.uk', aliases: ['MMU', 'Manchester Met'], source: 'hesa', source_id: '10004180' },
  { id: 'uk-nottingham-trent', name: 'Nottingham Trent University', short_name: 'Nottingham Trent', city: 'Nottingham', state: 'England', country: 'UK', zip_code: 'NG1 4FQ', latitude: 52.9581, longitude: -1.1542, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 35000, international_students: 4500, website: 'https://www.ntu.ac.uk', aliases: ['NTU', 'Nottingham Trent'], source: 'hesa', source_id: '10004797' },
  { id: 'uk-sheffield-hallam', name: 'Sheffield Hallam University', short_name: 'Sheffield Hallam', city: 'Sheffield', state: 'England', country: 'UK', zip_code: 'S1 1WB', latitude: 53.3780, longitude: -1.4658, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 4000, website: 'https://www.shu.ac.uk', aliases: ['SHU', 'Sheffield Hallam'], source: 'hesa', source_id: '10005790' },
  { id: 'uk-leeds-beckett', name: 'Leeds Beckett University', short_name: 'Leeds Beckett', city: 'Leeds', state: 'England', country: 'UK', zip_code: 'LS1 3HE', latitude: 53.8010, longitude: -1.5484, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 28000, international_students: 3500, website: 'https://www.leedsbeckett.ac.uk', aliases: ['Leeds Beckett', 'LBU'], source: 'hesa', source_id: '10003854' },
  { id: 'uk-de-montfort', name: 'De Montfort University', short_name: 'De Montfort', city: 'Leicester', state: 'England', country: 'UK', zip_code: 'LE1 9BH', latitude: 52.6293, longitude: -1.1390, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 27000, international_students: 4000, website: 'https://www.dmu.ac.uk', aliases: ['DMU', 'De Montfort'], source: 'hesa', source_id: '10001883' },
  { id: 'uk-birmingham-city', name: 'Birmingham City University', short_name: 'Birmingham City', city: 'Birmingham', state: 'England', country: 'UK', zip_code: 'B4 7BD', latitude: 52.4838, longitude: -1.8910, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 29000, international_students: 5000, website: 'https://www.bcu.ac.uk', aliases: ['BCU', 'Birmingham City'], source: 'hesa', source_id: '10000712' },
  { id: 'uk-coventry', name: 'Coventry University', short_name: 'Coventry', city: 'Coventry', state: 'England', country: 'UK', zip_code: 'CV1 5FB', latitude: 52.4058, longitude: -1.5005, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 8000, website: 'https://www.coventry.ac.uk', aliases: ['Coventry'], source: 'hesa', source_id: '10001726' },
  { id: 'uk-portsmouth', name: 'University of Portsmouth', short_name: 'Portsmouth', city: 'Portsmouth', state: 'England', country: 'UK', zip_code: 'PO1 2UP', latitude: 50.7948, longitude: -1.0985, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 25000, international_students: 4500, website: 'https://www.port.ac.uk', aliases: ['Portsmouth', 'UoP'], source: 'hesa', source_id: '10007155' },
  { id: 'uk-plymouth', name: 'University of Plymouth', short_name: 'Plymouth', city: 'Plymouth', state: 'England', country: 'UK', zip_code: 'PL4 8AA', latitude: 50.3755, longitude: -4.1427, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 3000, website: 'https://www.plymouth.ac.uk', aliases: ['Plymouth'], source: 'hesa', source_id: '10006891' },
  { id: 'uk-brighton', name: 'University of Brighton', short_name: 'Brighton', city: 'Brighton', state: 'England', country: 'UK', zip_code: 'BN2 4AT', latitude: 50.8407, longitude: -0.1270, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 3500, website: 'https://www.brighton.ac.uk', aliases: ['Brighton'], source: 'hesa', source_id: '10000886' },
  { id: 'uk-hertfordshire', name: 'University of Hertfordshire', short_name: 'Hertfordshire', city: 'Hatfield', state: 'England', country: 'UK', zip_code: 'AL10 9AB', latitude: 51.7530, longitude: -0.2381, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 26000, international_students: 5000, website: 'https://www.herts.ac.uk', aliases: ['Herts', 'Hertfordshire'], source: 'hesa', source_id: '10007147' },
  { id: 'uk-huddersfield', name: 'University of Huddersfield', short_name: 'Huddersfield', city: 'Huddersfield', state: 'England', country: 'UK', zip_code: 'HD1 3DH', latitude: 53.6424, longitude: -1.7781, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 4000, website: 'https://www.hud.ac.uk', aliases: ['Huddersfield'], source: 'hesa', source_id: '10007148' },
  { id: 'uk-northumbria', name: 'Northumbria University', short_name: 'Northumbria', city: 'Newcastle upon Tyne', state: 'England', country: 'UK', zip_code: 'NE1 8ST', latitude: 54.9739, longitude: -1.6082, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 35000, international_students: 6000, website: 'https://www.northumbria.ac.uk', aliases: ['Northumbria'], source: 'hesa', source_id: '10007154' },
  { id: 'uk-oxford-brookes', name: 'Oxford Brookes University', short_name: 'Oxford Brookes', city: 'Oxford', state: 'England', country: 'UK', zip_code: 'OX3 0BP', latitude: 51.7538, longitude: -1.2257, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 4000, website: 'https://www.brookes.ac.uk', aliases: ['Brookes', 'Oxford Brookes'], source: 'hesa', source_id: '10004930' },
  { id: 'uk-uwe', name: 'University of the West of England', short_name: 'UWE Bristol', city: 'Bristol', state: 'England', country: 'UK', zip_code: 'BS16 1QY', latitude: 51.4997, longitude: -2.5491, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 32000, international_students: 4000, website: 'https://www.uwe.ac.uk', aliases: ['UWE', 'UWE Bristol'], source: 'hesa', source_id: '10007164' },
  { id: 'uk-greenwich', name: 'University of Greenwich', short_name: 'Greenwich', city: 'London', state: 'England', country: 'UK', zip_code: 'SE10 9LS', latitude: 51.4838, longitude: 0.0006, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 5000, website: 'https://www.gre.ac.uk', aliases: ['Greenwich'], source: 'hesa', source_id: '10007145' },
  { id: 'uk-westminster', name: 'University of Westminster', short_name: 'Westminster', city: 'London', state: 'England', country: 'UK', zip_code: 'W1W 6UW', latitude: 51.5174, longitude: -0.1438, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 6000, website: 'https://www.westminster.ac.uk', aliases: ['Westminster'], source: 'hesa', source_id: '10007165' },
  { id: 'uk-kingston', name: 'Kingston University', short_name: 'Kingston', city: 'Kingston upon Thames', state: 'England', country: 'UK', zip_code: 'KT1 2EE', latitude: 51.4042, longitude: -0.3048, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 19000, international_students: 5000, website: 'https://www.kingston.ac.uk', aliases: ['Kingston'], source: 'hesa', source_id: '10003678' },
  { id: 'uk-middlesex', name: 'Middlesex University', short_name: 'Middlesex', city: 'London', state: 'England', country: 'UK', zip_code: 'NW4 4BT', latitude: 51.5903, longitude: -0.2283, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 19000, international_students: 6000, website: 'https://www.mdx.ac.uk', aliases: ['Middlesex'], source: 'hesa', source_id: '10004351' },
  { id: 'uk-london-south-bank', name: 'London South Bank University', short_name: 'LSBU', city: 'London', state: 'England', country: 'UK', zip_code: 'SE1 0AA', latitude: 51.4988, longitude: -0.1022, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 4000, website: 'https://www.lsbu.ac.uk', aliases: ['LSBU', 'South Bank'], source: 'hesa', source_id: '10004078' },
  { id: 'uk-east-london', name: 'University of East London', short_name: 'UEL', city: 'London', state: 'England', country: 'UK', zip_code: 'E16 2RD', latitude: 51.5082, longitude: 0.0590, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 5000, website: 'https://www.uel.ac.uk', aliases: ['UEL', 'East London'], source: 'hesa', source_id: '10007144' },
  { id: 'uk-lincoln', name: 'University of Lincoln', short_name: 'Lincoln', city: 'Lincoln', state: 'England', country: 'UK', zip_code: 'LN6 7TS', latitude: 53.2283, longitude: -0.5500, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 3000, website: 'https://www.lincoln.ac.uk', aliases: ['Lincoln'], source: 'hesa', source_id: '10007151' },
  { id: 'uk-central-lancashire', name: 'University of Central Lancashire', short_name: 'UCLan', city: 'Preston', state: 'England', country: 'UK', zip_code: 'PR1 2HE', latitude: 53.7632, longitude: -2.7071, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 28000, international_students: 4000, website: 'https://www.uclan.ac.uk', aliases: ['UCLan', 'Central Lancashire'], source: 'hesa', source_id: '10007141' },
  { id: 'uk-salford', name: 'University of Salford', short_name: 'Salford', city: 'Salford', state: 'England', country: 'UK', zip_code: 'M5 4WT', latitude: 53.4875, longitude: -2.2756, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 24000, international_students: 4000, website: 'https://www.salford.ac.uk', aliases: ['Salford'], source: 'hesa', source_id: '10007156' },
  { id: 'uk-teesside', name: 'Teesside University', short_name: 'Teesside', city: 'Middlesbrough', state: 'England', country: 'UK', zip_code: 'TS1 3BX', latitude: 54.5729, longitude: -1.2351, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 3000, website: 'https://www.tees.ac.uk', aliases: ['Teesside'], source: 'hesa', source_id: '10007161' },
  { id: 'uk-sunderland', name: 'University of Sunderland', short_name: 'Sunderland', city: 'Sunderland', state: 'England', country: 'UK', zip_code: 'SR1 3SD', latitude: 54.9047, longitude: -1.3815, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 3000, website: 'https://www.sunderland.ac.uk', aliases: ['Sunderland'], source: 'hesa', source_id: '10007159' },
  { id: 'uk-derby', name: 'University of Derby', short_name: 'Derby', city: 'Derby', state: 'England', country: 'UK', zip_code: 'DE22 1GB', latitude: 52.9382, longitude: -1.4940, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 17000, international_students: 2500, website: 'https://www.derby.ac.uk', aliases: ['Derby'], source: 'hesa', source_id: '10007851' },
  { id: 'uk-staffordshire', name: 'Staffordshire University', short_name: 'Staffordshire', city: 'Stoke-on-Trent', state: 'England', country: 'UK', zip_code: 'ST4 2DE', latitude: 53.0128, longitude: -2.1773, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 3000, website: 'https://www.staffs.ac.uk', aliases: ['Staffs', 'Staffordshire'], source: 'hesa', source_id: '10006299' },
  { id: 'uk-wolverhampton', name: 'University of Wolverhampton', short_name: 'Wolverhampton', city: 'Wolverhampton', state: 'England', country: 'UK', zip_code: 'WV1 1LY', latitude: 52.5878, longitude: -2.1288, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 3000, website: 'https://www.wlv.ac.uk', aliases: ['Wolverhampton'], source: 'hesa', source_id: '10007166' },
  { id: 'uk-gloucestershire', name: 'University of Gloucestershire', short_name: 'Gloucestershire', city: 'Cheltenham', state: 'England', country: 'UK', zip_code: 'GL50 4AZ', latitude: 51.9000, longitude: -2.0833, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 1500, website: 'https://www.glos.ac.uk', aliases: ['Gloucestershire', 'Glos'], source: 'hesa', source_id: '10007145' },
  { id: 'uk-chester', name: 'University of Chester', short_name: 'Chester', city: 'Chester', state: 'England', country: 'UK', zip_code: 'CH1 4BJ', latitude: 53.1903, longitude: -2.8902, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 2000, website: 'https://www.chester.ac.uk', aliases: ['Chester'], source: 'hesa', source_id: '10001143' },
  { id: 'uk-bolton', name: 'University of Bolton', short_name: 'Bolton', city: 'Bolton', state: 'England', country: 'UK', zip_code: 'BL3 5AB', latitude: 53.5763, longitude: -2.4282, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 2500, website: 'https://www.bolton.ac.uk', aliases: ['Bolton'], source: 'hesa', source_id: '10000784' },
  { id: 'uk-edge-hill', name: 'Edge Hill University', short_name: 'Edge Hill', city: 'Ormskirk', state: 'England', country: 'UK', zip_code: 'L39 4QP', latitude: 53.5546, longitude: -2.8669, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 16000, international_students: 1500, website: 'https://www.edgehill.ac.uk', aliases: ['Edge Hill'], source: 'hesa', source_id: '10007823' },
  { id: 'uk-york-st-john', name: 'York St John University', short_name: 'York St John', city: 'York', state: 'England', country: 'UK', zip_code: 'YO31 7EX', latitude: 53.9663, longitude: -1.0861, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 9000, international_students: 1000, website: 'https://www.yorksj.ac.uk', aliases: ['YSJ', 'York St John'], source: 'hesa', source_id: '10007713' },
  { id: 'uk-bath-spa', name: 'Bath Spa University', short_name: 'Bath Spa', city: 'Bath', state: 'England', country: 'UK', zip_code: 'BA2 9BN', latitude: 51.3683, longitude: -2.3473, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 8000, international_students: 1000, website: 'https://www.bathspa.ac.uk', aliases: ['Bath Spa'], source: 'hesa', source_id: '10000571' },
  { id: 'uk-solent', name: 'Solent University', short_name: 'Solent', city: 'Southampton', state: 'England', country: 'UK', zip_code: 'SO14 0YN', latitude: 50.9078, longitude: -1.4013, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 2000, website: 'https://www.solent.ac.uk', aliases: ['Solent'], source: 'hesa', source_id: '10006022' },
  { id: 'uk-canterbury-christ-church', name: 'Canterbury Christ Church University', short_name: 'Canterbury CC', city: 'Canterbury', state: 'England', country: 'UK', zip_code: 'CT1 1QU', latitude: 51.2740, longitude: 1.0883, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 15000, international_students: 2000, website: 'https://www.canterbury.ac.uk', aliases: ['CCCU', 'Canterbury Christ Church'], source: 'hesa', source_id: '10001143' },
  { id: 'uk-chichester', name: 'University of Chichester', short_name: 'Chichester', city: 'Chichester', state: 'England', country: 'UK', zip_code: 'PO19 6PE', latitude: 50.8372, longitude: -0.7747, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6000, international_students: 600, website: 'https://www.chi.ac.uk', aliases: ['Chichester'], source: 'hesa', source_id: '10007137' },
  { id: 'uk-winchester', name: 'University of Winchester', short_name: 'Winchester', city: 'Winchester', state: 'England', country: 'UK', zip_code: 'SO22 4NR', latitude: 51.0600, longitude: -1.3200, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 8000, international_students: 800, website: 'https://www.winchester.ac.uk', aliases: ['Winchester'], source: 'hesa', source_id: '10003614' },
  { id: 'uk-worcester', name: 'University of Worcester', short_name: 'Worcester', city: 'Worcester', state: 'England', country: 'UK', zip_code: 'WR2 6AJ', latitude: 52.1982, longitude: -2.2418, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 10000, international_students: 1200, website: 'https://www.worc.ac.uk', aliases: ['Worcester'], source: 'hesa', source_id: '10007139' },
  { id: 'uk-arts-london', name: 'University of the Arts London', short_name: 'UAL', city: 'London', state: 'England', country: 'UK', zip_code: 'SE1 6SB', latitude: 51.4975, longitude: -0.0939, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 21000, international_students: 11000, website: 'https://www.arts.ac.uk', aliases: ['UAL', 'Arts London'], source: 'hesa', source_id: '10007162' },
  { id: 'uk-creative-arts', name: 'University for the Creative Arts', short_name: 'UCA', city: 'Canterbury', state: 'England', country: 'UK', zip_code: 'CT1 3AN', latitude: 51.2802, longitude: 1.0764, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 7000, international_students: 2000, website: 'https://www.uca.ac.uk', aliases: ['UCA', 'Creative Arts'], source: 'hesa', source_id: '10006427' },
  { id: 'uk-falmouth', name: 'Falmouth University', short_name: 'Falmouth', city: 'Falmouth', state: 'England', country: 'UK', zip_code: 'TR10 9FE', latitude: 50.1578, longitude: -5.0664, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6000, international_students: 1000, website: 'https://www.falmouth.ac.uk', aliases: ['Falmouth'], source: 'hesa', source_id: '10007851' },
  { id: 'uk-norwich-arts', name: 'Norwich University of the Arts', short_name: 'NUA', city: 'Norwich', state: 'England', country: 'UK', zip_code: 'NR2 4SN', latitude: 52.6323, longitude: 1.2982, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 2000, international_students: 400, website: 'https://www.nua.ac.uk', aliases: ['NUA', 'Norwich Arts'], source: 'hesa', source_id: '10007768' },
  { id: 'uk-arts-bournemouth', name: 'Arts University Bournemouth', short_name: 'AUB', city: 'Bournemouth', state: 'England', country: 'UK', zip_code: 'BH12 5HH', latitude: 50.7429, longitude: -1.9167, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 3500, international_students: 700, website: 'https://www.aub.ac.uk', aliases: ['AUB', 'Arts Bournemouth'], source: 'hesa', source_id: '10000385' },
  { id: 'uk-birkbeck', name: 'Birkbeck, University of London', short_name: 'Birkbeck', city: 'London', state: 'England', country: 'UK', zip_code: 'WC1E 7HX', latitude: 51.5217, longitude: -0.1308, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 13000, international_students: 2000, website: 'https://www.bbk.ac.uk', aliases: ['Birkbeck'], source: 'hesa', source_id: '10007760' },
  { id: 'uk-open', name: 'The Open University', short_name: 'Open University', city: 'Milton Keynes', state: 'England', country: 'UK', zip_code: 'MK7 6AA', latitude: 52.0249, longitude: -0.7097, type: 'university', campus_type: 'online', sector: 'public', is_public: true, enrollment: 170000, international_students: 10000, website: 'https://www.open.ac.uk', aliases: ['OU', 'Open University'], source: 'hesa', source_id: '10007773' },
  { id: 'uk-buckingham', name: 'University of Buckingham', short_name: 'Buckingham', city: 'Buckingham', state: 'England', country: 'UK', zip_code: 'MK18 1EG', latitude: 52.0008, longitude: -0.9847, type: 'university', campus_type: 'main', sector: 'private_nonprofit', is_public: false, enrollment: 3000, international_students: 1500, website: 'https://www.buckingham.ac.uk', aliases: ['Buckingham'], source: 'hesa', source_id: '10000936' },
  { id: 'uk-law', name: 'The University of Law', short_name: 'ULaw', city: 'London', state: 'England', country: 'UK', zip_code: 'WC2R 2LS', latitude: 51.5115, longitude: -0.1160, type: 'university', campus_type: 'main', sector: 'private_forprofit', is_public: false, enrollment: 14000, international_students: 4000, website: 'https://www.law.ac.uk', aliases: ['ULaw', 'University of Law'], source: 'hesa', source_id: '10067647' },
  { id: 'uk-bpp', name: 'BPP University', short_name: 'BPP', city: 'London', state: 'England', country: 'UK', zip_code: 'EC4V 4BJ', latitude: 51.5119, longitude: -0.1040, type: 'university', campus_type: 'main', sector: 'private_forprofit', is_public: false, enrollment: 11000, international_students: 3000, website: 'https://www.bpp.com/bpp-university', aliases: ['BPP'], source: 'hesa', source_id: '10000825' },
  { id: 'uk-regents', name: "Regent's University London", short_name: "Regent's", city: 'London', state: 'England', country: 'UK', zip_code: 'NW1 4NS', latitude: 51.5266, longitude: -0.1562, type: 'university', campus_type: 'main', sector: 'private_nonprofit', is_public: false, enrollment: 5000, international_students: 3500, website: 'https://www.regents.ac.uk', aliases: ["Regent's"], source: 'hesa', source_id: '10006333' },

  // Scotland additional
  { id: 'uk-napier', name: 'Edinburgh Napier University', short_name: 'Napier', city: 'Edinburgh', state: 'Scotland', country: 'UK', zip_code: 'EH10 5DT', latitude: 55.9316, longitude: -3.2122, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 4000, website: 'https://www.napier.ac.uk', aliases: ['Napier', 'Edinburgh Napier'], source: 'hesa', source_id: '10007772' },
  { id: 'uk-gcu', name: 'Glasgow Caledonian University', short_name: 'GCU', city: 'Glasgow', state: 'Scotland', country: 'UK', zip_code: 'G4 0BA', latitude: 55.8666, longitude: -4.2509, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 20000, international_students: 4000, website: 'https://www.gcu.ac.uk', aliases: ['GCU', 'Glasgow Caledonian'], source: 'hesa', source_id: '10007762' },
  { id: 'uk-rgu', name: 'Robert Gordon University', short_name: 'RGU', city: 'Aberdeen', state: 'Scotland', country: 'UK', zip_code: 'AB10 7QE', latitude: 57.1188, longitude: -2.1371, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 16000, international_students: 3000, website: 'https://www.rgu.ac.uk', aliases: ['RGU', 'Robert Gordon'], source: 'hesa', source_id: '10005500' },
  { id: 'uk-abertay', name: 'Abertay University', short_name: 'Abertay', city: 'Dundee', state: 'Scotland', country: 'UK', zip_code: 'DD1 1HG', latitude: 56.4636, longitude: -2.9742, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 5000, international_students: 800, website: 'https://www.abertay.ac.uk', aliases: ['Abertay'], source: 'hesa', source_id: '10007849' },
  { id: 'uk-queen-margaret', name: 'Queen Margaret University', short_name: 'Queen Margaret', city: 'Edinburgh', state: 'Scotland', country: 'UK', zip_code: 'EH21 6UU', latitude: 55.9347, longitude: -3.0710, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 6000, international_students: 1000, website: 'https://www.qmu.ac.uk', aliases: ['QMU', 'Queen Margaret'], source: 'hesa', source_id: '10005337' },
  { id: 'uk-west-scotland', name: 'University of the West of Scotland', short_name: 'UWS', city: 'Paisley', state: 'Scotland', country: 'UK', zip_code: 'PA1 2BE', latitude: 55.8456, longitude: -4.4310, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 18000, international_students: 3000, website: 'https://www.uws.ac.uk', aliases: ['UWS', 'West Scotland'], source: 'hesa', source_id: '10007800' },
  { id: 'uk-highlands-islands', name: 'University of the Highlands and Islands', short_name: 'UHI', city: 'Inverness', state: 'Scotland', country: 'UK', zip_code: 'IV2 5NA', latitude: 57.4684, longitude: -4.2251, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 8000, international_students: 500, website: 'https://www.uhi.ac.uk', aliases: ['UHI', 'Highlands Islands'], source: 'hesa', source_id: '10007114' },

  // Wales additional
  { id: 'uk-south-wales', name: 'University of South Wales', short_name: 'South Wales', city: 'Pontypridd', state: 'Wales', country: 'UK', zip_code: 'CF37 1DL', latitude: 51.5874, longitude: -3.3313, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 28000, international_students: 4000, website: 'https://www.southwales.ac.uk', aliases: ['USW', 'South Wales'], source: 'hesa', source_id: '10007793' },
  { id: 'uk-wrexham', name: 'Wrexham University', short_name: 'Wrexham', city: 'Wrexham', state: 'Wales', country: 'UK', zip_code: 'LL11 2AW', latitude: 53.0514, longitude: -2.9965, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 8000, international_students: 1000, website: 'https://www.wrexham.ac.uk', aliases: ['Wrexham', 'Glyndwr'], source: 'hesa', source_id: '10007858' },
  { id: 'uk-trinity-st-david', name: 'University of Wales Trinity Saint David', short_name: 'UWTSD', city: 'Lampeter', state: 'Wales', country: 'UK', zip_code: 'SA48 7ED', latitude: 52.1145, longitude: -4.0778, type: 'university', campus_type: 'main', sector: 'public', is_public: true, enrollment: 12000, international_students: 2000, website: 'https://www.uwtsd.ac.uk', aliases: ['UWTSD', 'Trinity Saint David'], source: 'hesa', source_id: '10007858' },
];

// All UK Universities combined
export const ALL_UK_UNIVERSITIES: UKInstitution[] = [
  ...RUSSELL_GROUP,
  ...OTHER_UK_UNIVERSITIES,
];

export default ALL_UK_UNIVERSITIES;
